### ISSUE TITLE
BitcoinAverage API v1 now deprecated and in some case unusable

### ISSUE THREAD

**Issue by Polve** [knowm/XChange#1331]
I'm trying to use bitcoinavg quotation service and I get this error:

`Caused by: si.mazi.rescu.HttpStatusIOException: Can not construct instance of org.knowm.xchange.bitcoinaverage.dto.marketdata.BitcoinAverageTicker: no String-argument constructor/factory method to deserialize from String value ('This version of our API is now depreciated. Please update your code to use v2 immediately, documentation: https://apiv2.bitcoinaverage.com/')`
> at [Source: java.io.StringReader@740314a; line: 1, column: 17] (through reference chain: org.knowm.xchange.bitcoinaverage.dto.marketdata.BitcoinAverageTickers["message"])
>        at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
>        at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
>        at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)

**Comment by timmolter** [comment]
Maybe offer a bounty?
