### ISSUE TITLE
Support Winkdex

### ISSUE THREAD

**Issue by Polve** [knowm/XChange#1340]
http://docs.winkdex.com/

**Comment by jheusser** [comment]
Winkdex is not an exchange so this is probably not the right lib for it

**Comment by rafalkrupinski** [comment]
https://github.com/timmolter/XChange/wiki/Exchange-Support#data-providers ;)

**Comment by jheusser** [comment]
@rafalkrupinski good point 😊

**Comment by makarid** [comment]
Can we close this issue?
