### ISSUE TITLE
c.x.x.s.s.WebSocketEventProducer - reason= draft org.java_websocket.drafts.Draft_17@7c6572b refuses handshake

### ISSUE THREAD

**Issue by antlen** [knowm/XChange#149]
I have used your example code, pasted below, but I keep receiving connection refused errors:
17:31:10.087 [main] DEBUG com.xeiam.xchange.ExchangeFactory - Creating default exchange from class name
17:31:10.159 [main] DEBUG si.mazi.rescu.Config - httpReadTimeout = 30000
17:31:10.572 [main] DEBUG c.x.x.m.v.s.s.MtGoxWebsocketService - Streaming URI='ws://websocket.mtgox.com:80/mtgox?Currency=USD'
17:31:10.572 [main] DEBUG c.x.x.s.s.BaseWebSocketExchangeService - internalConnect
17:31:10.572 [main] DEBUG c.x.x.s.s.BaseWebSocketExchangeService - Attempting to open a websocket against ws://websocket.mtgox.com:80/mtgox?Currency=USD
17:31:13.150 [Thread-2] DEBUG c.x.x.s.s.WebSocketEventProducer - Connection closed by us
17:31:13.150 [Thread-2] DEBUG c.x.x.s.s.WebSocketEventProducer - reason= draft org.java_websocket.drafts.Draft_17@7c6572b refuses handshake
17:31:13.150 [Thread-2] DEBUG c.x.x.s.s.WebSocketEventProducer - onClose
17:31:13.153 [Thread-2] DEBUG c.x.x.m.v.s.s.MtGoxExchangeEventListener - MtGox disconnected         

```
// Use the default MtGox settings
            Exchange mtGoxExchange = ExchangeFactory.INSTANCE.createExchange(MtGoxExchange.class.getName());

            // Configure BTC/USD ticker stream for MtGox
            ExchangeStreamingConfiguration btcusdConfiguration = new MtGoxStreamingConfiguration(10, 10000, 60000, Currencies.BTC, Currencies.USD);

            // Interested in the public streaming market data feed (no authentication)
            streamingExchangeService = mtGoxExchange.getStreamingExchangeService(btcusdConfiguration);

            // Open the connections to the exchange
            streamingExchangeService.connect();

            ExecutorService executorService = Executors.newSingleThreadExecutor();
            Future<?> mtGoxMarketDataFuture = executorService.submit(this);

            // the thread waits here until the Runnable is done.
            mtGoxMarketDataFuture.get();

            executorService.shutdown();
```

**Comment by byron-xie** [comment]
How to solve this problem ？MainActivity: Connection closed by us, info=draft org.java_websocket.drafts.Draft_17@bb482f9 refuses handshake
