### ISSUE TITLE
Support bulk order query in PoloniexTradeService 

### ISSUE THREAD

**Issue by douggie** [knowm/XChange#1516]
Currently the following methods are not implemented:

public Collection<Order> getOrder(String... orderIds) as there is no bulk order query request on poloniex api, I suggest we just iterate over returnOrderTrades.

https://poloniex.com/support/api/

**Comment by herofe** [comment]
I use this exchange in my application. Will give a try at implementing getOrders(String...) by iterating over the Ids one by one. 
Anyone else working on this right now?
