### ISSUE TITLE
BitcoinCharts: bid/ask flipped?

### ISSUE THREAD

**Issue by KiaraGrouwstra** [knowm/XChange#1623]
I just noticed that unlike for other exchanges, for BitcoinCharts the Ticker data I was getting consistently had `bid` > `ask`, which appears opposite from the data I've gotten from some of the other exchanges. I figured I'd file this here as it looks like this could be erroneously swapped around.

**Comment by allenday** [comment]
there is a similar problem with Bittrex where the base/counter pair is inverted.  it requires special logic to use the data from this exchange.
