### ISSUE TITLE
effective rate limiting

### ISSUE THREAD

**Issue by npomfret** [knowm/XChange#1632]
I'm finding that I'm exceeding rate limits occasionally.  Has anyone got an effective way of dealing with them?

I see there s a nice little RateLimiter class in guava.  But i think to use it properly it has to be baked in at the lowest level where the RestProxyFactory is invoked.  It needs to be applied at the request level, and shared across the AccountService, TradeService and MarketDataService.    Wrapping the services in another _rate limiting_ proxy might work. Something like this:

```
  protected TheRockAccountServiceRaw(Exchange exchange) {
    super(exchange);

    ExchangeSpecification spec = exchange.getExchangeSpecification();
    this.apiKey = spec.getApiKey();
    this.signatureCreator = new TheRockDigest(spec.getSecretKey());

    TheRockAuthenticated theApi = RestProxyFactory.createProxy(TheRockAuthenticated.class, spec.getSslUri());

    RateLimiter rateLimiter = spec.rateLimiter();

    if(rateLimiter != null) {
      this.theRockAuthenticated = rateLimit(theApi, rateLimiter, TheRockAuthenticated.class);
    } else {
      this.theRockAuthenticated = theApi;
    }
  }

  private static <API> API rateLimit(API theApi, RateLimiter rateLimiter, Class<API> theClass) {
    return (API) Proxy.newProxyInstance(ClassLoader.getSystemClassLoader(), new Class[]{theClass}, new InvocationHandler() {

      @Override
      public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
        rateLimiter.acquire();

        return method.invoke(theApi, args);
      }
    });
  }
    ...

```

@timmolter thoughts?

**Comment by cymp** [comment]
That's what I am currently doing in a custom wrapper everytime I need to call the api.

**Comment by timmolter** [comment]
That's stretching the scope of this lib, I'd say. Especially since we still don't have a robust solution to the rate limit metadata yet, across all exchanges.

**Comment by npomfret** [comment]
A reason to do it at this base level (once an appropriate model is in place) is that some implementations make multiple API calls for a single high level method call.  So putting your rate limiter in your application won't work as effectively.

**Comment by cymp** [comment]
I do agree, and I can think of specifying this rate at this level for example, not sure if this would be in a third parameter or part of ExchangeSpecification: 
`public static ExchangeWorkerItf create(Class exchangeName, ExchangeSpecification spec)`

**Comment by timmolter** [comment]
Yeah, you're right. I can see integrating something like this into RESCU in a way similar to the nonce factory, where different exchanges have different implementations of rate limiting logic. @mmazi what do you think?

**Comment by npomfret** [comment]
Perhaps a start would be to move the responsibility of creating the api into the ExchangeSpecification? So instead of:

    ExchangeSpecification spec = exchange.getExchangeSpecification();
    TheRockAuthenticated theApi = RestProxyFactory.createProxy(TheRockAuthenticated.class, spec.getSslUri());

You could have:

    ExchangeSpecification spec = exchange.getExchangeSpecification();
    TheRockAuthenticated theApi = spec.createProxy(TheRockAuthenticated.class);

That would allow developers to provide their own wrappers around the low level API, which would allow them to do things like rate limiting.  They'd just need to implement their own ExchangeSpecification (or override the default implementation of the `createProxy` method).

**Comment by mmazi** [comment]
Perhaps XChange could include a `RateLimitingInterceptor`; see the docs:
https://github.com/mmazi/rescu/wiki/Interceptors

Then this interceptor could be registered when the proxy is created as suggested above.

**Comment by douggie** [comment]
Hi,

I have implemented this in cointrader, a fully automated java based algo
trading platform. Take a look at this class for an implementation or just
fire up the cointrader and it is all taken care of for you.

https://github.com/timolson/cointrader/blob/master/src/main/java/org/cryptocoinpartners/module/xchange/XchangeData.java

**Comment by K1ltu** [comment]
Here's a a possible solution it may be a bit dirty but you could always take a variable like a Boolean and have a separate thread that sets it to true every three or four hundred milliseconds and if that bool is true have it do your query or if it's false have it sleep like I said it's not the best solution it's not even a great solution but it would work

**Comment by cowwoc** [comment]
@K1ltu It would not work. The proposed solution is open to race conditions.

**Comment by douggie** [comment]
here is an example of rate limiting
https://github.com/timolson/cointrader/blob/master/src/main/java/org/cryptocoinpartners/module/xchange/XchangeData.java
it takes queries and a period. for example queries=10 and periods =5 would
mean 10 queries every 5 seconds.

the rate at which to poll is limited by the exchange but also by the number
or markets, usage of price data, bandwidth and storage so  seems quite
implementation specific rather than a generic feature.

**Comment by trixprod** [comment]
Hello, still no update on this ?

**Comment by walec51** [comment]
a new proposition in this regard: https://github.com/knowm/XChange/issues/3211
