### ISSUE TITLE
org.knowm.xchange.dto.marketdata.Trade.hashCode()/equals() not Null-safe

### ISSUE THREAD

**Issue by schabe77** [knowm/XChange#1804]
Trade's id may be null, e.g. in OKCoin's trade history a orderId is provided, but no tradeId.

Trade doesn't null-check the tradeId at hashCode() or equals(). Calling these methods on OkCoin's trade history item raises a NullPointerException.

`  public int hashCode() {`
`    return id.hashCode();`
`  }`

**Comment by npomfret** [comment]
Trades have a null id? That feels unlikely, maybe the problem is in the parsing of the results.  Perhaps the data format has changed.

**Comment by schabe77** [comment]
I request the trades at OKCoin:
   UserTrades trades = connection.getLastOrders(CurrencyPair.ETH_USD);

An example result is:
  {"amount":0.23,"avg_price":300.86956521,"create_date":1507796576000,"deal_amount":0.23,"order_id":123456789,"orders_id":123456789,"price":300.88,"status":2,"symbol":"eth_usd","type":"buy"}
(status 2 means "fully filled")

This result is converted to this UserTrade
UserTrade[type=BID, tradableAmount=0.23, currencyPair=ETH/USD, price=300.88, timestamp=Thu Oct 12 10:22:56 CEST 2017, id=null, orderId='123456789', feeAmount=null, feeCurrency='null']

It seems that OkCoin doesn't support TradeIds and yes, may be order_id should be mapped to UserTrade's id (even if it isn't).

In any case: there's no reason why hashCode()/equals() shouldn't be null-safe.

**Comment by npomfret** [comment]
Right.  Sounds to me like the problem is that order's aren't being filtered out.  An order isn't a trade, and the method you are using (`getTradeHistory`?) should only be returning trades.  The exchange method returns both by the sound of it, so the xchange implementation possibly needs to filter out the open orders in this case.

**Comment by schabe77** [comment]
My example order is a trade - it's fully filled. It just seems that OkCoin doesn't provide trade ids.

And again: even if there is no trade id, I don't want to run into a NullPointerException. Usage of id should be null-safe in Trade.

**Comment by npomfret** [comment]
Ok understood, that's very unusual.

You said '_status 2 means "fully filled"_', but the code in `getTradeHistory` passes the value "1" for the status parameter in `getOrderHistory`.  What am I missing here?

**Comment by npomfret** [comment]
Another question (sorry) - do you know what the difference is between the `order_id` and `orders_id` fields that are in the json you posted?

**Comment by schabe77** [comment]
I just updated my code Example - i didn't recognize, that i posted the call to my wrapper-method, sorry.

The API documentation at https://www.okcoin.com/about/rest_api.html states for https://www.okcoin.com/api/v1/order_history.do that in the result there is a field "order_id". Maybe "orders_id" is just for downward compatibility ?!

And the request-status differs from the response-status:
 - "query status: 0 for unfilled orders, 1 for filled orders"
 - "response status: -1 = cancelled, 0 = unfilled, 1 = partially filled, 2 = fully filled, 4 = cancel request in process"

**Comment by npomfret** [comment]
This is a tricky one.  xchange it seems assumes that all trades have a tradeId.  Which doesn't seem unreasonable.  Making the trade id nullable doesn't feel like the right thing to do.  Maybe the parser should put the orderId in the tradeId field (as well as in the orderId field).  If one orderId results in at most one trade then that seems a reasonable thing to do.  But if one orderId results in multiple trades then that cannot work.

**Comment by timmolter** [comment]
I'll chime in when I have more time. Sorry!

**Comment by timmolter** [comment]
Maybe the adapter should use `"orders_id":123456789` as the id. Problem solved.

**Comment by earce** [comment]
Was fixed as part of attached commit
