### ISSUE TITLE
Should Stop Loss orders be considered open ?

### ISSUE THREAD

**Issue by fandre90** [knowm/XChange#1865]
Currently on GDAX, `getOpenOrders(...)` does **not** report active stop loss (and stop loss limit) orders. The fix is trivial, but I just wanted to know if  `getOpenOrders(...)` is expected to return stop loss orders or not.
If not, there is currently no way to retrieve active stop loss orders in XChange and think some methods should be added in the API to do so.

You can vote here: https://goo.gl/forms/P1LC4ZyKKw7fJ1nh2

**Comment by timmolter** [comment]
I think it should be supported. If you want to implement it, go for it!

**Comment by timmolter** [comment]
Yes, they should be considered open.

**Comment by badgerwithagun** [comment]
This fix being just to stop specifying the 'open' filter in the API call? Yes, just saw that myself and was going to remove it in a PR (along with returning instances of `StopOrder` (see #2177). Glad someone else is on it.

**Comment by earce** [comment]
This had a PR submitted against it. (GDAX also is now CoinbasePro)
