### ISSUE TITLE
Support Bithumb

### ISSUE THREAD

**Issue by ezzimaro** [knowm/XChange#1871]
Are there any plans on adding support for Bitthumb
https://www.bithumb.com
API : https://www.bithumb.com/u1/US127

**Comment by Unbr8kbal** [comment]
@timmolter Would it unfair to ask for a Bounty? Do you plan on doing this for free? Like my only issue is obviously love to contribute but until i need the exchange, i wouldn't do it for free.

**Comment by timmolter** [comment]
Yes, you can always ask for a bounty if you want! I don't have time to work on it myself.

**Comment by Unbr8kbal** [comment]
@ezzimaro How fast you need this? Could happen faster with a bounty.

**Comment by sebastienkoch** [comment]
If no one is implementing the Bithumb interface, I propose to do it myself for 0.05 BTC or 0.7 ETH. Is someone still interested?

**Comment by earce** [comment]
Ticket was completed.
