### ISSUE TITLE
implementation request: bitflyer.jp

### ISSUE THREAD

**Issue by npomfret** [knowm/XChange#1959]

**Comment by cristianlucaci** [comment]
hey @npomfret,  any updates on the bitflyer implementation? Thanks

**Comment by npomfret** [comment]
Nope sorry, didn't even start.

**Comment by cristianlucaci** [comment]
thanks, just started the implementation, I am only interested for now in the Margin part, but it wont take long to continue the trading part. #2011

**Comment by npomfret** [comment]
http://bitguru.co.uk/bitflyer-to-operate-in-europe/

**Comment by earce** [comment]
Bitflyer was added to xchange correct?

**Comment by timmolter** [comment]
yes, it was.
