### ISSUE TITLE
GDAX API is outdated?

### ISSUE THREAD

**Issue by cristianlucaci** [knowm/XChange#2012]
hey, I am trying to test the GDAX API, but noticed the model is not matching the model on the exchange's  website. For example, the "GET /accounts"  will return accounts that have more fields than GDAXAccount currently has. 
I couldn't find any open/closed issue discussing about this mismatch, if anyone has mode details or is currently working on this, please let me know. 

https://docs.gdax.com/#accounts

**Comment by timmolter** [comment]
You are correct, it's missing a few fields.

**Comment by cristianlucaci** [comment]
Ive already started the work on this, unfortunately I am unable to test it using a real account, Im waiting for my account activation.

**Comment by earce** [comment]
I guess this is irrelevant given GDAX is now Coinbase.
