### ISSUE TITLE
Invalid hash signature question

### ISSUE THREAD

**Issue by makarid** [knowm/XChange#2142]
Hello,

i would like to ask you about the "invalid hash signature" error. I have create a program in Java and works without a problem. Sometimes while running and everything is OK it drops an invalid hash signature error. What does this error mean? I understand that it has something to do with private API connection only but i cannot understand why it pop's up in random times on random parts of the program. Sometimes it affects a cancelOrder request,sometimes an accountInfo request.Does anyone has experience something like that?
Thanks a lot!

**Comment by npomfret** [comment]
It might be that your are multi threading and the nonce is incorrect?

**Comment by makarid** [comment]
Thanks!
