### ISSUE TITLE
Bittrex getOrder return 0 average price 

### ISSUE THREAD

**Issue by rbwc** [knowm/XChange#2145]
xchange-bittrex:4.3.2

Using Bittrex exchange, performing the below call for any valid order produces 0 averagePrice. All other fields are populated correctly (quantity, etc). I have tested on multiple orders, all return 0. 

exchange.getTradeService().getOrder(uuid);

I believe the correct field on the bittrex api to return for averagePrice is PricePerUnit

**Comment by npomfret** [comment]
@richbwcohen This would be a great first PR is you fancied contributing

**Comment by traviscollins** [comment]
I'm working on this now.

**Comment by earce** [comment]
This fix was pushed
