### ISSUE TITLE
Implementation for Cobinhood

### ISSUE THREAD

**Issue by sirilicious** [knowm/XChange#2147]
Is there a implementation for the Cobinhood exchange?
https://cobinhood.github.io/api-public/#overview

**Comment by danielchrisros** [comment]
Yes pls implement this exchange i need it too!

**Comment by makarid** [comment]
+1

**Comment by aacdevelop** [comment]
+1

**Comment by bryantharris** [comment]
I'd do it for 50 mBTC.

**Comment by makarid** [comment]
@bryantharris i can pay you 50 mBTC.I am waiting for your response.Thanks

**Comment by bryantharris** [comment]
@makarid No problem, should have no issue hitting that date.

**Comment by makarid** [comment]
Great!

**Comment by makarid** [comment]
@bryantharris do you want to add the bounty in this post?

**Comment by makarid** [comment]
@bryantharris i have changed my mind.I have found a project that has all the implementations for the exchanges that i want already.Sorry for that. Thanks for your understanding.

**Comment by digitalchaotics** [comment]
@makarid If you don't mind sharing, what project did you find?

**Comment by makarid** [comment]
@digitalchaotics ccxt is a python library with every exchange that exists.

**Comment by makarid** [comment]
@digitalchaotics do you mean that they have some endpoints not finished? I am trying them out now and it seems prety good.They have a complete documentation also.

**Comment by digitalchaotics** [comment]
@makarid It may be that I tried ccxt first, found it unreliable/incomplete, and moved on to XChange.  Of course, XChange isn't without flaws...  :/

**Comment by makarid** [comment]
Thanks for your responses!

**Comment by bryantharris** [comment]
@makarid I'm about 80% complete with it.  If you decide you want me to resume I'll pick it back up.

**Comment by earce** [comment]
This can also be closed as cobinhood was shutdown.
