### ISSUE TITLE
[35 mBTC Bounty] Implement Coinegg

### ISSUE THREAD

**Issue by cymp** [knowm/XChange#2148]
Hello,

I am paying a 35mBTC bounty to whomever fully implements the [Coinegg ](https://www.coinegg.com/explain.api.html)before January 21st. 25mBTC otherwise.

Thanks.

**Comment by Flemingjp** [comment]
I can take a look at implementing this exchange also.

**Comment by cymp** [comment]
Please proceed, thanks!

**Comment by Flemingjp** [comment]
@cymp  See #2156 As with your other request, this API is also half finished, I check this at first with their customer support team. I've implemented everything I possibly can with the appropriate tests. Currently they have no working Trade service or Account service and I've implemented the data structures for these services to allow it to be quickly implemented when they sort it out.

**Comment by cymp** [comment]
wow this is really annoying, because it is completely useless for me like that... Well thank you I can pay you 18 mBTC now and the 17 remaining when you can finish this. I'm trusting you on this part and will test the whole stuff once it is finished.

**Comment by Flemingjp** [comment]
@cymp I just message the exchange again. It's difficult due to language barriers. They've sent me some test PHP code which I'm testing, so I may be able to push through. I'll update ASAP

**Comment by Flemingjp** [comment]
@cymp Can confirm the PHP code works. Their API documentation is wrong in comparison to their code. Will update in a few hours

**Comment by Flemingjp** [comment]
@cymp I've now implemented the basic Trade Service functions and the Accounts service. Please begin testing them ASAP and report and issues and bugs to me. Feedback with some code samples would be very useful

**Comment by cymp** [comment]
Thanks, will do asap.

**Comment by Flemingjp** [comment]
@cymp Any updates?

**Comment by cymp** [comment]
Sorry I was away these last days, I will be back tomorrow and work on it.

**Comment by Flemingjp** [comment]
@cymp No worries. I'll be busy the next few days also. Will be able to fix anything over the weekend

**Comment by cymp** [comment]
@Flemingjp I am starting to work a bit on integrating your work, do you have an idea what can be used to get all our open orders?

**Comment by Flemingjp** [comment]
@cymp use the getCoinEggTradeView from the CoinEggTradeServiceRaw

**Comment by cymp** [comment]
@Flemingjp ok thanks. By the way, I noticed that you extract the order books by calling "/api/v1/orders/", which returns, if I am correct reading the documentation, "Return the most recent 100 transactions", which does not look like an orderbook. Did I miss something?

**Comment by cymp** [comment]
Should be /api/v1/depth/ if I am correct.

**Comment by Flemingjp** [comment]
@cymp Sure. Apologies I've had a busy week, will look into this some point tomorrow

**Comment by cymp** [comment]
@Flemingjp getAccountInfo() does not work, you created the balances with no id so they can not fit into a map. Have you tested what you implemented? :)

**Comment by cymp** [comment]
@Flemingjp CoinEggExchange.getExchangeSymbols() returns null, I guess ExchangeMetadata is not extracted?

**Comment by Flemingjp** [comment]
@cymp Sorry, my account was still getting verified at the time. The customer service is poor and ended up taking 10 days to do so.

**Comment by cymp** [comment]
@Flemingjp Sorry I was not precise enough. A call to exchange.getAccountService().getAccountInfo().getWallets() throws a "duplicate wallets passed to AccountInfo" error since the wallets have a "null" key.

**Comment by Flemingjp** [comment]
@cymp Apologies, I must have not testing that out. I'll make the fix and also write the appropriate test cases for this issue

**Comment by cymp** [comment]
@Flemingjp I have fixed this and made a PR which has been accepted. The balances only return me BTC and ETH values, is this normal ?

**Comment by Flemingjp** [comment]
@cymp Oh great! I'm afraid I just realised I've been sat on that work for the last week. Currently XAS isn't implemented as a currency, my PR should include that and make it work. I'll push asap

**Comment by cymp** [comment]
@Flemingjp Usually with all of the exchanges I am working with, we are supposed to retrieve all of them, this is unusual to have just BTC and ETH and not all of the altcoins balances...

**Comment by Flemingjp** [comment]
@cymp Sorry, my testing only showed them three coins so I assumed it just displayed coins that can be withdrawn. I'll check further into this

**Comment by cymp** [comment]
@Flemingjp any update?

**Comment by earce** [comment]
This was completed
