### ISSUE TITLE
Implement Tidex

### ISSUE THREAD

**Issue by makarid** [knowm/XChange#2190]
https://tidex.com/public-api

**Comment by daniloguimaraes** [comment]
Nice API documentation.

I would like to help, but I'm already doing #2185 

Probably I will take Tidex after Bitcointrade, ok?

**Comment by makarid** [comment]
Great!

**Comment by banshee** [comment]
That url (https://tidex.com/public-api) is returning a 404 for me.  Maybe it's the same info that's at https://tidex.com/exchange/public-api now.

**Comment by makarid** [comment]
@banshee Yes you are right!
