### ISSUE TITLE
OkCoin using wrong URL/domain

### ISSUE THREAD

**Issue by sirilicious** [knowm/XChange#2192]
I noticed that OKCoin is using this url,
https://www.okex.cn/api/v1/ticker.do?ok=1&symbol=eth_btc

but it should use 
https://www.okex.com/api/v1/ticker.do?ok=1&symbol=eth_btc

**Comment by sirilicious** [comment]
https://github.com/timmolter/XChange/pull/2194

**Comment by theo1985** [comment]
Try:

exchangeSpecification.setExchangeSpecificParametersItem("Use_Intl", true);

.. in your code

**Comment by earce** [comment]
Handled https://github.com/knowm/XChange/pull/2194/files
