### ISSUE TITLE
Coinex

### ISSUE THREAD

**Issue by hpernu** [knowm/XChange#2240]
Anybody have time/skill to implement support for Coinex exchange?

**Comment by daniloguimaraes** [comment]
@hpernu , skill isn't the problem.
Luckly, this project has many skilled developers and contributors.

Actually, the main problem is **time**.

A simple way to solve this problem is [offering a small bounty](https://github.com/timmolter/XChange/wiki#bounties) to the community.

Good luck.

**Comment by hpernu** [comment]
What are normal bounties in these? And I am a professional programmer 
myself.

But I have the same problem: time.
And I am not familiar with how you go about to add new exchange to XChange .
Getting familiar would take even more time.

Is there a tutorial/manual/example somewhere? ( Aside from already 
implemented ones. )

**Comment by daniloguimaraes** [comment]
@hpernu, there is a [Bounty label](https://github.com/timmolter/XChange/labels/Bounty) on issues. It maybe can help you to find a value.

[Design notes](https://github.com/timmolter/XChange/wiki/Design Notes) and [New implementations best practices ] (https://github.com/timmolter/XChange/wiki/New-Implementation-Best-Practices) can help you implementing a new exchange.

**Comment by odrotleff** [comment]
Hey just stumbled upon this issue. Do you still want this @hpernu ? The normal bounty seems to be 50mBTC.

**Comment by discoltk** [comment]
@odrotleff   Are you asking because you're interested in claiming a bounty for adding xchange?   If so I am interested in having this implemented.

**Comment by hpernu** [comment]
It might be possible although, due to time constraints and not having 
intimate knowledge about
the XChange internal API, it might be difficult, and is not going to 
happen soon.

You might still offer a bounty for anyone to take, I guess.

**Comment by earce** [comment]
This exchange was added
