### ISSUE TITLE
margin trading

### ISSUE THREAD

**Issue by pier-rosini** [knowm/XChange#2241]
Is it possible to place margin trades with this lib?
For example Kraken lets trade on margin, how would I set up a limit or market order on margin with xchange?

**Comment by adrmille** [comment]
It's possible, but you have to have to use the raw version of the exchange class (ie: KrakenTradeServiceRaw).
Then you have to build yourself a KrakenStandardOrder using the KrakenOrderBuilder.
See [KrakenTradeServiceRaw.java](https://github.com/timmolter/XChange/blob/develop/xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenTradeServiceRaw.java).placeKrakenMarketOrder source code:

Here an example:
```java
final KrakenType type = KrakenType.fromOrderType(marketOrder.getType());
final KrakenOrderBuilder orderBuilder = KrakenStandardOrder.getMarketOrderBuilder(marketOrder.getCurrencyPair(), type, marketOrder.getOriginalAmount()).withOrderFlags(marketOrder.getOrderFlags()).withLeverage(leverage);
final KrakenStandardOrder krakenStandardOrder = orderBuilder.buildOrder();
final KrakenOrderResponse krakenOrderResponse = krakenTradeServiceRaw.placeKrakenOrder(krakenStandardOrder);
```

**Comment by earce** [comment]
This can be closed as was answered
