### ISSUE TITLE
Bitfinex - Missing information

### ISSUE THREAD

**Issue by Wilwilly** [knowm/XChange#2268]
I'm trying to get different information from Bitfinex, but some of the values are null.

Here are some examples:

```java
// Null username
exchange.getAccountService().getAccountInfo().getUsername()

// Null trading fee
exchange.getAccountService().getAccountInfo().getTradingFee()

// Null trading fee
exchange.getExchangeMetaData().getCurrencyPairs().get(CurrencyPair.ETH_BTC).getTradingFee()

// Wallet with "null" id
exchange.getAccountService().getAccountInfo().getWallets().get(null)
```

As far as I see the values are missing on the metadata file itself: https://github.com/timmolter/XChange/blob/develop/xchange-bitfinex/src/main/resources/bitfinex.json

Should I expect the same on other exchanges? Should I hardcode the fees on my code?

**Comment by Wilwilly** [comment]
Here is another example to show my point. This one is from the official docs.

```java
ExchangeSpecification exSpec = new BitfinexExchange().getDefaultExchangeSpecification();
exSpec.setUserName("me");
exSpec.setApiKey("foo");
exSpec.setSecretKey("bar");
org.knowm.xchange.Exchange exchange = ExchangeFactory.INSTANCE.createExchange(exSpec);

// Get the account information
AccountService accountService = exchange.getAccountService();
AccountInfo accountInfo = accountService.getAccountInfo();
System.out.println(accountInfo.toString());

// AccountInfo [username=null, tradingFee=null, wallets={null=Wallet [id=null, name=null, balances=[Balance [currency=ETH, total=10.0, available=10.0, frozen=0.000000, borrowed=0, loaned=0, withdrawing=0, depositing=0]]]}]
```

I've found a similar result with CexIO, though the username and fees are shown correctly when requested by the currency pair. However *accountService.getAccountInfo().getTradingFee()* returns null as well.

 I'm confused.

**Comment by Wilwilly** [comment]
Any comment on this? Maybe you know @timmolter?

**Comment by npomfret** [comment]
Unfortunately not all metadata is automatically available from all exchanges.  Some is manually typed into json files which you can find at the root of each project.  For example https://github.com/timmolter/XChange/blob/develop/xchange-bitfinex/src/main/resources/bitfinex.json

If no one has keyed in this information then it's not available to you.

If you can find the information and would like to submit a PR that would be helpful.

**Comment by Wilwilly** [comment]
Well, that was my point. So it's not reliable and maybe even if present it may be not up to date.

Thanks.

**Comment by timmolter** [comment]
As @npomfret says, unfortunately all metadata across all exchanges is not 100% implemented and updated.
