### ISSUE TITLE
LakeBTC v1 api has gone

### ISSUE THREAD

**Issue by npomfret** [knowm/XChange#2274]
I was trying to test LakeBTC integration but it looks like the V1 API hasn't just been deprecated but it's been removed completely. I'm just getting 404s

@timmolter I guess we could delete the repo until someone steps up to rewrite it?

**Comment by timmolter** [comment]
It looks like the V2 url is in there:

```
@Path("api_v2")
@Produces(MediaType.APPLICATION_JSON)
public interface LakeBTC {
```

**Comment by npomfret** [comment]
That's weird.  I'm seeing https://api.lakebtc.com/api_v1/

**Comment by npomfret** [comment]
Ah...

```
@Path("api_v1")
@Consumes(MediaType.APPLICATION_FORM_URLENCODED)
@Produces(MediaType.APPLICATION_JSON)
public interface LakeBTCAuthenticated {
```

**Comment by earce** [comment]
This was updated
