### ISSUE TITLE
Binance - getOpenOrders without currency pair is supported by API but unsupported by XChange

### ISSUE THREAD

**Issue by trekmbikes** [knowm/XChange#2287]
Currently BinanceTradeService.java for getOpenOrders() throws an ExchangeException stating CurrencyPair is needed; however this is supported by their API at https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md under /api/v3/openOrders

(it assesses a larger rate limit penalty but should still be accessible)

**Comment by earce** [comment]
completed
