### ISSUE TITLE
GDAX get order by id issue

### ISSUE THREAD

**Issue by bucherarnold** [knowm/XChange#2295]
tradeService.getOrder("f89c7a18-55cf-49e4-843f-80f4f77ebefb");

this will throw the following error:

 java.lang.ArithmeticException: Division undefined
	at java.math.BigDecimal.divide(BigDecimal.java:1741)
	at org.knowm.xchange.gdax.GDAXAdapters.adaptOrder(GDAXAdapters.java:188)
	at org.knowm.xchange.gdax.service.GDAXTradeService.getOrder(GDAXTradeService.java:101)

---------------------------------------------------------------------
tradeService.getOrder("31f2e557-d8eb-4f61-8e2d-7a557ea78a76");

this will throw the following error:

java.lang.NoSuchMethodError: org.knowm.xchange.dto.trade.LimitOrder.<init>(Lorg/knowm/xchange/dto/Order$OrderType;Ljava/math/BigDecimal;Lorg/knowm/xchange/currency/CurrencyPair;Ljava/lang/String;Ljava/util/Date;Ljava/math/BigDecimal;Ljava/math/BigDecimal;Ljava/math/BigDecimal;Ljava/math/BigDecimal;Lorg/knowm/xchange/dto/Order$OrderStatus;)V
	at org.knowm.xchange.gdax.GDAXAdapters.adaptOrder(GDAXAdapters.java:212)
	at org.knowm.xchange.gdax.service.GDAXTradeService.getOrder(GDAXTradeService.java:101)

**Comment by traviscollins** [comment]
The top one (divide by zero) was fixed in commit 80168395f4c97408979c263153a9d8ff30217441

**Comment by traviscollins** [comment]
The bottom error looks like a transitive dependency issue between xchange-core and xchange-gdax. Use "mvn depdendency:tree -Dverbose=true | grep conflict" to check for issues.

**Comment by nichet** [comment]
Also I think in the method GDAXAdapters.adaptOrderStatus() it should be order.getFilledSize().compareTo(order.getSize()) < 0

**Comment by earce** [comment]
Is this still in scope given we have moved to CoinbasePro?
