### ISSUE TITLE
Improvement - Add OrderParams / CurrencyPairOrderParams to support Binance

### ISSUE THREAD

**Issue by trekmbikes** [knowm/XChange#2297]
Currently the API for getOrder() takes just order ID(s), but Binance requires we also provide the CurrencyPair. Currently we just throw a NotYetImplementedForExchange exception (unfortunate for an exchange in the top 5). I would suggest we overload it with an "OrderParam" interface and subinterface called "CurrencyPairOrderParam".

**Comment by mrhead66** [comment]
I agree... same for numerous other exchanges too (KuCoin, OkEx).

**Comment by brilliantnut** [comment]
What's the improvement suggestion? Doesn't this already exist at https://github.com/timmolter/XChange/blob/develop/xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeService.java#L53 ?

**Comment by aleks-azen** [comment]
submitted a pr for this
