### ISSUE TITLE
Historical OHLC data

### ISSUE THREAD

**Issue by IanWorthington** [knowm/XChange#2324]
I was hoping that I might be able to use xchange to get hourly historical ohlc data from cryptopia, but a closer look at the cryptopia api seems to suggest its not available.

cryptocompare seems to provide a historical api for multiple exchanges though.  Has it ever been considered extending the "exchanges" to include that?  Or is there an existing solution I've missed?

i

**Comment by timmolter** [comment]
If it's not yet implemented you'll have to do it yourself. A PR with the solution would be appreciated.

**Comment by IanWorthington** [comment]
Hi Tim

Understand that.  Just wanted to know if there was any other way I'd missed. :)
