### ISSUE TITLE
Port to java9

### ISSUE THREAD

**Issue by rafalkrupinski** [knowm/XChange#2337]
1. [x] make RestProxyFactory mockable
2. [ ] change tests so they don't require PowerMockito
    - [ ] acx
    - [x] anx
    - [x] bitmarket
    - [ ] bleutrade
    - [ ] btcmarkets
3. [ ] upgrade maven in travis
4. [ ] add java9 in travis

@timmolter please assign to me

**Comment by walec51** [comment]
are we planning to move to java.time to?

**Comment by rafalkrupinski** [comment]
@walec51 as much as I'd love to ditch that awful class from all java, what would be the reason to make that effort and break compatibility?

**Comment by timmolter** [comment]
@rafalkrupinski Any more progress here? I feel this is the most pressing change needed at the moment. Can I help in some way?

**Comment by rafalkrupinski** [comment]
I've no work in progress at the moment, feel free to handle any of the above exchanges

**Comment by walec51** [comment]
successfully complied all modules on jdk10 with these changes: https://github.com/knowm/XChange/pull/2731
