### ISSUE TITLE
abucoins implementation..?

### ISSUE THREAD

**Issue by npomfret** [knowm/XChange#2373]
@bryantharris are you planning to implement trade and funding history?

**Comment by bryantharris** [comment]
@npomfret Funding history is implemented I believe (unless I didn't push it or something, it may have come after the initial release so please confirm against snap shot).

Abucoins has a historical trades endpoint.  `GET /products/<product-id>/trades` (which is already implemented in the raw method `AbucoinsMarketDataServiceRaw.getAbucoinsTrades` but it's an un-authenticated general historical end point as opposed to a authenticated user specific trade history end point (which is what would be needed to properly implement `TradeService.getTradeHistory`).  

`TradeService.getTradeHistory` returns a `UserTrades` object so I had interpreted that method as returning the historical trades for the user.  Maybe @timmolter can weigh in and let me know if I interpreted that method correctly.  If it's a general trade history by product call, then I can map it, would take me maybe 30 minutes to implement.  If it's a user specific trade history, I don't see an endpoint to implement that.

I see in the code that `getTradeHistory` throws a `NotYetImplementedForExchangeException` which is misleading, I think it should throw `NotAvailableFromExchangeException`

I'll fix that misleading exception issue at the very least.

So if the answer is that `TradeService.getTradeHistory` is generic, I can knock it out in less than a day.  If the answer is no, `TradeService.getTradeHistory` is per user I don't think there's an end point that supports that for Abucoins.  If you see one I missed feel free to point me to it.

**Comment by npomfret** [comment]
WRT fundingHistory, I must have been looking at an old snap shot. Thanks.

> TradeService.getTradeHistory returns a UserTrades object so I had interpreted that method as returning the historical trades for the user.

That's correct.  I think this is the api call: https://docs.abucoins.com/#list-fills

**Comment by bryantharris** [comment]
Okay, that end point is already supported in the raw class `AbucoinsTradeServiceRaw.getFills`, so I'll knock out the generic layer right now.

**Comment by bryantharris** [comment]
Okay I created a pull request.

See Issues #2230 as there are some paging elements to the API I did not implement because I didn't have a clear path to accessing the HTTP headers in the response needed to properly support paging.

**Comment by npomfret** [comment]
Thanks @bryantharris

**Comment by earce** [comment]
Looks like this was address https://github.com/knowm/XChange/commit/60784b95967b1765e4c47a3051d4ebfb2b42309a and can be closed

**Comment by walec51** [comment]
abucoins exchanges is dead and its module was removed ;)
