### ISSUE TITLE
About Volume Scale in the project

### ISSUE THREAD

**Issue by makarid** [knowm/XChange#2386]
Hello, i saw that there is a priceScale in Metadata of the Exchange class.In order for someone to place any order on any exchange must specify the volume Scale on the bigdecimal.setscale() method.Does anyone knows if any exchange API provide that information,just like the priceScale,in order not to put it manual for every exchange? Thanks for your response!

**Comment by michaelscheung** [comment]
Binance provides this information, but not every exchange does. I was thinking of adding a volumeScale to `CurrencyPairMetaData`, or at least to `BinanceCurrencyPairMetaData`, if we are okay with that.

**Comment by makarid** [comment]
Yes but,how will take all these info if not all the exchanges provide them? Thanks

**Comment by michaelscheung** [comment]
It could be specified in the json file for each exchange. Not every exchange publishes their price scale though, so it could default to 1e-8

**Comment by makarid** [comment]
So the only solution is to hard write the volumeScale to json.

**Comment by timmolter** [comment]
@michaelscheung Yes, that's OK to do at the generic level
