### ISSUE TITLE
abucoins error "INVALID SIGN"

### ISSUE THREAD

**Issue by npomfret** [knowm/XChange#2395]
I'm seemingly randomly getting a "INVALID SIGN" error from abucoins. Anyone else seeing this?

**Comment by cymp** [comment]
I don't get such error.

**Comment by makarid** [comment]
Do you mean Invalid hash signature?

**Comment by npomfret** [comment]
I guess that's what the error means.  The exact text of the error from the API is "INVALID SIGN".

**Comment by npomfret** [comment]
Maybe you have a threading issue or something like that.  You can't make concurrent request with the same api key for a lot of exchanges. I only get this error on abucoins so I don't think that's the issue in my code (but it's the only idea i have right now).

**Comment by makarid** [comment]
Thanks a lot for your reply @npomfret . I didn't know about concurrent issue.Thanks

**Comment by npomfret** [comment]
I can reproduce the issue now.  I use multiple API keys.  When I make a request with one, and then another request with another I get this error.  No idea why though.

**Comment by npomfret** [comment]
Fixed in https://github.com/knowm/XChange/pull/2488
