### ISSUE TITLE
(BUG)Adapter Issue on Quoinex 

### ISSUE THREAD

**Issue by makarid** [knowm/XChange#2412]
Hello, i have found a bug on the QuoineAdapters.adapteOpenOrders class. This method is trying to substring a currencyPair to 2 currencies with the substring method of String class. The thing is that the way that it is implemented works only when the first Currency has 3 characters.If the the first Currency has > than 3 characters,the method returns a Currency that doesn't exist. I saw that when i was trying to getOrders from Qryptos exchange. If you try to get an order of CurrencyPair.ETH_BTC everything works fine.But if you try to get an order of CurrencyPair.FLIXX_BTC which has 5 characters,the method returns FLI/XXE instead of FLIXX/ETH.As i saw the Quoine documentation, the currencyPairCode that they provide hasn't any separator or something.So, one way that i believe we can fix it is by getting the "funding_currency" attribute that the Order response has and sustring it from the rest of "currency_pair_code" .I am not sure but i believe that the funding_currency" attribute is always the counter currency. I am waiting for your responses of how can we fix it.Thanks

**Comment by npomfret** [comment]
That's a good spot.  How many currency pairs does quione support that have symbols that are not three characters long?  

If the exchange returns the market as a pair separated by a '/' character that would be a better way to do it.

**Comment by makarid** [comment]
I don't know how many currencies has Quoine or Qryptos with more than 3 symbols.I believe that we can add the "funding_currency" variable to every response class of Quoine adapters. If @timmolter agree i can try it out.

**Comment by makarid** [comment]
fixed
