### ISSUE TITLE
How to see if wallet of cryptocurrency is in maintenance ?

### ISSUE THREAD

**Issue by octoberfestuser** [knowm/XChange#2464]
##
**Otherwise, if there is nothing already set to do this gracefully how could I accomplish this ?**
I thought of trying to deposit/withdraw that crypto from the exchange and if that doesn't work I'll know it's in maintenance ? but if it works I'd have just done a withdraw/deposit that I didn't actually want to do ? This doesn't seem an option to me. 

Any ideas? Maybe there's already a function for this or something ?

## 
## Any help is largely appreciated.

**Comment by npomfret** [comment]
I don't know of any exchange API that supports this feature (it certainly isn't supported in the xChange api).  But that doesn't mean it's not there.  You'd have to check each the docs of the API for each exchange you want to trade on.

**Comment by octoberfestuser** [comment]
Thx for your answer npomfret.

I did that and the only maintenance I have found is the general server maintenance, not wallet's maintenance.

I sent a ticket to each exchange in hope for an answer.

If anyone has anything to add, maybe an idea to accomplish this or something, I'll be very grateful !

**Comment by cryptoquest** [comment]
Hi @octoberfestuser thank you for sharing this! It's super helpful!
I was wondering if you found any other APIs for wallet maintenance for other exchanges? 
If not, are you aware of any other workarounds?
