### ISSUE TITLE
UserTrade.feeAmount

### ISSUE THREAD

**Issue by devinrsmith** [knowm/XChange#2490]
What's the expectations for the sign (+/-) of UserTrade.feeAmount? Can it be explicitly added to the javadocs?

If I'm charged a fee from an exchange, should I expect UserTrade.feeAmount to be positive? Or negative? (And conversely, I expect that if I receive a rebate from an exchange, the sign should be opposite of what it was for the fee case.)

I ask, because there seems to be an inconsistency in the implementations. I'm getting different signs from Gemini vs Bitfinex.

**Comment by npomfret** [comment]
As I understand it (but this is opinion and not fact) all values should be positive.  I dare say there are inconsistencies, and if you find them please raise a ticket.  That's an easy fix.

**Comment by devinrsmith** [comment]
Here is the example from the Gemini docs:

```json
[ {
  "price" : "30.00",
  "amount" : "1000",
  "timestamp" : 1494871386,
  "timestampms" : 1494871386089,
  "type" : "Sell",
  "aggressor" : true,
  "fee_currency" : "USD",
  "fee_amount" : "75.00",
  "tid" : 44375933,
  "order_id" : "44375931",
  "exchange" : "gemini",
  "is_auction_fill" : false
}, {
  "price" : "31.72",
  "amount" : "3.152585",
  "timestamp" : 1494871242,
  "timestampms" : 1494871242391,
  "type" : "Sell",
  "aggressor" : true,
  "fee_currency" : "USD",
  "fee_amount" : "0.2499999905",
  "tid" : 44375908,
  "order_id" : "44375906",
  "exchange" : "gemini",
  "is_auction_fill" : false
} ]
```

XChange looks to be negating the fee_amount, which is incorrect if it's meant to be positive for a fee.
