### ISSUE TITLE
place several orders

### ISSUE THREAD

**Issue by br0x** [knowm/XChange#250]
Is there any official XChange way to place several orders (almost) simultaneously, that is asynchronously of each other? I think of creating small thread pool and placing orders from independent threads. Should it work at all?

**Comment by matthewdowney** [comment]
Has anybody made progress toward a hack to get around this without the 20ms delay? @timmolter You're right that the computer can only send one request at a time over the wire, but `PollingTradeService::placeLimitOrder` returns the order id, and must communicate with the exchange to do so. So there is definitely a significant speed increase from being able to make non-blocking `placeLimitOrder` calls.

**Comment by timmolter** [comment]
@matthewdowney What exchange are you working with? There is a new improved mechanism in XChange that makes dealing with this much better. When setting up the exchange, you can define a NonceFactory and the nonce is actually created by Rescu at the very moment before the message is sent.

**Comment by matthewdowney** [comment]
@timmolter Excellent! Primarily Bitfinex, Coinbase Exchange, Bitso, and Kraken. How is this done? I took a cursory look at [ExchangeSpecification](https://github.com/timmolter/XChange/blob/f2491a85e26cd526fd3baa3d9c07027345058d16/xchange-core/src/main/java/com/xeiam/xchange/ExchangeSpecification.java) and [ExchangeFactory](https://github.com/timmolter/XChange/blob/f2491a85e26cd526fd3baa3d9c07027345058d16/xchange-core/src/main/java/com/xeiam/xchange/ExchangeFactory.java) but didn't see anything obvious.

**Comment by timmolter** [comment]
take a look around in the `xchange-examples` module. Or search for usages of `NonceFactory` and you'll find what you're looking for.

**Comment by matthewdowney** [comment]
@timmolter Thanks. For anyone else who ends up reading this, I think this is what is being referred to. The only result I found from a search of `xchange-examples` for `NonceFactory`, anyway.

```
    Exchange ANXExchange = ANXExamplesUtils.createExchange();
    ANXV2 ANXV2 = RestProxyFactory.createProxy(ANXV2.class, ANXExchange.getExchangeSpecification().getSslUri());
    ParamsDigest signatureCreator = ANXV2Digest.createInstance(ANXExchange.getExchangeSpecification().getSecretKey());

    ANXWalletHistoryWrapper wallethistory = ANXV2.getWalletHistory(ANXExchange.getExchangeSpecification().getApiKey(), signatureCreator,
        new CurrentTimeNonceFactory(), "BTC", null);
        // There we go ^

    System.out.println("WalletHistory: " + wallethistory.getANXWalletHistory().toString());
    for (ANXWalletHistoryEntry entry : wallethistory.getANXWalletHistory().getANXWalletHistoryEntries()) {
      System.out.println(entry.toString());
    }
```

**Comment by timmolter** [comment]
@matthewdowney Please see <https://github.com/timmolter/XChange/wiki/Design-Notes> and <https://github.com/timmolter/XChange/wiki/Frequently-Asked-Questions> to address your issue. I just updated it for you specifically. Cheers!
