### ISSUE TITLE
bitfinex margin limit order

### ISSUE THREAD

**Issue by sedatdoganer111** [knowm/XChange#2505]
When I try to send a margin limit order to bifinex, It's executed with the market price, ignoring the limit price I set. In the trade history I can see that all the params sent to bitfinex api are correct but the price.

LimitOrder limitOrder = new LimitOrder(orderType, new BigDecimal(order.getAmount()), currencyPair,
                    null, null, priceDecimal);
Set<Order.IOrderFlags> flags = Stream.of(BitfinexOrderFlags.MARGIN).collect(Collectors.toSet());
limitOrder.setOrderFlags(flags);
String orderId = exchange.getTradeService().placeLimitOrder(limitOrder);

**Comment by douggie** [comment]
humm wonder if it is the way you are setting the flags.

LimitOrder limitOrder = new LimitOrder(orderType, volume, currencyPair, "",
null,BigDecimal.valueOf(2800.1));

limitOrder.addOrderFlag(BitfinexOrderFlags.MARGIN) works fine for me to
place limit orders.

**Comment by sedatdoganer111** [comment]
I changed the api key/secret and use what you proposed to send the limit order and it works. 
Thanks,
