### ISSUE TITLE
 USDT=="tetheruso" on bitfinex

### ISSUE THREAD

**Issue by hillerm** [knowm/XChange#2509]
on bitfinex USDT is referred to as "tetheruso" in their api . currently using Currency.USDT seems to cause withdrawal , transactionhistory to have empty returns. 

realizing the proper fix is to add "tetheruso" to "alternativeCodes" in the Currency for USDT. Is there a quick and dirty way to get this working locally ?

**Comment by hillerm** [comment]
im going to close this. Worked with Bitfinex to provide an alias on their side. Using Currency.USDT now returns proper funding records.

**Comment by googya** [comment]
> im going to close this. Worked with Bitfinex to provide an alias on their side. Using Currency.USDT now returns proper funding records.

how do you alias USDT?
