### ISSUE TITLE
web3j and/or bouncycastle

### ISSUE THREAD

**Issue by jnorthrup** [knowm/XChange#2512]
Ethereum uses a specific array of sha3 implementations and this drives ethereum wire protocols for at least one DAP I maintain.  

the checksums are backed by bouncycastle but the web3j layer is impl specific, and tries to be relevant to the web3js api as well.

can i include this in an upcoming PR?  there's no reasonable substitute for Idex

**Comment by timmolter** [comment]
What's the scope of the upcoming PR? I never saw an exchange requiring raw ethereum wire protocols.

**Comment by makarid** [comment]
It is need for decentralized exchanges, in order to sign orders and cancel them.

**Comment by jnorthrup** [comment]
the requirement is here and below it https://github.com/AuroraDAO/idex-api-docs/blob/master/README.md#order 

web3j and contracts in java lack examples, this took a week to bitbang with the architect

**Comment by timmolter** [comment]
OK, go ahead, just exclude the dependencies not needed under web3j, as it seems to pull in a lot of stuff. Ideally you'd just depend on bouncycastle.

**Comment by jnorthrup** [comment]
![image](https://user-images.githubusercontent.com/73514/39330316-6b9dd824-49cb-11e8-87e2-d6b9d7f72189.png)
