### ISSUE TITLE
Roadmap, and 5.0 PR's

### ISSUE THREAD

**Issue by jnorthrup** [knowm/XChange#2517]
rightfully, some developers have expressed grave concerns about refactoring
 * refactoring seems to create so many vast sweeping changes 
 * sweeping changes like reformatting, and refactoring make the PR's unreadable, and so untrusted.
 * all possible PR's and usecases and applications must comply with one and only one development branch 
 * development branch is treated like master branch, -- developers ignore master branch and typically the internet references to this project say "use development"
 * frequently debates languish for long periods of time, awaiting attention
 * beneficial libraries all fall under the term "no new dependencies", and so require prolonged discussion/time
 * things that worked for 5 modules can be significantly less convenient across 70+ modules 
 * exceptions made for some modules have gotten thru without sharing the benefit across all of the applicable modules, making them exceptional rather than improving the whole.  e.g. google collections, assertj, commons-*, making the respective module owners fight harder to preserve status quo and/or fight for the improvements.   

a refactoring-incentivized codebase is difficult with a lack of trust and a minimization of effort, but also compounded by growth of the project making the divide more pronounced.
 
I think that having a roadmap, and discussing features and rapidly spit-balling changes and new features is preferable to the above "grave concerns".  

the project forks have increased in frequency since late 2017.  the ability to read the various forks has been removed due to the crushing numbers on the github hamsters

I maintain several development branches with changes not even worth vetting against the development branch because of the single track policy.  I already have roadmap, and alternate implementations, but now I'm advocating for exchange clients to minimize the process overheads of onboarding a new exchange.  not all of the styleguide and sanctioned practices make our job easier.  

more automated features is probably a good thing.  automated formatters and line-endings is a monumental improvement due to the number of happenstance commits from all varying development platforms in use. 

scripts to perform simplification can be a good thing to arrive at refactored solutions and cheaper new modules and fastger/simpler builds.

this is just what i can come up with off the top of my head.

**Comment by timmolter** [comment]
This project is not my main focus (obviously) and while roadmaps, RFCs, proper git branching and versioning are all good things, I personally don't have the time to manage all that. 

I DO have time to accept and merge small atomic PRs, keep the wheels on the thing and allow it to move forward and pick up some general improvements along the way, and release a new jar once a month. 

I realize this isn't going to please 100% of everyone, but it is what it is. If people find this useful, can easily submit PRs to add new features and fixes, and the code remains un-infiltrated and secure, then the original vision of this project continues on.

**Comment by jnorthrup** [comment]
@timmolter I have been through the wiki a few passes, and the thing that stands out is that you've got a lot of content in there.  the second thing that stands out is that the content has exceeded the scope of time/energy to maintain it, and the project artifacts on the web are as likely to turn up version 1.2 in google as it is to show recent developments (e.g. googling xchange will show Readme with mtgox and 2-3 other exchanges).

I want to run two methodologies by you against what you just posted.  

first is the linux kernel release process.  Linus is a busy guy who invented git, and the basic featureset of what you wrote above against the epitomy of POSIX roadmaps, RFCs, proper git branching and versioning..

is there any amount of linux kernel dev/news verbiage you can link/quote that makes the process more succinct and removes some surface area of the wiki?  

http://12factor.net -- This methodology is older and more pragmatic, and in fact, encompasses but doesn't  conflict with more recent "micro" services and "serverless" architectures.. but given the lack of updates, can't be accused of selling anything.  Kind of epitomizes "the timeless way of building" pattern language approach. 

again I hope you have time to enumerate agreements/disagreements of 12 relevant factors to a degree where the aging wiki can be refreshed and simplified against a similar set of factors and the direction you'd like to see that are less subject to point-in-time, allowing for the wiki to be boiled down to essentials.

**Comment by earce** [comment]
Looking though old tickets given we released 5.0 I guess we can close?
