### ISSUE TITLE
abucoins weirdness in fills response

### ISSUE THREAD

**Issue by npomfret** [knowm/XChange#2529]
I'm getting my trade data from abucoins, but I have the following fills in the response.  For a single order (_407100794_)  I have 2 fills (_2041465 and 2040811_), one of which is showing as a `sell`, and one as a `buy`:

```
  {
    "trade_id": "2041465",
    "product_id": "LSK-BTC",
    "price": "0.00140993",
    "size": "0.32000000",
    "order_id": "407100794",
    "created_at": "2018-04-20T13:38:16Z",
    "fee": "0.00000000",
    "liquidity": "T",
    "side": "sell"
  },
  {
    "trade_id": "2040811",
    "product_id": "LSK-BTC",
    "price": "0.00140789",
    "size": "0.18000000",
    "order_id": "407100794",
    "created_at": "2018-04-20T00:33:00Z",
    "fee": "-0.00018000",
    "liquidity": "T",
    "side": "buy"
  }
```

Also, one has no fee, which indicates that is was a maker fill (only takers have fees), but the `liquidity` is `T` (taker) for both of them.

Any ideas?

**Comment by walec51** [comment]
hmmm maybe a possible bug showing that abucoins forgot that the "side" attribute should mean
could you post the data of the 407100794 order?

**Comment by npomfret** [comment]
```
{
  "id": "407100794",
  "price": "0.00140993",
  "size": "0.50000000",
  "product_id": "LSK-BTC",
  "side": "buy",
  "type": "limit",
  "time_in_force": "GTC",
  "post_only": false,
  "created_at": "2018-04-20T00:33:00Z",
  "filled_size": "0.50000000",
  "status": "closed",
  "settled": true
} 

```

**Comment by walec51** [comment]
having a sell fill from a buy order looks like a bug, could you mail this issue to abucoins developers?

**Comment by npomfret** [comment]
I raised a ticket with their support but haven't had a response yet.  If you can expedite that would be good.  They have the trade and order ids, will that be enough (don't like to give out account details)?

**Comment by npomfret** [comment]
@walec51 if they check their support site, it's ticket 4597

**Comment by walec51** [comment]
I've email my contact in abucoins and send him your ticket number - I hope this will give us some priority in the queue as I'm also just about to release integration with their exchange in my app

**Comment by npomfret** [comment]
@walec51 still no response from abucoins support.  did you hear back from your contact?

**Comment by walec51** [comment]
unfortunately no
judging from their trade volumes and lack of communication they might be abandoning ship

**Comment by walec51** [comment]
well with less then 2 BTC of volume on all markets they are making 1395 $ max income a month from fees

**Comment by npomfret** [comment]
Ha @walec51, like a minute after you replied they sent me this:

> Data show it in that way because you did a transaction with yourself.  We recommend using stp=co flag to prevent self-trading. 

I understand what's happened (and will add the missing flags in), but the data still doesn't quite make sense to me.  If I placed two orders and they crossed, surely my fills should reflect the two order ids.  As it stands, I have one bid order that was filled twice (with a buy and sell fill), and a ask order that wasn't filled at all.

**Comment by npomfret** [comment]
@walec51 you were right - abucoins is going out of business v soon

**Comment by walec51** [comment]
abucoins as removed from develop
