### ISSUE TITLE
Introduction of a SecurityException

### ISSUE THREAD

**Issue by walec51** [knowm/XChange#2533]
I would like to introduce a `SecurityException extends ExchangeException` which would be thrown in the following situations:

- authentications failed - credentials unrecognized by the exchange
- authorization failed - no permission to access some endpoint
- wrong request signature - in exchanges where this type of error is thrown if the API keys are unrecognized

The purpose of this exception is to separate situations where an applications user could have passed improper credentials from technical errors. In consequence this will allow us to provide a better UI experience and error messaging.

Is every one ok with this?

If you are than I'll add this functionality to the following exchanges in the next two weeks:
Binance, BitBay, Poloniex, Bitfinex, Bittrex, Cryptopia, BitMarket, Abucoins

**Comment by npomfret** [comment]
Sounds good to me.

**Comment by timmolter** [comment]
Yes, please do.

**Comment by walec51** [comment]
because a SecurityException is already in java.lang I'm perusing the name ExchangeSecurityExchange for this case

**Comment by walec51** [comment]
If someone has 5 min please check if the code is going in the right direction:
https://github.com/knowm/XChange/pull/2628

**Comment by timmolter** [comment]
Looks good except that you should put the error handling method in the BaseService, rather than in the adapter. See `GDAXBaseService`.
