### ISSUE TITLE
Liqui exchange : Frozen balance is still equal to 0

### ISSUE THREAD

**Issue by trixprod** [knowm/XChange#2538]
On balance listing we can observe that frozen balance for each wallet is still equals to 0.
So the total balance is wrong too.

**Comment by trixprod** [comment]
The liqui API say : 
funds:Your account balance available for trading. Doesn’t include funds on your open orders.

The total balance should be null and frozen balance too.

Checking all actives orders is necessary to compute frozen balance ( on orders ).

**Comment by cymp** [comment]
@timmolter Please close this if you agree to accept https://github.com/knowm/XChange/pull/2839.
