### ISSUE TITLE
Ethfinex : Create XChange implementation ( clone of Bitfinex )

### ISSUE THREAD

**Issue by trixprod** [knowm/XChange#2542]
Ethfinex is a ERC20 token exchange site based on Bitfinex.
The Ethfinex APIs use the same endpoints as the Bitfinex APIs. 

Can we consider an implemention which use a max of Bitfinex impl with a different URL ?

**Comment by alphafoobar** [comment]
I've used the Bitfinex module to connect to Ethfinex - this works if you extend the Bitfinex exchange class and use a different URL. But when I did this Ethfinex was publishing Bitfinex rates... only just for ERC20 markets.

**Comment by trixprod** [comment]
Hello,

I tried your solution. That's fine.
Ethfinex will be a dedicated market to ERC20 only. So i can understand the ERC20 markets only. ( in theory )

For now, Ethfinex continues to use some BTC currency pair. I don't really understand why.
And Bitfinex continues to display ERC20 markets too.

So Ethfinex rates are the same of Bitfinex ( to be confirmed ) as we can see same pairs on both markets.

**Comment by alphafoobar** [comment]
Hi @trixprod 
When I tried it seemed that ethfinex was the ERC20 markets subset of bitfinex - I based my solution off xchange-stream here: https://github.com/alphafoobar/ethfinex-streaming

**Comment by trixprod** [comment]
Hello,
I'm using Bitfinex and Ethfinex ( tweaked Bitfinex URL ) to have all my currency pairs.
Having only ERC20 tokens for Ethfinex is (imho) the normal behavior.

I think Bitfinex, in a near future, will be sticked with BTC pairs and Ethfinex with ETH pairs.
For now, it's a little bit confusing. All balances are shared ( well why not ) and some BTC pairs are still available in the Ethfinex Website.

**Comment by earce** [comment]
https://blog.deversifi.com/introducing-deversifi/ closing as ethfinex has been moved to deversifi
