### ISSUE TITLE
Offering up to 0.25 BTC worth of bounties for exchange implementations

### ISSUE THREAD

**Issue by michaelscheung** [knowm/XChange#2551]
First of all, I just want to express my gratitude to @timmolter and all contributors for this useful and well designed library. I read in the wiki that we can offer bounties for development, and I am willing to provide those for certain exchange implementations. Please let me know if these bounties are reasonable. If they are, I can send the bounties ~~to the address listed on the wiki (1MHMpzFxx4fRSaeYGSxhyEcgux7j4Gqwsc) to be held until the bounties are paid out~~ directly to you. If not, I am willing to make adjustments to better reflect the work needed for each task.

These are the exchanges that I'd be willing to donate a bounty for a complete implementation:
- **15 mBTC for BitflyerExchange.** It's missing TradeService. It also appears to only support Bitflyer Japan and not Bitflyer US - this should be configurable via exchangeSpecification. It appears just changing the URL to "api.bitflyer.com" works, but there may be other differences. API docs: https://lightning.bitflyer.jp/docs?lang=en
- **75 mBTC for BTCC within a week or so, or 60 mBTC otherwise.** It's missing almost everything except for a partially completed MarketDataService. API docs: https://www.btcc.com/apidocs (you probably want BTCC USD Exchange Market Data REST API and the Authentication API)
- **85 mBTC for ZB within a week or so, or 70 mBTC otherwise.** Nothing is implemented yet. API docs (can't find anything in English): https://www.zb.com/i/developer
- **75 mBTC for EXMO within a week or so, or 60 mBTC otherwise.** Nothing is implemented yet. API docs: https://exmo.com/en/api

**Comment by npomfret** [comment]
I'll can take a look at exmo  - will implement just the xchange public API ok?

**Comment by michaelscheung** [comment]
@npomfret would 5 mBTC be fair for that task, leaving 10 mBTC for the private API?

**Comment by npomfret** [comment]
Nope, to be honest most of the exchanges i've implemented have been for 50mBTC.  

When I say the public api, I mean I'll implemented the TradeService, AccountService and MarketDataService where possible.  If there are other API endpoints that do not fit into the xchange api I will not implement those.

**Comment by michaelscheung** [comment]
Apologies for the misunderstanding, By public API I thought you meant just the MarketDataService and metadata. Looking at past bounties, you are correct that 50 mBTC seems to be the standard. I also notice that you've expedited implementations for 75 mBTC. I'd be willing to pay that for an implementation done in a week or so. I also updated the bounties for the other tasks.

**Comment by michaelscheung** [comment]
I noticed that past bounties create a separate issue for each exchange, which makes sense. I mainly created this to get feedback on what bounties are reasonable. So I'll close this issue and open up new ones for each exchange.
