### ISSUE TITLE
[60-75 mBTC Bounty] Implement EXMO

### ISSUE THREAD

**Issue by michaelscheung** [knowm/XChange#2553]
I am offering 75 mBTC for a full implementation of EXMO before 5/11, or 60 mBTC otherwise. API docs: https://exmo.com/en/api Highest to lowest priority are:
1. getOrderBook in MarketDataService
2. All supported operations in TradeService
3. getAccountInfo and getFundingHistory in AccountService
4. ExchangeMetaData (looks like they only have metadata for currency pairs)
5. everything else (I believe it's just getTrades and getTickers, plus deposit/withdrawal)

**Comment by npomfret** [comment]
@michaelscheung i'll try and have it all done tomorrow

**Comment by michaelscheung** [comment]
Thanks for the quick implementation, looks good! I've tested and it's working for me. I also don't have authorization for `withdraw_crypt` and `wallet_history` yet, so that's fine - feel free to @ mention me if and when they get back to you and you're able to implement and test it. Send me your wallet address and I'll send over 75 mBTC.

**Comment by npomfret** [comment]
@michaelscheung i've got the authorisation now so should be able to finish it off today.

The user trade history is still giving me problems though.

**Comment by npomfret** [comment]
@timmolter you can close this i think
