### ISSUE TITLE
[25 mBTC Bounty] Implement TradeService and support US for Bitflyer

### ISSUE THREAD

**Issue by michaelscheung** [knowm/XChange#2554]
I am offering 15 mBTC to finish the implementation of Bitflyer, which is currently missing the TradeService. I would also like to add support for Bitflyer US via exchangeSpecification. I believe it's as simple as changing the URL to api.bitflyer.com but I could be wrong, and would be willing to raise the bounty if it turns out to be more work.

**Comment by michaelscheung** [comment]
Raising this to 25 mBTC

**Comment by CHUANGPEIFENG** [comment]
/

michaelscheung <notifications@github.com> 於 2018年6月9日 週六 05:21 寫道：

**Comment by EricAnderson1000** [comment]
@michaelscheung  I assume this bounty is dead?

**Comment by michaelscheung** [comment]
@EricAnderson1000 sorry for the delayed response, yes this bounty is dead
