### ISSUE TITLE
[Bitmex] Orderbook

### ISSUE THREAD

**Issue by mike789vvv** [knowm/XChange#2568]
Hello)
On BitMEX API Explorer - pair XBTUSD  is worked)
doc:
https://www.bitmex.com/api/explorer/#!/OrderBook/OrderBook_getL2
link to orderbook:
https://www.bitmex.com/api/v1/orderBook/L2?symbol=XBTUSD&depth=25

Did anyone get orderbook for the pair XBTUSD  by MarketDataService.getOrderBook() ?
What type of BitmexPrompt should be specified for the pair  XBTUSD ?

**Comment by wvr** [comment]
Each contract has its own orderbook, so for example:
MarketDataService.getOrderBook(new CurrencyPair("BTC/USD"), BitmexPrompt.PERPETUAL);
The current valid contract-choices are:
PERPETUAL, WEEKLY, MONTHLY, QUARTERLY, BIQUARTERLY
and may be found here:
https://github.com/knowm/XChange/blob/develop/xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/BitmexPrompt.java#L5

**Comment by mike789vvv** [comment]
>> MarketDataService.getOrderBook(new CurrencyPair("BTC/USD"), BitmexPrompt.PERPETUAL);
Current example return "Bitmex does not support the contact BTC/USD/PERPETUAL"

**Comment by wvr** [comment]
@mike789vvv that seems correct - just tested and working for me. Could you include the entire code-snippet you're using?

**Comment by mike789vvv** [comment]
I've  testing again and I'm sorry, you're right, OrderBook for PERPETUAL works correctly))) 
Thank you very match)
