### ISSUE TITLE
Respectful mecanism of API calls to prevent rate limitation

### ISSUE THREAD

**Issue by trixprod** [knowm/XChange#2583]
Hello,
A nice feature would be to implement mechanism to prevent API rate limitation on the rest invocation level.

Example :
If exchange limits 20 calls by second, then force a wait (compute ms to wait).

**Comment by walec51** [comment]
duplicate of https://github.com/knowm/XChange/issues/1632

**Comment by trixprod** [comment]
Oh great, haven't see this.
Should i close ?
