### ISSUE TITLE
[Bitstamp] ArrayIndexOutOfBoundsException in getOrder

### ISSUE THREAD

**Issue by pesua** [knowm/XChange#2590]
Hi guys
I'm getting ArrayIndexOutOfBoundsException when calling TradeService.getOrder() for order with no trades.
The cause is unchecked array access at 
https://github.com/knowm/XChange/blob/develop/xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampAdapters.java#L358
`Date date = bitstampTransactions[0].getDatetime();`

I can send a pull request with fix right away. But I have a question. Is it ok to have null date in the order?

**Comment by npomfret** [comment]
Can you post some sample data that causes the exception?

**Comment by mathvdh** [comment]
I have submitted a PR for this as well as the "Canceled" status which was causing problems ... Let me know if it's fine

**Comment by walec51** [comment]
thank you @mathvdh for the PR - its merged to develop
