### ISSUE TITLE
On Android : BinanceTradeService always throws error: -1022: Signature for this request is not valid.

### ISSUE THREAD

**Issue by karthikemr** [knowm/XChange#2621]
I am able to use all methods in BinanceTradeService on my ubuntu, **but on android it always throws Signature for this request is not valid.** 
**BinanceAccountService** and MarketDataService both working on ubuntu and android. 

`ExchangeSpecification exSpec = new BinanceExchange().getDefaultExchangeSpecification();
        exSpec.setUserName("mybinance");
        exSpec.setApiKey("API-KEY");
        exSpec.setSecretKey("API-SECRET");

  Exchange exchange =  ExchangeFactory.INSTANCE.createExchange(exSpec);

TradeService tradeService = exchange.getTradeService();
        BinanceTradeHistoryParams tradeHistoryParams = (BinanceTradeHistoryParams) tradeService.createTradeHistoryParams();

        tradeHistoryParams.setCurrencyPair(new CurrencyPair("ICX", "BTC"));

        try {

            UserTrades trades = tradeService.getTradeHistory(tradeHistoryParams);

            System.out.println(trades.toString());

        } catch (Exception e) {

            e.printStackTrace();

        }
`
Same piece of code works on ubuntu and fails on android. Please help.

**Comment by walec51** [comment]
did you check if syncing the devices clock helps?

**Comment by bschnider** [comment]
Did you find a solution to your issue ? I am facing the same error with Binance whatever API key I use.
