### ISSUE TITLE
gateio cancelOrder api not work  

### ISSUE THREAD

**Issue by xpao24** [knowm/XChange#2689]
GateioAuthenticated.java 

   @POST
  @Path("private/cancelorder")
  GateioBaseResponse cancelOrder(
      @FormParam("orderNumber") String orderNumber,
      @HeaderParam("KEY") String apiKey,
      @HeaderParam("SIGN") ParamsDigest signer,
      @FormParam("nonce") SynchronizedValueFactory<Long> nonce)
      throws IOException;

the latest gateio api "cancelOrder", FormParam "currencyPair" must be provided

**Comment by cymp** [comment]
Hello,

I am going to fix that.

**Comment by cymp** [comment]
Fixed: https://github.com/knowm/XChange/pull/2690.
