### ISSUE TITLE
gatio ExchangeSpecification tradeService.getOpenOrders()  interface very slow

### ISSUE THREAD

**Issue by xpao24** [knowm/XChange#2691]
1.why use gateio original api is much faster than then ExchangeSpecification  tradeService.getOpenOrders()?
2.Did the ExchangeSpecification support config  HttpConnectionPool?

**Comment by xiaods** [comment]
could you please add some testing on the project.

**Comment by walec51** [comment]
3 feature requests in one issue

if you want to improve this library please prepare z pull request

more tests and support for connection pooling would be welcomed
