### ISSUE TITLE
Kraken - how to  set price precision correctly for each market upon Order?

### ISSUE THREAD

**Issue by hivemall** [knowm/XChange#2726]
the exchange complains about bad price precision: 

```
[2Jorg.knowm.xchange.exceptions.ExchangeException: [EOrder:Invalid price:XICNXXBT price can only be specified up to 6 decimals.]
	at org.knowm.xchange.kraken.service.KrakenBaseService.checkResult(KrakenBaseService.java:87)
	at org.knowm.xchange.kraken.service.KrakenTradeServiceRaw.placeKrakenOrder(KrakenTradeServiceRaw.java:257)
	at org.knowm.xchange.kraken.service.KrakenTradeServiceRaw.placeKrakenLimitOrder(KrakenTradeServiceRaw.java:209)
	at org.knowm.xchange.kraken.service.KrakenTradeService.placeLimitOrder(KrakenTradeService.java:54)
```

I place the order with:

```
LimitOrder limitOrder = new LimitOrder(OrderType.ASK, new BigDecimal(originalAmount), new CurrencyPair(currencyPairString), null, null, new BigDecimal(limitPrice));
		String orderId = exchange.getTradeService().placeLimitOrder(limitOrder);
```

Unfortunate the constructor does not have params object nor precision parameters, only:

> 
> Parameters:
> type Either BID (buying) or ASK (selling)
> originalAmount The amount to trade
> currencyPair The identifier (e.g. BTC/USD)
> id An id (usually provided by the exchange)
> timestamp a Date object representing the order's timestamp according to the exchange's server, null if not provided
> limitPrice In a BID this is the highest acceptable price, in an ASK this is the lowest acceptable price
> 

<br>
<br>
i also get the error with eg liqui, which also seems to be due to precision, how do i set it?<br>

`LiquiException: invalid parameter: rate`  when calling  `.placeOrderLimitSell(...`

**version      <version>4.3.8</version> montly build**

**Comment by hivemall** [comment]
how would i extend this example: 
```
	public String placeOrderLimitBuy(String currencyPairString, double originalAmount, double limitPrice) throws IOException {
		LimitOrder limitOrder = new LimitOrder(OrderType.BID, new BigDecimal(originalAmount), new CurrencyPair(currencyPairString), null, null, new BigDecimal(limitPrice));
		String orderId = exchange.getTradeService().placeLimitOrder(limitOrder);
		return orderId;
	}
```

**Comment by timmolter** [comment]
You can set the precision on the BigDecimal. You can use the ExchangeMetaData class to get the required precision for that exchange (if it's implemented).

**Comment by hivemall** [comment]
i tried to locate it in these services noo success:
```
exchange.getExchangeMetaData()
exchagne.getExchangeSpecification()
```
could you please give an example?

**Comment by scionaltera** [comment]
I use something like this:

```
BigDecimal amount = new BigDecimal(100);
Integer scale = exchange.getExchangeMetaData().getCurrencyPairs().get(currencyPair).getPriceScale();
amount.setScale(scale);
```

Of course you have to check for nulls because `get(currencyPair)` is often null and `getPriceScale()` is also often null. In those cases I default to 8.
