### ISSUE TITLE
Liqui - cumulativeAmount < 0 and originalAmount is 0 upon getOpenOrders()

### ISSUE THREAD

**Issue by hivemall** [knowm/XChange#2727]
The mentioned values `cumulativeAmount` and `originalAmount`  seem to be off:
```
Open orders: 
  [order=LimitOrder [limitPrice=0.00003255, Order [type=ASK, originalAmount=0, cumulativeAmount=-300.0, averagePrice=0.00003255, currencyPair=MGO/BTC, id=533215795, timestamp=Thu Jul 26 20:21:37 CEST 2018, status=NEW]]]
  [order=LimitOrder [limitPrice=0.00002512, Order [type=BID, originalAmount=0, cumulativeAmount=-547.21855095, averagePrice=0.00002512, currencyPair=MGO/BTC, id=533217346, timestamp=Thu Jul 26 20:23:43 CEST 2018, status=NEW]]]
Hidden orders: None
```
after the call:

```
openOrders = exchange.getTradeService().getOpenOrders();
List<Order> listOpenOrders = openOrders.getAllOpenOrders();
```
i try to get the `originalAmount` by `getOriginalAmount()` but it returns 0 and i struggle to make sense of how its calculated:
```
    final BigDecimal filledAmount = orderInfo.getStartAmount().subtract(orderInfo.getAmount());
```

**version      <version>4.3.8</version> montly build**

**Comment by cymp** [comment]
Which version of the library are you using?

**Comment by hivemall** [comment]
i use the version 4.3.8 montly build

**Comment by cymp** [comment]
There's something wrong in LiquiOrderInfo constructor: 
`this.startAmount = new BigDecimal(startAmount != null ? startAmount : "0");` should not work like this because the startAmount is null on ActiveOrders API call, resulting in a bad construction of filledAmount. I am going to fix this today unless you want to do it.

**Comment by cymp** [comment]
And I don't get what you don't understand in the filledAmount, it's pretty straigth forward.

**Comment by cymp** [comment]
But there a wrong case here too, I'm working on it.

**Comment by cymp** [comment]
Fixed.

**Comment by cymp** [comment]
Please note that the originalAmount information is unknown since not given by the Liqui API for active orders, limitOrder.getRemainingAmount() is what you need.

**Comment by hivemall** [comment]
thank you for the quick fix, will test soon;
