### ISSUE TITLE
CexIOExchange:433 - An exception occured while loading the metadata file from the file system

### ISSUE THREAD

**Issue by dmitry-kanunnikoff** [knowm/XChange#2736]
The title speaks for itself. This is a step in the initialization of the exchange.

**Comment by walec51** [comment]
No, it does not... let me guess... you running unit tests via Eclipses JUnit Runner instead of maven which does a poor job of respecting maven resource configuration?

If not the post a stacktrace, logs, info how are you instantiating the client.

**Comment by dmitry-kanunnikoff** [comment]
No, your guess is wrong. I create the client quite standard. Before that everything worked. All I did was update the library from version 4.3.6 to version 4.3.9.
I've attached the stacktrace and the code screenshot (I use Kotlin) to this post.

![pw2llr](https://user-images.githubusercontent.com/7009886/43651646-a0f22f16-974b-11e8-9090-bd3eace12af1.png)
[stacktrace.txt](https://github.com/knowm/XChange/files/2257890/stacktrace.txt)

**Comment by walec51** [comment]
ok, this is the commit that messed up the JSON: https://github.com/knowm/XChange/commit/2ddf13f73f6aa4797c3fb8dba7b1c857a0d54c8f#diff-b139fd82e4215124e84f73df18943847R120

someone just has to remove the last comma in line 120
could you clone the repo, remove it, test if it works for you and submit a PR?
