### ISSUE TITLE
OKex - 'Invalid currency pair' when requesting the transfers history 

### ISSUE THREAD

**Issue by dmitry-kanunnikoff** [knowm/XChange#2748]
OKex [API](https://github.com/okcoin-okex/API-docs-OKEx.com/blob/master/API-For-Spot-EN/REST%20API%20for%20SPOT.md) for a deposits and withdrawals waits for the pairs like `ltc_usd, etc_usd,..` in the `symbol` parameter.

But the current implementation of `getFundingHistory` method in `OkCoinAccountService` class works with the `Currency` instead of `CurrencyPair`:

```
@Override
  public List<FundingRecord> getFundingHistory(TradeHistoryParams params) throws IOException {
    String symbol = null;
    if (params instanceof TradeHistoryParamCurrency
        && ((TradeHistoryParamCurrency) params).getCurrency() != null) {
      symbol = OkCoinAdapters.adaptSymbol(((TradeHistoryParamCurrency) params).getCurrency());
    }
    if (symbol == null) {
      throw new ExchangeException("Symbol must be supplied");
    }
...
```

**Comment by walec51** [comment]
tell me, how can you deposit to a currency pair?

**Comment by dmitry-kanunnikoff** [comment]
@walec51 Are you sure you understand the essence of the problem I described?

**Comment by walec51** [comment]
I do - its a mistake in their documentation and the expect a symbol of a currency, not a currency pair which would make no sense in this context...
