### ISSUE TITLE
Support cancelling and getting orders with params in OkCoinFuturesTradeService

### ISSUE THREAD

**Issue by douggie** [knowm/XChange#2752]
The okcoin futures api (https://github.com/okcoin-okex/API-docs-OKEx.com/blob/master/API-For-Futures-EN/REST%20API%20for%20FUTURES.md) requires that the currency pair, the contract and the order id is specified in the cancellation request. Today this is achieved by looping over the supported currency pairs and contracts and calling the REST endpoint  for each combination until the right pair is found to cancel the correct order.

This approach results in the REST endpoint being hit multiple times for a single request, as okcoin imposes rate limits on their cancelation API's, i am proposing to implement the following to methods to allow the currency pair, contract and order id's to be specified and therefore reduce the number of API calls and reduce the risk of the rate limit kicking in.

```
org.knowm.xchange.okcoin.service.OkCoinFuturesTradeService

public Collection<Order> getOrder(OrderQueryParams... orderQueryParams)
public boolean cancelOrder(CancelOrderParams orderParams) throws IOException
```

**Comment by timmolter** [comment]
sounds reasonable.

**Comment by walec51** [comment]
I see from the above this got merged
