### ISSUE TITLE
Bitfinex example produces HTTP 500 error

### ISSUE THREAD

**Issue by p-v-d-Veeken** [knowm/XChange#2786]
I have the following code (virtually identical to the code in the bitfinex example)
```Java
import org.knowm.xchange.Exchange;
import org.knowm.xchange.ExchangeFactory;
import org.knowm.xchange.ExchangeSpecification;
import org.knowm.xchange.bitfinex.v1.BitfinexExchange;

public class MWE {
    public static void main(String[] args) {
        Exchange bfx = ExchangeFactory.INSTANCE.createExchange(BitfinexExchange.class.getName());
        ExchangeSpecification bfxSpec = bfx.getDefaultExchangeSpecification();

        bfxSpec.setApiKey(...);
        bfxSpec.setSecretKey(...);
        bfx.applySpecification(bfxSpec);
    }
}
```
Which produces the following error: 
```
Exception in thread "main" org.knowm.xchange.exceptions.ExchangeException: si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 500
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:117)
	at nl.frijt.adapter.orderservice.MWE.main(MWE.java:13)
Caused by: si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 500
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
	at com.sun.proxy.$Proxy15.accountFees(Unknown Source)
	at org.knowm.xchange.bitfinex.v1.service.BitfinexAccountServiceRaw.getAccountFees(BitfinexAccountServiceRaw.java:153)
	at org.knowm.xchange.bitfinex.v1.BitfinexExchange.remoteInit(BitfinexExchange.java:66)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:115)
	... 1 more
```
I have checked the API key and secret I'm using with the bitfinex nodejs library and they are correct. 

Is there something obvious I'm missing, or has Bitfinex stopped working for this library?

**Comment by walec51** [comment]
500 error codes suggests a problem at the exchange it self
please try to capture the HTTP request / response using a tool like Wireshark or https://github.com/knowm/XChange/wiki/New-Implementation-Best-Practices#step-3
and send it here and to Bitfinexes support

**Comment by mawoFrijt** [comment]
So after enabling debug messages, we came to the following before the exception:

`2018-09-06 08:40:32,808 INFO  [main] [org.knowm.xchange.bitfinex.v1.BitfinexExchange] Calling Remote Init... 
2018-09-06 08:40:32,816 DEBUG [main] [si.mazi.rescu.HttpTemplate] Executing GET request at https://api.bitfinex.com/v1/symbols 
2018-09-06 08:40:33,029 DEBUG [main] [si.mazi.rescu.HttpTemplate] Request http status = 200 
2018-09-06 08:40:33,051 DEBUG [main] [si.mazi.rescu.HttpTemplate] Executing GET request at https://api.bitfinex.com/v1/symbols_details 
2018-09-06 08:40:38,201 DEBUG [main] [si.mazi.rescu.HttpTemplate] Request http status = 200 
2018-09-06 08:40:38,270 DEBUG [main] [si.mazi.rescu.HttpTemplate] Executing POST request at https://api.bitfinex.com/v1/account_fees 
2018-09-06 08:40:38,369 DEBUG [main] [si.mazi.rescu.HttpTemplate] Request http status = 500 
2018-09-06 08:40:38,371 ERROR [main] [Starter] Exception caught: si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 500
Stacktrace:
org.knowm.xchange.exceptions.ExchangeException: si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 500`

This indicates that Bitfinex has problems with the https://api.bitfinex.com/v1/account_fees endpoint, which I cannot find in the authenticated endpoints of Bitfinex: https://docs.bitfinex.com/docs/rest-auth

Is it possible that they removed the endpoint? But it is weird that they would send 500 as response back for a not existing endpoint...

**Comment by walec51** [comment]
you need to use the trace level to see the responces content in the logs

https://github.com/mmazi/rescu#logging

did you report this to the exchange?

**Comment by davassi** [comment]
I have exactly the same issue and same error response when fetching account fees. Any suggestions?

**Comment by davassi** [comment]
I have exactly the same issue and same error response when fetching account fees. Any suggestions?

After enabling TRACE level on 'rescu' I got the following log stream:

22:33:07.633 [main] DEBUG si.mazi.rescu.HttpTemplate - Executing POST request at https://api.bitfinex.com/v1/account_fees 22:33:07.634 [main] TRACE si.mazi.rescu.HttpTemplate - Request body = {"request":"/v1/account_fees","nonce":"729166347"} 22:33:07.634 [main] TRACE si.mazi.rescu.HttpTemplate - Request headers = {X-BFX-PAYLOAD=eyJyZXF1ZXN0IjoiL3YxL2FjY291bnRfZmVlcyIsIm5vbmNlIjoiNzI5MTY2MzQ3In0=, Accept=application/json, X-BFX-APIKEY=M+HfJj, X-BFX-SIGNATURE=d70fc7f7d36afbe50801a7d0690dfab759dfb51367601e410c6519ade0e3ed4a918e9e1e30d888318f52f9a6b9d9784b, Content-Type=application/json} 22:33:07.634 [main] TRACE si.mazi.rescu.HttpTemplate - Header request property: key='Accept-Charset', value='UTF-8' 22:33:07.634 [main] TRACE si.mazi.rescu.HttpTemplate - Header request property: key='X-BFX-PAYLOAD', value='eyJyZXF1ZXN0IjoiL3YxL2FjY291bnRfZmVlcyIsIm5vbmNlIjoiNzI5MTY2MzQ3In0=' 22:33:07.634 [main] TRACE si.mazi.rescu.HttpTemplate - Header request property: key='Accept', value='application/json' 22:33:07.634 [main] TRACE si.mazi.rescu.HttpTemplate - Header request property: key='X-BFX-SIGNATURE', value='d70fc7f7d36afbe50801a7d0690dfab759dfb51367601e410c6519ade0e3ed4a918e9e1e30d888318f52f9a6b9d9784b' 22:33:07.634 [main] TRACE si.mazi.rescu.HttpTemplate - Header request property: key='User-Agent', value='ResCU JDK/6 AppleWebKit/535.7 Chrome/16.0.912.36 Safari/535.7' 22:33:07.634 [main] TRACE si.mazi.rescu.HttpTemplate - Header request property: key='X-BFX-APIKEY', value='++HfJj' 22:33:07.634 [main] TRACE si.mazi.rescu.HttpTemplate - Header request property: key='Content-Type', value='application/json' 22:33:07.732 [main] DEBUG si.mazi.rescu.HttpTemplate - Request http status = 500 22:33:07.732 [main] TRACE si.mazi.rescu.HttpTemplate - Header response property: key='Strict-Transport-Security', value='[max-age=31536000]' 22:33:07.732 [main] TRACE si.mazi.rescu.HttpTemplate - Header response property: key='CF-RAY', value='[468419985dae6f24-FCO]' 22:33:07.732 [main] TRACE si.mazi.rescu.HttpTemplate - Header response property: key='Server', value='[cloudflare]' 22:33:07.732 [main] TRACE si.mazi.rescu.HttpTemplate - Header response property: key='X-Request-Id', value='[8940d8e6-e55e-491e-bb60-5e86faf9699f]' 22:33:07.732 [main] TRACE si.mazi.rescu.HttpTemplate - Header response property: key='X-Runtime', value='[0.007401]' 22:33:07.733 [main] TRACE si.mazi.rescu.HttpTemplate - Header response property: key='Connection', value='[keep-alive]' 22:33:07.733 [main] TRACE si.mazi.rescu.HttpTemplate - Header response property: key='Set-Cookie', value='[__cfduid=d90d830a2c0abad81ab27e215bf2b06761539289987; expires=Fri, 11-Oct-19 20:33:07 GMT; path=/; domain=.bitfinex.com; HttpOnly]' 22:33:07.733 [main] TRACE si.mazi.rescu.HttpTemplate - Header response property: key='Content-Length', value='[48]' 22:33:07.733 [main] TRACE si.mazi.rescu.HttpTemplate - Header response property: key='Date', value='[Thu, 11 Oct 2018 20:33:07 GMT]' 22:33:07.733 [main] TRACE si.mazi.rescu.HttpTemplate - Header response property: key='Expect-CT', value='[max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"]' 22:33:07.733 [main] TRACE si.mazi.rescu.HttpTemplate - Header response property: key='Content-Type', value='[application/json; charset=utf-8]' 22:33:07.733 [main] TRACE si.mazi.rescu.HttpTemplate - Http call returned 500; response body: {"status":"500","error":"Internal Server Error"}

**Comment by davassi** [comment]
I have exactly the same issue and same error response when fetching account fees. Any suggestions?

After enabling TRACE level on 'rescu' I got the same log stream:

> 23:22:36.171 [main] DEBUG si.mazi.rescu.HttpTemplate - Executing POST request at https://api.bitfinex.com/v1/account_fees
> 23:22:36.172 [main] TRACE si.mazi.rescu.HttpTemplate - Request body = {"request":"/v1/account_fees","nonce":"729178219"}
> ...
>  [main] TRACE si.mazi.rescu.HttpTemplate - Http call returned 500; response body: {"status":"500","error":"Internal Server Error"}

**Comment by walec51** [comment]
5xx errors indicate that there is a problem with the exchange, not the client
did any one send the request / response to Bitfinexes support?

**Comment by davassi** [comment]
I did. I am waiting for their response.

Customer support anyway suggested me to do not throw too fast requests to their exchange. I suspect that the call to 

> https://api.bitfinex.com/v1/symbols_details

followed immediately by 

> https://api.bitfinex.com/v1/account_fees 

is causing troubles...
