### ISSUE TITLE
Get user trade exception

### ISSUE THREAD

**Issue by gligorijenikolic** [knowm/XChange#2792]
I am using this methods to get list of gdax UserTrade:

```
public static Exchange getAuthedGDAX(String key, String secret, String passphrase) {
        Exchange gdax = ExchangeFactory.INSTANCE.createExchange(GDAXExchange.class.getName());
        ExchangeSpecification spec = gdax.getDefaultExchangeSpecification();
        spec.setApiKey(key);
        spec.setSecretKey(secret);
        spec.setExchangeSpecificParametersItem("passphrase", passphrase);
        Exchange gdx = ExchangeFactory.INSTANCE.createExchange(spec);
        return gdx;
    }

    public static List<UserTrade> getGDAXTrades(String key, String secret, String passphrase) throws IOException {
        Exchange gdx = getAuthedGDAX(key, secret, passphrase);
        TradeService ts = gdx.getTradeService();
        return ts.getTradeHistory(ts.createTradeHistoryParams()).getUserTrades();
    }
```

and I am getting this exception:

org.knowm.xchange.exceptions.ExchangeException: org.knowm.xchange.gdax.dto.GDAXException: query must contained either product_id or order_id (HTTP status code: 400)

this code worked 2 weeks ago, and now I am getting exception.

**Comment by gligorijenikolic** [comment]
Thank you for interesting to help, in the meantime I founded the solution.

First gdax is deprecated and migrated to xchange-coinbasepro.

The solution is, like you mentioned, to pass CurrencyPair as param or order_id as well:

`List<CurrencyPair> pairs = fetchUserPairs(gdx);
            CoinbaseProTradeServiceRaw.GdaxTradeHistoryParams params;
            List<UserTrade> trades = new ArrayList<>();
            for (CurrencyPair pair : pairs) {
                params = new CoinbaseProTradeServiceRaw.GdaxTradeHistoryParams();
                params.setCurrencyPair(pair);

                List<UserTrade> helpTrades = ts.getTradeHistory(params).getUserTrades();
                if (helpTrades.size() > 0)
                    trades.addAll(helpTrades);
}`

**Comment by timmolter** [comment]
make sure you're using the coinbasePro module from here on out.
