### ISSUE TITLE
Max Order Rate?

### ISSUE THREAD

**Issue by tmathur** [knowm/XChange#2795]
Is there a limit to the number of orders that can be sent using XChange

**Comment by douggie** [comment]
nope it is thread safe so you can have 1000's of threads sending in 1000's
of orders at the exact same instant. however the exchanges do have limits
some on order entry some on cancelation rates it varies exchange to
exchange abd has to be handle vua code outside the xchange adapters take a
look at
https://github.com/timolson/cointrader/blob/master/src/main/java/org/cryptocoinpartners/module/xchange/XchangeOrderService.java
as an example.

**Comment by tmathur** [comment]
Thanks for the info.
What is this rate limit used for?
https://github.com/knowm/XChange/blob/develop/xchange-kraken/src/main/resources/kraken.json#L284

**Comment by douggie** [comment]
specfied in krakens api docs.

https://www.kraken.com/help/api

**Comment by tmathur** [comment]
thanks!
