### ISSUE TITLE
Suffering from severe latency

### ISSUE THREAD

**Issue by szd116** [knowm/XChange#2796]
I don't know if it's just me, I'm only able to do 100 ms per trade. meaning send an newOrder and get an newOrderID back. I tested on Bittrex and HITBTC. how's everyone else's latency?

**Comment by douggie** [comment]
Hi,

Welcome to crypto! The majority of latency is the internet, depending on
where you are in the world Bittrex.com is between 20 and 120 ms, assume you
are around 30ms, that is 60ms per round trip, leaving you around 40ms
unaccounted for, that I suspect is the time the exchange is taking to add
your order to the matching queue, sometimes they give you a time it was
added on the raw response so you can see the delay. The matching engine on
the exchanges vary wildly, and can sometimes take upto 2-3 seconds to add
new orders to the matching queue.

**Comment by szd116** [comment]
Thank you Douggie for the kind comment, I will follow up if I find anything that could help improve the latency little bit. Thanks again for your time.
