### ISSUE TITLE
CoinbasePro ticker issue

### ISSUE THREAD

**Issue by bucherarnold** [knowm/XChange#2815]
CoinbasePro ticker is not supported for ETH/GBP currency pair:

Note:
CoinbaseProMarketDataServiceRaw:checkProductExists() will return false in case of ETH/GBP currency pair.
exchange.getExchangeSymbols() not returns all supported currency pairs

**Comment by cymp** [comment]
This can come from the fact that the symbols are sometimes read from a hard coded json in XChange. The reason can be:
- There are not available from the API
- They are, but the the remoteInit does not call the API endpoint

Both case would require a PR.

**Comment by jakubkalicki** [comment]
Hey @bucherarnold, @timmolter,
I wanted to fix this, but seems like issue is already solved.

**Comment by earce** [comment]
This can be closed as seems to be resolved.
