### ISSUE TITLE
 Codes instead of double quotes and other json symbols

### ISSUE THREAD

**Issue by yurivin** [knowm/XChange#2819]
I have to add method with parameters. And one of FormParams is a json string. 
So I have codes instead of symbols which target server can't understand.
I just know that target server is written in PHP

15:18:08.022 [default] [main] TRACE si.mazi.rescu.HttpTemplate - Request body = currency=EUR&amount=0&password=qazzaq&transferDetails=%7B%22firstname%22%3A+%22First+Name%22%2C+%22lastname%22%3A+%22Last+Name%22%2C+%22iban%22%3A+%22345345%22%7D 

I got Error TransaferDetails should be a simple object.

**Comment by walec51** [comment]
what? how does this relate to the XChange library? which module?

**Comment by yurivin** [comment]
I write new module. I should have request to the exchenge where one of fields is Json inside a String field.

**Comment by walec51** [comment]
well standard form params should be encoded as you see in the log
if the server excepcts a non standard format that you cannot relay od form params encoding provided by the client library but build the entire request body by your self

**Comment by yurivin** [comment]
Looking to make it with Apache HTTP client I see a problem to create signature for request

**Comment by walec51** [comment]
just pass the request body as a string that you prepared and encoded your self without the @FormParam annotation
