### ISSUE TITLE
HELP - Support Required With XChange-Streams

### ISSUE THREAD

**Issue by Flemingjp** [knowm/XChange#2831]
_[Releveant XChange-Stream Issue Here](https://github.com/bitrich-info/xchange-stream/issues/234)_

Hello all,

I've recently been working on the sister project [XChange-Streams](https://github.com/bitrich-info/xchange-stream) to try and rejuvenate the development and bring it to a 4.3.11 release in-line with this project. Progress has been made, yet has slowed in the last few days as the current active developers lack any experience using the **Bitmex exchange**.

Currently [3 of the 4 milestone PRs](https://github.com/bitrich-info/xchange-stream/pulls?utf8=✓&q=bitmex+is%3Aopen+is%3Apr+milestone%3A4.3.11+) are for fixing and maintaining the Bitmex exchange. We would love it if anyone from here would mind taking a look at these PRs and testing and reviewing the code.

Any help would be much appreciated.

**Comment by earce** [comment]
This ticket can be closed as it was merged in.
