### ISSUE TITLE
Trades.java class is incorrectly comparing ID strings

### ISSUE THREAD

**Issue by shimonm** [knowm/XChange#2836]
Trades.java contains the following:

```
@Override
public int compare(Trade trade1, Trade trade2) {
    return trade1.getId().compareTo(trade2.getId());
}
```

Since `.getId()` returns a String, comparing two Strings using `compareTo` is a lexicographical comparison, and would not work reliably, especially when the length of the String is different. 

Consider this example:

```
public static void main(String[] args) {
  String id = "100";
  // check if the value is less than 100
  System.out.println(id.compareTo("99"));
  // check if value is equal to 100
  System.out.println(id.compareTo("100"));
  // check if value is greater than 100
  System.out.println(id.compareTo("101"));
}
```

Console:
```
-8
0
-1
```

`"100".compareTo("99")` returns a negative number which is lexicographically correct, but if these are trade Ids, then this is a bug. 

We should therefore change the TradeIDComparator in Trades.java to convert the String into a BigInteger or Integer prior to the comparison.

something like this:
```
@Override
public int compare(Trade trade1, Trade trade2) {
	BigInteger id1 = new BigInteger(trade1.getId());
	BigInteger id2 = new BigInteger(trade2.getId());
	return id1.compareTo(id2);
}
```

**Comment by cymp** [comment]
If you really want to do that, why not just adding a BigDecimal test in the existing compareTo method?

**Comment by cymp** [comment]
@shimonm I addressed your problem in https://github.com/knowm/XChange/pull/2839, dealing with hexadecimal IDs as well.

**Comment by shimonm** [comment]
Thank you! closing
