### ISSUE TITLE
OKEX needs to support API v3

### ISSUE THREAD

**Issue by declan94** [knowm/XChange#2841]
OKEx has launched their new version of API (v3). Although API v3 and v1 are currently both supported, API v1 will be totally removed someday in the future. So the support for API v3 needs to be added into this repo.

**Comment by roeiba** [comment]
+1

**Comment by slix007** [comment]
The deadline was set by Okex.
> API ACTION REQUIRED: We will no longer support certain endpoints of our V1 WebSocket API from 5am Feb 19, 2019 (CET, UTC+1). Please change your API settings / switch to V3 immediately to avoid disruption in the future.

**Comment by declan94** [comment]
I'm working on it here: https://github.com/declan94/XChange/tree/okex-v3

Anyone who wants to contribute, please contact me. chenye94@qq.com

**Comment by andre77** [comment]
this issue could be closed, since at least parts of the v3 API are already in place
[see](https://github.com/knowm/XChange/tree/develop/xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3)
