### ISSUE TITLE
Service of chart ( data history with timeframe ) provider

### ISSUE THREAD

**Issue by trixprod** [knowm/XChange#2873]
Regarding the XChange API, we lacks of some interfaces to fetch chart history ( ticker data ) on differents timeframes.

Some exchanges provide this kind of data. As example Bittrex provides chart data.
A method already exists in BittrexMarketDataServiceRaw : 
List<BittrexChartData> getBittrexChartData

This method is never used, i guess there are some other in others exchanges.

So, why not creating a method in MarketDataService ?
```
List<ChartData> getChartData(ChartParams)

ChartData
  private final Date timeStamp;
  private final BigDecimal open;
  private final BigDecimal close;
  private final BigDecimal high;
  private final BigDecimal low;
  private final BigDecimal volume;
  private final BigDecimal baseVolume;
  private final String timeframe 
```

**Comment by walec51** [comment]
the BittrexMarketDataServiceRaw.getBittrexChartData method is used by many clients that relay on exchange specific features

do some research first if there is any generic way to window tickers implemented by most exchanges so we can add this information to: https://github.com/knowm/XChange/wiki/Generic-feature-candidates

ps. we already have a Ticker model, adding a ChartData model with timeframe seams pointless

**Comment by timmolter** [comment]
Most exchanges don't have chart data endpoints. For the ones that do, you'll have to use the non-generic method like you've noted.

**Comment by trixprod** [comment]
Hello,
Ticker and ChartData or (CandleData) are things quite different.
A ticker is firstly an instant value of a currency pair on a market. All others data ( vol / open / close ) may be  :
- Sliding window data ( last 24h of volume as example )
- Snapshot of 1D data ( last close ? and open of the day ).

With tickers you can't do chart analysis as traders need a common representation of data ( same ticker open / close hour of day ).

Moreover the timeframe is just a need, some traders want to see 15mn candlesticks ( short term trading ) and other 1 week ( long term trading or investors ).

So, well, we need a new kind of data. (Candle / ChartData ? ) or just add the timeframe on the ticker.

Most exchanges don't have chart data endpoints, that's true. But it becomes less and less true.

A quick search in some exchanges api give me this :
https://docs.bitfinex.com/v2/reference#rest-public-candles
https://docs.pro.coinbase.com/?r=1#get-trades
https://www.bitmex.com/api/explorer/#!/Trade/Trade_getBucketed

With bitfinex / coinbase / bitmex / bittrex ( already impl ) we can have historical candle informations.

I will work on this feature in my fork.
Will do a pull request if i get results.

**Comment by timmolter** [comment]
Yeah, we could add a timeframe to Ticker where 24 Hr is the default.

**Comment by walec51** [comment]
does it make sense to at a property to an object that applies to an entire list of them?

I mean: you will never get a list that has tickers with various timeframes

**Comment by timmolter** [comment]
@walec51 many times a single ticker is requested so the field would need to be somewhere. If we only ever requested lists of Tickers that all had the same timeframe, then it would make more sense to not put it in the Ticker object.

**Comment by walec51** [comment]
maybe this would be cleaner:

```
public class SingleTicker extends Ticker {
    private Duration timeframe; 
    // ... getters, etc ...
}
```

```
public class TickerSeries extends ArrayList<Ticker> {
    private Duration timeframe; 
    // ... getters, etc ...
}
```

**Comment by trixprod** [comment]
Binance provides candles api endpoint :
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

Kline/Candlestick data
GET /api/v1/klines

**Comment by trixprod** [comment]
> maybe this would be cleaner:
> 
> ```
> public class SingleTicker extends Ticker {
>     private Duration timeframe; 
>     // ... getters, etc ...
> }
> ```
> ```
> public class TickerSeries extends ArrayList<Ticker> {
>     private Duration timeframe; 
>     // ... getters, etc ...
> }
> ```

The thread is closed but that idea of candles provider is still on my mind.
For the question of "timeframe" i'm convinced that we have to do the most simplest solution.
i.e : Just add a timeframe in Ticker entity.

**Comment by timmolter** [comment]
yes. And just set it to 24hr as default
