### ISSUE TITLE
Hibernate support

### ISSUE THREAD

**Issue by Hypeon** [knowm/XChange#2884]
Guys, what do you think about implementing Hibernate mapping for whole project? It would be a nice improvement for developers that want to start using this XChange library. 

Actually I started working on this in my application for Binance exchange.

**Comment by walec51** [comment]
your free to do that in a separate project but the core library should not have any dependency do JPA

**Comment by Hypeon** [comment]
Ok, i will consider this. Maybe more people will be interested.
