### ISSUE TITLE
Bitmex exchange metadata and use of currency pairs is inconsistent

### ISSUE THREAD

**Issue by badgerwithagun** [knowm/XChange#2886]
If I do the following:
```
 Exchange exchange = ExchangeFactory.INSTANCE.createExchange(BitmexExchange.class.getName());
 System.out.println(exchange.getExchangeMetaData().getCurrencyPairs().keySet());
```
I get:
```
[BTC/BTC, EOS/BTC, BCH/BTC, ADA/BTC, ETH/USD, ZEC/BTC, TRX/BTC, XLM/BTC, LTC/BTC, \
XRP/BTC, BTC/USD, ETH/BTC, DASH/BTC, XMR/BTC, ETC/BTC]
```
There a a few problems here

- Several of these pairs aren't actually supported by Bitmex (looks like `bitmex.json` is just a copy & paste. I can fix that easily)
- `BTC/BTC`?
- The fact that `BTC` is used instead of `XBT`.

This last bit is interesting.  The code in `org.knowm.xchange.bitmex.BitmexAdapters.adaptToExchangeMetaData` seems to do this deliberately, but...
```
System.out.println(exchange.getMarketDataService().getTicker(CurrencyPair.BTC_USD));
```
... returns null, whereas...
```
System.out.println(exchange.getMarketDataService().getTicker(new CurrencyPair("XBT", "USD")));
```
... works (as I would expect, to be honest!)

How _should_ this work?  Should Bitmex accept XBT as one might expect (in which case it's the exchange metadata implementation that's wrong), or should it translate BTC to XBT internally (in which case the first of those two examples should work, but not the second)?

My inclination is to remove all the cleverness in `org.knowm.xchange.bitmex.BitmexAdapters.adaptToExchangeMetaData` and make it use Bitmex-native currency codes throughout.

**Comment by badgerwithagun** [comment]
It seems to be a bit worse than I thought.  Here's what I have to do to get the ticker and trades for ADA:
```
System.out.println(exchange.getMarketDataService().getTicker(new CurrencyPair("ADA", "Z18")).getLast());
System.out.println(exchange.getMarketDataService().getTrades(new CurrencyPair("ADA", "BTC"), BitmexPrompt.QUARTERLY));

So I can't use the same currently pair to get trades as I do for tickers.  Anyone know why?  Why not just make it `ADA/Z18`, `XBT/Z18`, `XBT/USD` across the board, in line with Bitmex' own representation, and get rid of `BitmexPrompt`?

It seems doomed to failure to try and make the pairs line up with other exchanges, given that Mex's swap contracts aren't even sold/priced in line with other exchanges (when buying 100 on `XBT/USD` you're actually buying 100 USD's worth, not 100 BTC).

**Comment by jakubkalicki** [comment]
Hey, @badgerwithagun 
I could take care of this issue, if you like.

**Comment by badgerwithagun** [comment]
That'd be amazing, @jakubkalicki.  It never seems to make it to the top of my priority list!

**Comment by jakubkalicki** [comment]
Ok, i'm starting then 😃

**Comment by badgerwithagun** [comment]
_Dzięki!_ Happy to review/help test/etc.

**Comment by badgerwithagun** [comment]
A few test cases based on my thinking here:

```
assertEquals(new CurrencyPair("XBT", "USD"), exchange.determineActiveContract("BTC", "USD", PERPETUAL);
assertEquals(new CurrencyPair("LTC", "H19"), exchange.determineActiveContract("LTC", "BTC", QUARTERLY);
assertEquals(new CurrencyPair("XBT", "H19"), exchange.determineActiveContract("BTC", "BTC", QUARTERLY);
```

**Comment by jakubkalicki** [comment]
Ok, now it's implemented it the way you suggested.

I'm wondering what should be done with this adaptToExchangeMetaData method. 
Some options here:
1. Just remove it, it's seems to be useless
2. Load currency pairs and currencies in the same way as in determineActiveContract method
3. Something else?

**Comment by badgerwithagun** [comment]
Fantastic!  Two remaining parts to this:

We still want to be able to query the exchange metadata via XChange and get a list of the currently active contracts using:
```
Exchange exchange = ExchangeFactory.INSTANCE.createExchange(BitmexExchange.class.getName());
 System.out.println(exchange.getExchangeMetaData().getCurrencyPairs());
```
So the results of the API query have to be merged into the `ExchangeMetaData`.  What we want to remove is all the conversion from the Bitmex instrument symbols, and just return them directly converted into `CurrencyPair`.  So I don't think the method should be removed, just simplified - no more symbol conversions, just augment the static method data from `bitmex.json`, just as all the other exchange implementations do (see Binance or Bitfinex for examples).

The second issue is that several methods like `MarketDataService.getTrades` and `getOrderBook` (and presumably others on `TradeService` and `AccountService`) are actually expecting the converted symbols.  It's inconsistent.  One must fetch tickers like this:

```
exchange.getMarketDataService().getTicker(new CurrencyPair("XBT", "USD"));
```
But one must fetch trades and order books like this:

```
exchange.getMarketDataService().getTrades(new CurrencyPair("BTC", "USD"), PERPETUAL);
exchange.getMarketDataService().getOrderBook(new CurrencyPair("BTC", "USD"), PERPETUAL);
```
Instead, all API methods should just accept `new CurrencyPair("XBT", "USD")`. The only API method where `BitmexPrompt` should be accepted is your new `determineActiveContract` method.

**Comment by jakubkalicki** [comment]
Second issue is solved, now BitmexMarketDataService is consistent with other services. I have also added few integration tests. Probably tomorrow i will take care of meta data.

**Comment by jakubkalicki** [comment]
Done
