### ISSUE TITLE
[Feature Request] Request for a fat jar for dll creation

### ISSUE THREAD

**Issue by mohanc4547** [knowm/XChange#2897]
Can a fat jar of the entire solution be placed in one of the folders.
I come from the land of dotNet, and a dll is all i need.
Planning to create a dll out of the fat jar, if a fat jar is provided. The dll in itself if provided is also welcome
Thanks in advance

**Comment by walec51** [comment]
If you need a fat jar you have to learn how to build one your self.
Usually fat jars are build for applications that are distributed as a single jar file. No one does it for library jars and should not expect that someone here will support such an odd solution for you.
