### ISSUE TITLE
Kucoin 2.0 API

### ISSUE THREAD

**Issue by badgerwithagun** [knowm/XChange#2914]
Is anyone working on implementing this? I don't want to duplicate effort.

Happy to assist if anyone wants to spread the load.

**Comment by timmolter** [comment]
no one that I know of is working on it.

**Comment by casoc** [comment]
@badgerwithagun 
Hi,  bro. 
I am the developer in Kucoin exchange. 
Are you still implementing the Kucoin 2.0 API? 
Maybe I can provide Kucoin 2.0 official JAVA SDK for you.

**Comment by badgerwithagun** [comment]
I'll probably do this soon.

**Comment by badgerwithagun** [comment]
Yup. now underway, using the Java SDK, which speeds things up loads.

Tickers and exchange metadata working.  Will post a branch soon in case anyone wants to play with the work in progress.

**Comment by badgerwithagun** [comment]
Hey @casoc, is there some rate limiting built into the API? I am trying to simulate a rate limit ban so I can make sure I'm converting the exception correctly, but every call I make to the API blocks for about 1 second before returning.

**Comment by badgerwithagun** [comment]
Work in progress: https://github.com/badgerwithagun/XChange/tree/kucoin-2.0

**Comment by purekid** [comment]
Hi @badgerwithagun , Thank you very much for your work, rate limit is not fully configured in the sandbox environment.

**Comment by badgerwithagun** [comment]
Kucoin 1.0 is now dead, so I'm going to update #2946 with the removal of the 1.0 API implementation.

**Comment by anhtuantt** [comment]
Hello badgerwithagun,
Thank you for your great contribution. I also want to replace Kucoin 1.0 with your change ASAP (I'm also using Kucoin 1.0 APIs of java XChange library). Could you show me the way to do it?

**Comment by badgerwithagun** [comment]
Hi @anhtuantt, I've only implemented ticker, order book and public trade history so far. You can use it by adding jitpack as a repository:

```
repositories>
      <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
        <releases>
          <enabled>true</enabled>
          <updatePolicy>never</updatePolicy>
          <checksumPolicy>warn</checksumPolicy>
        </releases>
        <snapshots>
          <enabled>false</enabled>
        </snapshots>
      </repository>
    </repositories>
```

Then:

```
dependency>
        <groupId>com.github.badgerwithagun.XChange</groupId>
        <artifactId>THE ARTIFACTS YOU NEED</artifactId>
        <version>kucoin-2.0-SNAPSHOT</version>
      </dependency
```
This is only temporary and I can't guarantee it won't be broken as I keep adding changes. Read the jitpack instructions and you'll see how to pin to a specific revision hash.

**Comment by anhtuantt** [comment]
Thank you for your information. Could you let me know your schedule or when Kucoin 2.0 is completely supported? I will wait until that time.

**Comment by badgerwithagun** [comment]
I'm aiming for `getAccountInfo` in the next week, then probably `getOpenOrders` and `getTradeHistory` next, 1-2 weeks, then finally `placeLimitOrder`, `cancelOrder` and `placeStopOrder`, in another week. I will stop there. No guarantee on timescales; this is just what I'm aiming for but I have some higher priorities.

**Comment by anhtuantt** [comment]
I'm wondering how you could share me some tasks? I took a lot of time to work with Xchange library, so i could give my contribution for the community if you have a way to share your workload.

**Comment by badgerwithagun** [comment]
Sure! Just submit pull requests to the kucoin-2.0 branch on my fork. I can merge them into the ongoing work.

**Comment by badgerwithagun** [comment]
If you did placelimitorder, placestoporder and/or placecancelorder that would speed things up greatly.

**Comment by badgerwithagun** [comment]
Kucoin have just put live a change that has broken their own SDK.
```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "datetime" (class com.kucoin.sdk.rest.response.SymbolTickResponse), not marked as ignorable (9 known properties: "changeRate", "high", "vol", "low", "symbol", "changePrice", "open", "volValue", "close"]) 
```
I know the fix, just can't do anything about it at work.  Will sort out later.

**Comment by anhtuantt** [comment]
Yes, let me work with these APIs: placelimitorder, placestoporder and/or placecancelorder.

**Comment by badgerwithagun** [comment]
I should warn you: it looks like Kucoin are making lots of undocumented changes to the API at the moment. Behaviour of Live is totally different to Sandbox and new fields are appearing in the Live data every hour.  It keeps breaking the "official" SDK (which I've now forked in a vain attempt to keep it working).

The SDK code quality is not great either; I keep finding new bugs.  If you find issues with that, submit PRs to the fork: https://github.com/gruelbox/kucoin-java-sdk

**Comment by badgerwithagun** [comment]
getAccountInfo now available on the branch.

**Comment by szd116** [comment]
Thank you for the great effort @badgerwithagun  and @anhtuantt.

**Comment by badgerwithagun** [comment]
getOpenOrders now added.

**Comment by badgerwithagun** [comment]
getTradeHistory added.

@anhtuantt, are you getting anywhere? Otherwise I'll finish up tomorrow with those last three methods.

**Comment by badgerwithagun** [comment]
ok @anhtuantt, I'm going to implement those now.

**Comment by badgerwithagun** [comment]
All done, everyone. The code on the branch is now working for all those use-cases. Unfortunately it needs refactoring to remove the SDK dependency (see comments on #2946).

It's up to @timmolter as to whether it will be merged into `develop` before then, or the merge can happen and the refactor later.

Would anyone be willing to pick up from here port the SDK code into XChange?  If not, I will, but it may take me a while to get around to it.

My thinking is that:

- All the JSON-mapped DTOs like `OrderCreateApiRequest` can just be copied into XChange unmodified. They use Lombok, but I think I've seen Lombok in use in a few places in XChange already.
- The interfaces which are proxied to REST API calls (like `AccountAPI`) can be copied again, just with some slightly different annotations
- Only the interface implementations need to be changed, to use `RestProxyFactory` instead of retrofit.

Simple, just a little laborious.

**Comment by timmolter** [comment]
Yeah, Lombok is now in XChange.
