### ISSUE TITLE
[cryptofacilities] implementation

### ISSUE THREAD

**Issue by andre77** [knowm/XChange#2926]
Just a question regarding the general cryptofacilities implementation

https://github.com/knowm/XChange/blob/71b96352c49ae82016e08ee8de18a818832ee980/xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/CryptoFacilitiesAuthenticated.java#L33

All the methods are implemented es GET methods, but the API expects  POST requests there
see https://www.cryptofacilities.com/resources/hc/en-us/articles/360000546054-Send-Order
@Panchen 
did the provided code ever work ? anybody using it?

**Comment by nielsdraaisma** [comment]
Since the API is only using query parameters they might not even check the request method, in which case it might work ?, should probably still be fixed though, just in case they change their mind.

**Comment by Panchen** [comment]
@andre77  
did the provided code ever work?  
Yes.

anybody using it? 
All endpoints work for me.

NB CF strangely changed their api in the release on 1st August 18 from POST to GET requests for authenticated calls as per note from support:

"These endpoints only accept GET requests, POST requests are not valid. During the release on Wednesday we tidied up the v3 API.
Please ensure that the requests you are making are GET requests."

@nielsdraaisma 
You are correct. Send / cancel orders do accept both methods. I have upgraded to POST. Others only accept GET.

**Comment by andre77** [comment]
@Panchen 
thanks 👍
