### ISSUE TITLE
Java 8 EOL end of 2019

### ISSUE THREAD

**Issue by timmolter** [knowm/XChange#2945]
Let's plan on cutting off Java 8 support early 2020. It should be an easy transition. I've been using Java11 now for a while.

**Comment by badgerwithagun** [comment]
Seems sensible. My litmus test for this for my own apps is when the top link on Google to download Java doesn't give you Java 8:

https://www.java.com/en/download/

And you don't have to install a plugin in major IDEs to support it:

https://marketplace.eclipse.org/content/java-11-support-eclipse-2018-09-49

In the meantime, everyone should have CI set up to make sure it works, so the switch to using language features can happen at any time.

**Comment by cymp** [comment]
Java 11 now has an [HTTP Client library](https://openjdk.java.net/groups/net/httpclient/intro.html), do you think it means we can get rid of the rescu library? Not that I don't like it, but it would spare a dependency.

**Comment by timmolter** [comment]
It would be a painful transition I believe, as rescu has built a lot of features for XChange as XChange grew. Without knowing the advantages and if it would even work, I'm happy with keeping rescu.

**Comment by walec51** [comment]
rescu is a more abstract client proxy framework which currently uses the old Java HttpURLConnection

it would make more sense to add optional support for the new HTTP client API in rescu

BTW. despite the fact that Oracle announced EOF for Java 8, is Java 11 and its new HTTP client gona get any support on Android?

**Comment by cymp** [comment]
No idea.
Thanks for your answers though.

**Comment by EricAnderson1000** [comment]
Project builds and runs tests in Java 11 just fine. Any reason not to change the target compilation to 11 soon? Who changes the CI builds? 

Tested using 
java --version
openjdk 11.0.5 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20191016_371 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 2a7af5674b based on jdk-11.0.5+10)

**Comment by walec51** [comment]
because a lot of people are running this library on java 8 and android

**Comment by earce** [comment]
Does it make sense to consider this for 5.0.0 given it's a major release + the inclusion of xchange-streaming exchange library?

**Comment by walec51** [comment]
does Java 11 run on Android?

**Comment by earce** [comment]
Does not seem like it, (I am not personally an android developer) but it seems like much of the reason being that Google wanted to accelerate Kotlin development so it may be a while before we see android adopt java 11 IF they do :/

**Comment by walec51** [comment]
Java 8 is barely supported on Android: https://issuetracker.google.com/issues/114481425

Java 11 is simply not

until this changes, xchange has to compile on Java 8

**Comment by timmolter** [comment]
It seems like it may be supported: <https://medium.com/@jack_martynov/adopt-android-build-on-the-jdk11-macos-cc8f05995341>. Just like upgrading normal Java apps to from Java8 to Java 11, there are a few bumps in the road that the developer has to deal with. If anyone using XChange for Android has real-world experience with this please let us know.

I think I'll remove Java8 for the 5.0.0 release and do a rollback if people run into impossible roadblocks getting it working with Android.

**Comment by badgerwithagun** [comment]
Hm, from that post:

> Finally, Android Studio doesn’t support JDK9+. If you try to change JAVA_HOME for the project in Android Studio to JDK9+ then you will get the error: **Path is not valid JDK8 home**

**Comment by timmolter** [comment]
Please report issues here and we can revert as a last resort.

**Comment by walec51** [comment]
the fact that Android Studio runs on Java 11 does not mean that you can use Java 11 language features on Android JVM.

Android Studio is an IDE. not the target runtime.

I personal do not use this library on Android but once we stop testing it on Java 8 it will become unusable on Android as even all the features of Java 8 are not supported: https://developer.android.com/studio/write/java8-support

**Comment by cymp** [comment]
Wait, can we commit Java 11 code or not ?

**Comment by timmolter** [comment]
Good question. Since I'm not sure given the fact that I'm not an Android developer, I think I'll restrict it back to Java 8. If we open it up to Java 11 source cade and later find out it's not Android compatible, then we have a big problem.

**Comment by timmolter** [comment]
From my research it sorta looks like Android apps can be compiled with Java 11 dependencies, but I really don't know for sure nor can I test it myself.
