### ISSUE TITLE
Adding @JsonProperty to all POJO fields

### ISSUE THREAD

**Issue by makarid** [knowm/XChange#2954]
Hello everyone, because i am interested to convert from POJO to json and reverse, in order to save the json to a database,i would like to ask you if any of you, finds a good idea to include a @JsonProperty annotation to every field on the main POJOs of the project (Orderbook,LimitOrder,UserTrades etc). I am looking forward for your answers and suggestions.Thank you

**Comment by walec51** [comment]
you can serialize to JSON right now without adding @JsonProperty to any field so I don't see how that would help

only deserialization will have a problem with the fact that we use the builder pattern so if you want to do something in this area then making the builder (not the value object like CurrencyPair or Trade it self) usable by Jackson is the way to go

**Comment by makarid** [comment]
Hello @walec51 . You are right, the serialization is not a problem the JSON to POJO is. I  small Google search about deserialize builder pattern brought me this annotation (@JsonDeserialize(builder=ValueBuilder.class). Are you referring to something like this? Thanks for your answer.

**Comment by walec51** [comment]
yep, integration the builder with Jackson is the way to go
