### ISSUE TITLE
How to check if a limit order is filled on Binance

### ISSUE THREAD

**Issue by andrewlin0410** [knowm/XChange#2962]
An example or some short code would help. Thanks

**Comment by badgerwithagun** [comment]
Some more context would be useful. For example, is it because you want to deal with errors and retry without risking submitting a trade twice?

There are several different solutions depending on what you're trying to do.

**Comment by badgerwithagun** [comment]
Do you mean: how to check if a specific order has been filled?  That is "I submitted an order, and `getOpenOrders` doesn't return it anymore, so was it filled or cancelled"?

**Comment by andrewlin0410** [comment]
> Do you mean: how to check if a specific order has been filled?  That is "I submitted an order, and getOpenOrders doesn't return it anymore, so was it filled or cancelled"?
Hi you are right. I realized I can check through getOpenOrders and see if it still exists but is there an easier way? Thank you

**Comment by badgerwithagun** [comment]
I would combine it with `getTradeHistory`. That will give you the `orderId` of any trades, so if you have trade(s) against the order and the order doesn't exist, then it was definitely filled. If you have no trades and the order doesn't exist, then it was almost certainly cancelled.

There are faster/cleaner ways in terms of interaction with the Binance API (e.g. using [xchange-stream](https://github.com/bitrich-info/xchange-stream) to monitor the execution reports via the websocket, which is what Binance themselves advise) but this is definitely not _easier_.
