### ISSUE TITLE
[simulated] Create simulated/dummy/mock exchange

### ISSUE THREAD

**Issue by badgerwithagun** [knowm/XChange#2964]
I have a lot of code built up around XChange (and xchange-stream) which needs end-to-end testing.

To facilitate this, I am in the progress of creating a "native" in-process exchange implementation, `xchange-simulated`, which implements all the main XChange interfaces but using a simple, low performance but thread-safe in-process "exchange".  This has its own L3 orderbook for each coin, a matching engine, and allows multiple `Exchange` instances with different api-keys in their `ExchangeSpecification` to trade against each other.

It will support:

* All market data (ticker, order book, trades)
* Trading (limit order and market order only for now, no stops, but that could easily be added)
* Trade history
* Open orders
* Account balances

I will eventually extend it with an equivalent xchange-stream implementation.

In all cases, I am intending to ensure that it throws the correct core exchange exceptions (e.g. `FundsExceededException`) at the right times, but will also _randomly_ throw exceptions that a designer should expect to handle gracefully, such as `NonceException`, `SocketTimeoutException` or `RateLimitExceededException`.  The intention is to flush out reliability issues in developer code and encourage adherence to xchange-core standards.

Should be ready soon.

**Comment by timmolter** [comment]
Sounds good! There are some old issues floating around about this exact sort of thing.
