### ISSUE TITLE
Dependabot

### ISSUE THREAD

**Issue by badgerwithagun** [knowm/XChange#2970]
I use this on projects, and it has revolutionised staying on top of new dependency versions:

https://github.com/dependabot

Example of the pulls it raises: https://github.com/gruelbox/orko/pull/276

It's free. Can it be enabled here?

**Comment by timmolter** [comment]
yeah, looks awesome. I always have done it manually, which is very time consuming.

**Comment by badgerwithagun** [comment]
Be prepared for an onslaught when it's turned on, but it's very cathartic.

**Comment by walec51** [comment]
done
