### ISSUE TITLE
Exception in thread "main" org.knowm.xchange.independentreserve.dto.IndependentReserveHttpStatusException: Invalid credentials (bad signature) (HTTP status code: 400)

### ISSUE THREAD

**Issue by songproducer** [knowm/XChange#2998]
I'm new to Java and Xchange and I'm not sure how to run the Independent Reserve example over ssl. I'm just trying to get a feel for how to use so I can do auto-buys eventually.

I tried to follow the Getting Started with XChange for Noobies guide but I'm a bit stuck with this error:

> Exception in thread "main" org.knowm.xchange.independentreserve.dto.IndependentReserveHttpStatusException: Invalid credentials (bad signature) (HTTP status code: 400)

Should l also do this:
https://github.com/knowm/XChange/wiki/Installing-SSL-Certificates-into-TrustStore
but Run:
java InstallCert independentreserve.com

I don't have an application of my own yet just working within Eclipse.

**Comment by walec51** [comment]
the exception you are getting has nothing to do with SSL certificates, you must provide an API key from the exchange
