### ISSUE TITLE
[NEW EXCHANGE]  Derebit

### ISSUE THREAD

**Issue by dinozof** [knowm/XChange#3008]
Hi everybody,

I saw that Derebit is not supported yet. I think it would be nice to implement this new exchange since it's gaining some popularity 
https://www.deribit.com/

Cheers!

**Comment by jakubkalicki** [comment]
I will start working on this in upcoming days.

**Comment by jakubkalicki** [comment]
Basic market data requests are implemented now.

**Comment by earce** [comment]
This was implemented
