### ISSUE TITLE
Poloniex disabling TLS 1.0-1.1

### ISSUE THREAD

**Issue by cymp** [knowm/XChange#3027]
Hello,

Just received this from poloniex:
« Dear Poloniex Customer:
As part of our effort to provide you with the most secure experience, Poloniex is going to require the use of TLS 1.2 or greater. On April 15, 2019 we will disable support for TLS 1.0 and 1.1 as well as all versions of SSL for all our services, including our website and API.« 

Would that require some fix regarding XChange?

**Comment by walec51** [comment]
I download public data without any interruption so I thinks this was not a problem
