### ISSUE TITLE
Initial compilation error at XChange Core

### ISSUE THREAD

**Issue by zach-bell** [knowm/XChange#3090]
Hi,
I'm really new to Maven, and I want to use XChange to compare the selling and buying costs between different exchanges and make buying and selling decisions happen from a static account.

I am having a bit of trouble though when compiling, I am using jdk 1.8 in eclipse and doing a maven install and getting this output error on the console. Link here: https://pastebin.com/cSjDN3Jq

I've done multiple clean runs, I've used the master and dev branch from github. I'm not too sure what I'm doing wrong, but i've been stuck on this for a bit now.

**Comment by timmolter** [comment]
you don't need to build xchange from source to use XChange in your own project. Just add a reference to XChange in your project's POM. See the README.

**Comment by zach-bell** [comment]
When I run the maven install with only the dependencies in the pom I keep running into No Class Def Errors even though the exchange I'm testing with was included in the dependency (the exact code exampled in the readme).
This is the output I am getting from the console: https://pastebin.com/pQ6RyBQU
This is what my pom looks like: https://pastebin.com/vTPzBpat

**Comment by timmolter** [comment]
ok, thanks. I'm not sure what's going on. I'd look in your local repository for `com/fasterxml/jackson/databind` and see if it's actually there. Sometimes Maven gets messed up. You could google the problem in general.

**Comment by zach-bell** [comment]
Ok, sorry guess i was being dumb for a bit. Bitstamp is also timing out for me but that's a different issue, thank you for at least taking the time to respond to my menial issue.
