### ISSUE TITLE
Bitmex NPE in placeOrder() when getting rate limit responses

### ISSUE THREAD

**Issue by MeLoco1** [knowm/XChange#3095]
```
        Exchange bitmex = ExchangeFactory.INSTANCE.createExchange(BitmexExchange.class.getName());
        ExchangeSpecification bitmexSpec = bitmex.getDefaultExchangeSpecification();
        bitmexSpec.setHost("testnet.bitmex.com");
        bitmexSpec.setApiKey("...");
        bitmexSpec.setSecretKey("...");

        bitmex.applySpecification(bitmexSpec);

        System.out.println(bitmexSpec.getHost());
        result = bitmex.getTradeService().placeMarketOrder(new MarketOrder(Order.OrderType.ASK, new BigDecimal("100"), CurrencyPair.XBT_USD));
```

I tried for both limit and market orders

**Comment by AntonTutuka** [comment]
```
java.lang.NullPointerException
	at org.knowm.xchange.bitmex.service.BitmexBaseService.updateRateLimit(BitmexBaseService.java:104)
	at org.knowm.xchange.bitmex.service.BitmexTradeServiceRaw.placeOrder(BitmexTradeServiceRaw.java:104)
	at org.knowm.xchange.bitmex.service.BitmexTradeService.placeLimitOrder(BitmexTradeService.java:95)
```

**Comment by Denebulas** [comment]
I have the same problem and it happens on connection.
Is there a workaround ?
Or an old version is working?

**Comment by Denebulas** [comment]
It's easy to fix:
line 98 in BitmexBaseService
`catch (Exception e){
            throw handleError(e);
        }finally{
            if(responseAware != null && !rateLimitsUpdated){
                Map<String, List<String>> responseHeaders = responseAware.getResponseHeaders();
                List<String> hd = responseHeaders.get("X-RateLimit-Limit");
                if(hd != null)
                    rateLimit = Integer.valueOf(hd.get(0));
                hd = responseHeaders.get("X-RateLimit-Remaining");
                if(hd != null)
                    rateLimitRemaining = Integer.valueOf(hd.get(0));
                hd = responseHeaders.get("X-RateLimit-Reset");
                if(hd != null)
                    rateLimitReset = Long.valueOf(hd.get(0));
                rateLimitsUpdated = true;
            }
            if(rateLimitsUpdated){
                RateLimitUpdateListener rateLimitUpdateListener = exchange.getRateLimitUpdateListener();
                if(rateLimitUpdateListener != null){
                    rateLimitUpdateListener.rateLimitUpdate(rateLimit, rateLimitRemaining, rateLimitReset);
                }
            }
        }`

**Comment by declan94** [comment]
I've encountered the same problem, turns out it's because my account has been disabled by BITMEX.

The response is 
`403 Your account has been disabled from using the API. Please contact support`
