### ISSUE TITLE
OkCoin switching to API V3

### ISSUE THREAD

**Issue by dinozof** [knowm/XChange#3105]
Just wanted to report that OkCoin is currently showing API V1 as "OLD" and their website reports this information:

> Our platform supports the concurrent use of new (v3) and old (v1) API currently. However, v1 will be soon disabled. To ensure a smooth trading experience, please upgrade to v3 as soon as possible.

We should consider upgrading V1 API to V3.

Cheers

**Comment by declan94** [comment]
Same as #2841 

And I've been working on it here: https://github.com/declan94/XChange/tree/okex-v3

**Comment by douggie** [comment]
Hi declan94, any thoughts on when you might raise a PR?
