### ISSUE TITLE
Binance Exchange Example

### ISSUE THREAD

**Issue by sf202020sf** [knowm/XChange#3161]
I am trying the following code:

` ExchangeSpecification  exSpec = new BinanceExchange().getDefaultExchangeSpecification();
        exSpec.setUserName("34387");
        exSpec.setApiKey("a4SDmpl9s6xWJS5fkKRT6yn41vXuY0AM");
        exSpec.setSecretKey("sisJixU6Xd0d1yr6w02EHCb9UwYzTNuj");
        Exchange exchange2 = ExchangeFactory.INSTANCE.createExchange(exSpec);`

But I am getting this error:

` Exception in thread "main" java.lang.NoSuchMethodError: org.knowm.xchange.dto.meta.CurrencyPairMetaData.<init>(Ljava/math/BigDecimal;Ljava/math/BigDecimal;Ljava/math/BigDecimal;Ljava/lang/Integer;Ljava/lang/Integer;[Lorg/knowm/xchange/dto/meta/FeeTier;Ljava/math/BigDecimal;Lorg/knowm/xchange/currency/Currency;)V
	at org.knowm.xchange.binance.BinanceExchange.remoteInit(BinanceExchange.java:118)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:115)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:128)
`

What I am doing wrong?

**Comment by walec51** [comment]
how your project have the same latest version of xchange-core and xchange-binance in its dependencies?

**Comment by walec51** [comment]
closing because of no response from the author
