### ISSUE TITLE
Kraken does not support the currency code [XDAO]

### ISSUE THREAD

**Issue by alinbreaban** [knowm/XChange#3165]
When an account has a balance in an asset that Kraken does not support anymore in the API assets, then we get into this issue: Kraken does not support the currency code **[asset]**

Did anyone else get this error until now?

Could someone that already contributed help with fixing this?
I think KrakenAdapters.adaptWallet(...) could be a good place to treat the exception thrown by KrakenUtils.translateKrakenCurrencyCode(...). This should solve the problem and not impact other flows.

Thoughts? 

`2019/08/08 01:17:27.381 [main] DEBUG Executing POST request at https://api.kraken.com/0/private/Balance
2019/08/08 01:17:28.480 [main] DEBUG Request http status = 200
2019/08/08 01:17:28.482 [main] DEBUG Kraken does not support the currency code XDAO`

**Comment by makarid** [comment]
Why you want to trade a currency that doesn't support the Kraken?

**Comment by alinbreaban** [comment]
You don't have to trade it, but the wallet implementation of Kraken exchange was throwing an exception if you had a balance in a currency which was not supported for trading anymore.

Fixed it here: https://github.com/knowm/XChange/pull/3167
