### ISSUE TITLE
HuobiAdapters 缺少 askSize 和 bidSize

### ISSUE THREAD

**Issue by hlevel** [knowm/XChange#3169]
**Before revision :**
`  public static Ticker adaptTicker(HuobiTicker huobiTicker, CurrencyPair currencyPair) {
    Ticker.Builder builder = new Ticker.Builder();
    builder.open(huobiTicker.getOpen());
    builder.ask(huobiTicker.getAsk().getPrice());
    builder.bid(huobiTicker.getBid().getPrice());
    builder.last(huobiTicker.getClose());
    builder.high(huobiTicker.getHigh());
    builder.low(huobiTicker.getLow());
    builder.volume(huobiTicker.getVol());
    builder.timestamp(huobiTicker.getTs());
    builder.currencyPair(currencyPair);
    return builder.build();
  }`

**update :**

 builder.ask(huobiTicker.getAsk().getPrice());
 builder.askSize(huobiTicker.getAsk().getAmount()); //Why is it private?
 builder.bid(huobiTicker.getBid().getPrice());
 builder.bidSize(huobiTicker.getBid().getAmount());  //Why is it private?

**Comment by timmolter** [comment]
There's a getter method for it in Ticker: ` public BigDecimal getAskSize() {
    return askSize;
  }`.

**Comment by hlevel** [comment]
Huobi Ticker [currencyPair=XRP/USDT, open=0.3011, last=0.2975, bid=0.2974, ask=0.2975, high=0.3028, low=0.2924,avg=null, volume=10970086.222083956, quoteVolume=null, timestamp=1565515730032, bidSize=null, askSize=null]

Binance Ticker [currencyPair=XRP/USDT, open=0.30090000, last=0.29782000, bid=0.29770000, ask=0.29782000, high=0.30295000, low=0.29237000,avg=0.29781771, volume=48985118.20000000, quoteVolume=14588635.80295300, timestamp=null, bidSize=934.80000000, askSize=43.90000000]

Author Hello, Huobi bidSize and askSize are empty. Looking at the source code, we found that HuobiAdapters are not set.

Code:

`ExchangeSpecification exSpec = new HuobiExchange().getDefaultExchangeSpecification();
Exchange exchange = ExchangeFactory.INSTANCE.createExchange(exSpec);
CurrencyPair currencyPair = new CurrencyPair(Currency.XRP, Currency.USDT);
MarketDataService marketDataService = exchange.getMarketDataService();
Ticker ticker = marketDataService.getTicker(currencyPair);
System.out.println(ticker.toString());
`
