### ISSUE TITLE
[Bitmex] Signature not valid with default sslUri

### ISSUE THREAD

**Issue by sizmestiev** [knowm/XChange#3173]
Issue #3145 fix breaks signature creation with default BitMEX exchange `sslUri`

https://github.com/knowm/XChange/blob/868fd2b4f065e0b4c54d78c04cd84732ef241b43/xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/BitmexExchange.java#L63
https://github.com/knowm/XChange/blob/868fd2b4f065e0b4c54d78c04cd84732ef241b43/xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/BitmexExchange.java#L34

whereas in #3145 `sslUri` defined as
```
bitmexSpec.setSslUri("https://www.bitmex.com");
```

without '/' at the end. 

`payload` with default `sslUri` at https://github.com/knowm/XChange/blob/868fd2b4f065e0b4c54d78c04cd84732ef241b43/xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexDigest.java#L48 is calculated like `GETapi/v1/...` instead of `GET/api/v1/....`

**Comment by sizmestiev** [comment]
@rastooo

**Comment by trixprod** [comment]
Can we revert back @rastooo commit ?

**Comment by timmolter** [comment]
If the `/` is added back it will probably break something else. Can someone carefully check every path and submit a PR?

**Comment by timmolter** [comment]
I took a stab at it. Please test.

**Comment by trixprod** [comment]
Tested on the lastest SNAPSHOT version, the sslUri doesn't contain the last / 

```
        BitmexExchange bitmexExchange = new BitmexExchange();
        final ExchangeSpecification exSpec = bitmexExchange.getDefaultExchangeSpecification();
        exSpec.setApiKey("xxxxxxx");
        exSpec.setSecretKey("xxxxxxx");
        bitmexExchange.applySpecification(exSpec);

        AccountService accountService = bitmexExchange.getAccountService();
        AccountInfo accountInfo = accountService.getAccountInfo();
```

```
Caused by: java.lang.NullPointerException
	at org.knowm.xchange.bitmex.service.BitmexBaseService.updateRateLimit(BitmexBaseService.java:104)
	at org.knowm.xchange.bitmex.service.BitmexAccountServiceRaw.getBitmexAccountInfo(BitmexAccountServiceRaw.java:30)
	at org.knowm.xchange.bitmex.service.BitmexAccountService.getAccountInfo(BitmexAccountService.java:40)


```

**Comment by timmolter** [comment]
Someone with a Bitmex account is going to have to debug this. Ideally the slashes should be left off the URL definitions and they should be added only in places like `digestParams` in `BitmexDigest`. Maybe the issue is there in fact.

**Comment by makarid** [comment]
I have already check that. The only thing that needs to be changed is to
delete the / on the BitmexDigest.

**Comment by trixprod** [comment]
@makarid, are you going to PR ?

**Comment by makarid** [comment]
I am waiting one of my PRs to merge and then i will make the bitmex PR
which has the fix.

**Comment by makarid** [comment]
This issue can be closed
