### ISSUE TITLE
[Bitmex] NPE on updateRateLimit

### ISSUE THREAD

**Issue by trixprod** [knowm/XChange#3178]
This issue still remains 

`java.lang.NullPointerException: null
at org.knowm.xchange.bitmex.service.BitmexBaseService.updateRateLimit(BitmexBaseService.java:104)
at org.knowm.xchange.bitmex.service.BitmexTradeServiceRaw.getBitmexOrders(BitmexTradeServiceRaw.java:65)
at org.knowm.xchange.bitmex.service.BitmexTradeService.getOpenOrders(BitmexTradeService.java:51)
`

Related to #3133 (closed), #2877 (closed), #3095 (open)
In the #3095, @Denebulas provides a solution, can we pull request this ?

Regards

**Comment by sizmestiev** [comment]
NPE on updateRateLimit can be a consequence of invalid signature #3173. I have the same error on authenticated calls with default `sslUri`:

```
Http call returned 401; response body:
{"error":{"message":"Signature not valid.","name":"HTTPError"}}  

java.lang.NullPointerException at  
org.knowm.xchange.bitmex.service.BitmexBaseService.updateRateLimit(BitmexBaseService.java:104) at  
org.knowm.xchange.bitmex.service.BitmexAccountServiceRaw.getBitmexMarginAccountsStatus(BitmexAccountServiceRaw.java:70)
```

**Comment by makarid** [comment]
Hello, i have found and solve the issue. The problem is on the BitmexDigest class. There is one more "/" on the payload which needs to be removed. I will submit a PR shortly.

**Comment by timmolter** [comment]
Related to https://github.com/knowm/XChange/issues/3173
