### ISSUE TITLE
[Poloniex] Call for pair BTC/USD and ETH/USD fails with org.knowm.xchange.exceptions.CurrencyPairNotValidException: Invalid symbol.

### ISSUE THREAD

**Issue by oleksandrkyetov** [knowm/XChange#3181]
When using
https://github.com/knowm/XChange/blob/develop/xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/PoloniexMarketDataServiceRaw.java#L48
https://github.com/knowm/XChange/blob/develop/xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/PoloniexMarketDataServiceRaw.java#L114
calls fail with org.knowm.xchange.exceptions.CurrencyPairNotValidException: Invalid symbol.

Reason for that is that currency pairs BTC/USD and ETH/USD are being resolved to USD_BTC and USD_ETH symbols respectively, but should resolve to USDC_BTC and USDC_ETH

**Comment by walec51** [comment]
No it should not
USD is plain old vanilla fiat USA Dollar which Poloniex does not support directly on the exchange
USDC is a ERC20 token representing a stable coin tied to USD by Circle and Coinbase

**Comment by oleksandrkyetov** [comment]
Thank you @walec51 , that make sense, how do I get a price for BTC/USDC or ETH/USDC in this case?
Poloniex REST API contains both USDC_BTC and USDC_ETH in the response https://poloniex.com/public?command=returnTicker
But, there is no USDC in the CurrencyPair class https://github.com/knowm/XChange/blob/develop/xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java

**Comment by cymp** [comment]
You can use a CurrencyPair constructor to build your own pair with strings.
