### ISSUE TITLE
USDC is missing in CurrencyPair class 

### ISSUE THREAD

**Issue by oleksandrkyetov** [knowm/XChange#3182]
Current implementation is missing USDC in CurrencyPair class, so there is no easy way to get ticks for BTC/USDC or ETH/USDC currency pairs

https://github.com/knowm/XChange/blob/develop/xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java

**Comment by walec51** [comment]
There is:

`new CurrencyPair("BTC", "USDC")`

If we put all possible currency pairs as statics in `CurrencyPair` then it will have thousands lines of code. Only the most popular ones should go there. USDC is still quite new.

**Comment by timmolter** [comment]
Feel free to add it to `CurrencyPair` if you want to submit a PR.
