### ISSUE TITLE
[Feature] Adding minor support for margin trading on Wallet.class

### ISSUE THREAD

**Issue by makarid** [knowm/XChange#3202]
Hello, i would like to add 3 optional fields in the Wallet class in order to have at least some support for margin trading. 
The fields can be: 
1) boolean isMarginSupported
2) long maxLeverage
3) double currentLeverage.

What do you think about that? Thanks

**Comment by makarid** [comment]
@timmolter @walec51 what do you think?

**Comment by walec51** [comment]
why would those attributes be assigned to a wallet?
you want add information about "margin trading" or "margin lending"?

**Comment by makarid** [comment]
Thanks for the response @walec51 .Yes i would like the library to have support for at least some basic margin trading functionality

**Comment by walec51** [comment]
you did not answer my questions

**Comment by makarid** [comment]
Sorry, about margin trading

**Comment by makarid** [comment]
I believe this feature is very small and will not break anything. It is a quick fix until we can fully support margin trading.

**Comment by walec51** [comment]
ok, is it like that on most exchanges?
with which ones to you have experience with in margin trading?

PS. Small features added to the core API become unrefactorable without braking backwards  compatibility really fast. Because of this we have to think them through.

**Comment by walec51** [comment]
on exchanges that support multiple wallets can you have one wallet with margin trading and one without it?

isn't the maxLeverage global for the entire exchange?

**Comment by makarid** [comment]
At least the following exchanges offer margin trading: Bitfinex,Bitmex,Kraken,Kraken futures(crypto facilities),liquid. Maybe there are more which i don't know or use them. 
About your backward compatibility issue maybe then it would be better to create a new class for example MarginWallet which extends Wallet and add all the margin features there.

**Comment by makarid** [comment]
> on exchanges that support multiple wallets can you have one wallet with margin trading and one without it?
> 
> isn't the maxLeverage global for the entire exchange?

Yes we can have 2 wallets. The maxLeverage is global for the entire exchange. If we go with this approach we need to create 2 constant variables(or an enum) for the Wallet.name attribute in order to have specific names (for example "spot","margin"), so we can distinct which one is.

**Comment by walec51** [comment]
I'm not asking which exchanges offer margin trading. I'm asking on which of them did you margin trading your self and learned how it works there.

Adding MarginWallet to xchange-core is still extending the API.

We already have accountInfo.getWallet(String id). Unfortunately this id is exchange specific as some exchanges like Bitfinex wale separate wallets for holding, trading and lending (remember that margin trading != margin lending).

Furthermore tell me how a wallet.currentLeverage attribute would correspond to the fact that on some exchanges you can set a different leverage for each order?

**Comment by makarid** [comment]
> I'm not asking which exchanges offer margin trading. I'm asking on which of them did you do margin trading your self and learned how it works there.
> 
> Adding MarginWallet to xchange-core is still extending the API.
> 
> We already have accountInfo.getWallet(String id). Unfortunately this id is exchange specific as some exchanges like Bitfinex have separate wallets for holding, trading and lending (remember that margin trading != margin lending).
> 
> Furthermore tell me how a wallet.currentLeverage attribute would correspond to the fact that on some exchanges you can set a different leverage for each order?

I have margin trade on all the above exchanges. 
The main problem with accountInfo.getWallet(String id) is that there isn't any standard for this id in order to be for any use. It would be much more efficient to know that if i write accountInfo.getWallet(Enum.SPOT) i would always get the spot wallet to trade with.(i am always talking about margin trading)

wallet.currencyLeverage = the real-time leverage that the wallet is using right now based on the open positions of the wallet-account.

**Comment by makarid** [comment]
With these 3 informations you can safely margin trade in order to not getting margin call or any other catastrophic event which right now it is not supported.

**Comment by walec51** [comment]
ok, taking all into consideration I think that:

1) We should leave the get wallet by id mechanism is case we come across a exchange that can allow you to have more then one margin trading wallet.

2) We should add a WalletFeature enum like so: 

```
public class Wallet {

  public enum WalletFeature {
    /** The wallet has the ability to deposit external funds and withdraw funds allocated on it */
    FUNDING,
    /** You can trade funds allocated to this wallet */
    TRADING,
    /** You can do margin trading with funds allocated to this wallet */
    MARGIN_TRADING,
    /** You can fund other margin traders with funds allocated to this wallet to earn an interest */
    MARGIN_FUNDING
  }

  // ...
  
  public Set<WalletFeature> getFeatures() {
    // ...
  }
}
```

3) To AccountInfo we should add the following method:

```
public class AccountInfo {
  // ...
  
  //**
    * Get wallet with given feature
    *
    * @return null if no wallet on given exchange supports this feature
    * @throws UnsupportedOperationException if there are more then one wallets supporting the given feature
  public Wallet getWallet(WalletFeature feature) {
    // scan wallets map values for proper wallet
  }
}
```

4) maxMarginLeverage and currentMarginLeverage can be added do the wallet class as properties but currentMarginLeverage  should be BigDecimal not double. As for maxMarginLeverage I also think it should be BigDecimal to support the case of fractional leverages like x1.5 is some exchange adds support for them.

@timmolter what do you think about these changes?

**Comment by makarid** [comment]
OK, one question, a wallet will have only one feature right?

**Comment by walec51** [comment]
no, it can have many

**Comment by makarid** [comment]
> no, it can have many

**Comment by makarid** [comment]
> no, it can have many, most exchanges have one wallet with FUNDING and TRADING feature
> 
> HitBTC for example has one wallet for FUNDING and one for TRADING
> 
> Bitfinex has a one wallet for FUNDING+TRADING and another for MARGIN_TRADING and another for MARGIN_FUNDING

Isn't funding and trading the same thing? Why will i deposit to a wallet if the only thing i can do is deposit and withdraw?

**Comment by walec51** [comment]
> Isn't funding and trading the same thing?

no, funding and trading are not the same things

> Why will i deposit to a wallet if the only thing i can do is deposit and withdraw?

On HitBTC and a few other exchanges you have one wallet to which you can deposit / withdraw but to trade them you have to move part of the funds you wish to another wallet - this is done internally within the exchange.

> lso, what the method will return if there are 2 wallets on the same exchange that both offer Trading?

read the pseudo-code carefully, the answer is there

```
* @throws UnsupportedOperationException if there are more then one wallets supporting the given feature
```

**Comment by makarid** [comment]
Maybe it would be better the WalletFeature to be the product that this wallet offers. For example, with this wallet you can buy/sell on spot, so WalletFeature.SPOT, with this wallet you can buy/sell on margin so WalletFeature.MARGIN. That way only one WalletFeature will exists on any wallet and we do not need to throw an exception.

**Comment by walec51** [comment]
One wallet can have many features, there is no point of hacking around this. It is also good to know if you can deposit / withdraw to a wallet. You point of view ignores this feature.

**Comment by makarid** [comment]
> > 
> On HitBTC and a few other exchanges you have one wallet to which you can deposit / withdraw but to trade them you have to move part of the funds you wish to another wallet - this is done internally within the exchange.
> 
>>

Can i transfer the funds from one to the other using their API? If not then the FUNDING wallet is not useful, it is just confusing.

Anyway i don't mind the wallet to have many features,i just believe that it just adds complexity for no reason and this makes the library harder to learn for the newcomers.

**Comment by makarid** [comment]
When @timmolter sees that and agrees with the implementation i will start working on it and make a PR with the solution that you suggested.

**Comment by walec51** [comment]
I gave you the reasons for this in my previous comments. The fact that your not interested in having info which wallet supports deposits / withdraws and which also supports margin funding (this is something else then margin trading) does not invalidate those reasons.

Further more there are exchange like Bitmarket which supported margin trading and spot trading on one wallet. If we get another exchange like that then your proposition will make it impossible to implement.

**Comment by makarid** [comment]
OK no problem. Just to clarify. Let's say that i am going implement Kraken exchange with the new WalletFeature. I will make 2 wallets, one with WalletFeature.TRADING and WalletFeature.FUNDING and an other with WalletFeature.Margin and WalletFeature.Funding. Is that right? In both wallets you can deposit/withdraw, but the first is for spot trading and the other is for margin trading, is that right?

**Comment by walec51** [comment]
Yes in that case youy Kraken account will have two wallets with features:

- TRADING, FUNDING
- MARGIN_TRADING, FUNDING

PS. As I understand from this article: https://support.kraken.com/hc/en-us/articles/202967026-Where-do-funds-for-margin-trading-come-from-
Kraken does not allow users to lend funds to margin traders - they supply the loan their companies found - so no wallet will have the MARGIN_FUNDING feature.

**Comment by makarid** [comment]
Do i need to create a new constructor in order to pass the Set<WalletFeature> or just a setter?

**Comment by makarid** [comment]
I have create the new implementation, when you give me the green light i will make the PR

**Comment by walec51** [comment]
Wallet is a value object, you should not add any setters to it.

**Comment by makarid** [comment]
OK. Do i need to add to every Wallet constructor the new WalletFeature set and update the Wallet creation in every part of the project?
