### ISSUE TITLE
How to get the symbols (not currencypair) of an exchange?

### ISSUE THREAD

**Issue by hivemall** [knowm/XChange#3207]
For binance i can use:
```
BinanceMarketDataService mds = (BinanceMarketDataService) exchanges.get(exchangeNameSelected).getMarketDataService();
mds.getExchangeInfo().getSymbols();


```
but eg kraken does not have that method `getExchangeInfo()`:

```
KrakenMarketDataService mds = (KrakenMarketDataService) exchanges.get(exchangeNameSelected).getMarketDataService();
mds.getExchangeInfo().getSymbols();
```

How to get a list of symbols like in binance?

**Comment by walec51** [comment]
`getExchangeInfo` is a binance specific method
use methods from the `Exchange` interface if you want like `getExchangeSymbols`

**Comment by walec51** [comment]
if you need a `Set<Currrency>` then just build it your self out of `getExchangeSymbols`

**Comment by hivemall** [comment]
i need symbols not currencypairs to do `Filter[] filters = symbol.getFilters();` and get the scale. For binance i have symbols for others i dont. `getExchangeSymbols` returns currencypairs and has no info on the filter. How to to this with non binance?

**Comment by hivemall** [comment]
i switched to https://github.com/ccxt
