### ISSUE TITLE
New FundingRecord.Type for Airdrops, Kickbacks, etc...

### ISSUE THREAD

**Issue by Yampersand** [knowm/XChange#3218]
At the moment FundingRecords can be either a deposit or a withdrawal. Same exchanges have additional mechanisms to change one’s funding history.
For example, Bitcoin.de has Kickbacks which are partly refunded fee for trades made using their API and Poloniex knows Airdrops for “gifted” crytos out of promotion campaigns
While those funds are technically kind of like deposits there are use cases to distinguish them, for example accounting.
Poloniex calls this “adjustments” which I think is a good name. I propose following changes to handle these kinds of funds:

- add an additional Type “ADJUSTMENT” to FundingRecord.Type

- add an additional String field to FundingRecord like “category”, “detail” or “subtype” to have some kind of way to transport the information what kind of adjustment was made

Alternatively there could be an additional method in AccountService to access those records. That would not be my preferred way, because, in my limited experience, exchanges return that data alongside with deposits and withdrawals

I would be willing to supply a pullrequest with the necessary changes, if this is considered a valid change in the API.

**Comment by timmolter** [comment]
would we really need the enum type AND a String?

**Comment by Yampersand** [comment]
No, we don't: If you are fine with adding more types to FundingRecord.Type that is properly the best solution. I allready know of two additional types, "Kickback" and "Airdrop", but there could be more.

If you are saying that's what that enum is for, I'm more than happy to add "Airdrop" for Poloniex and later on "Kickback" for Bitcoin.de, when I find the time to implement, same or all account service feature.

**Comment by walec51** [comment]
adding more types is a very bad idea, it will cause application code to look like this:

```
if (type == DEPOSIT || type == AIRDROP || type = KICKWHATNOT || ...) {
  // add to balance
} else {
  // remove from balance
}
```

I'm in favour of adding a `String subtype` plus maybe some class with commons ones like

```
public final class CommonFundingSubtypes {

  public static final String AIRDROP = "AIRDROP";
  public static final String STAKING = "STAKING";
}
```

**Comment by Yampersand** [comment]
We could circumvent ugly if-blocks by attributing a directing to the Type:

    public enum Type {
      WITHDRAWAL(false),
      DEPOSIT(true),
      KICKBACK(true),
      AIRDOP(true);

      private final boolean incoming;

      Type(final boolean incoming) {
        this.incoming = incoming;
      }

      public boolean isIncoming() {
        return this.incoming;
      }

      public boolean isOutgoing() {
        return !this.incoming;
      }
    }

So your if-Statement would become something like:

    if (type.isIncoming()) {
      // add to balance
    } else {
      // remove from balance
    }


I agree that Kickback, airdrop, etc clearly feel like Deposit-subtypes. I don't have a preference for either solution, I just need that information, preferably without using the Raw-ReturnType.

So, what is the process on deciding which way to go?

**Comment by timmolter** [comment]
@Yampersand Your last proposal is the way to go - much cleaner than Strings.

**Comment by walec51** [comment]
Enum's are for closed sets, Strings are for open sets of values.

In my view this is still a bad design decision. 

The goal of generic interfaces, DTOs and enums in xchange-core is to provide a unified API for common exchange features. KICKBACK is NOT a common feature, it exists only in ONE exchange. If we go this way this enum will get dominated by dozens of types that exist only in one or two exchanges.

**Comment by Yampersand** [comment]
That is a fair point.

@timmolter: If you agree with @walec51 to hesitate to say so. I'm willing to adapt my proposal.
I'm interested in an consitant api design.

**Comment by walec51** [comment]
I've made my case ;) but @timmolter has to make the final decision in which direction this API change will go

**Comment by timmolter** [comment]
Go for the enum. I'd rather have a closed set with established types so that if another exchange offers it, it can be used. It's not hurting anything to be there, and to me actually helps define a generic API. Using Strings reeks of code smell to me. I know it's kind of an arbitrary decision. For example the `Currency` class has lots of members defined where some will only be used in a few exchanges and definitely not in all. On the other hand we've been strongly resistant to adding new one-off members to generic DTOs. I think adding new types to enums if fine as long as it's not like `PoloniexAirdrop` of course.
