### ISSUE TITLE
FTX Exchange implementation

### ISSUE THREAD

**Issue by douggie** [knowm/XChange#3258]
Hi,

Is anyone looking at implementing the rapidly growing ftx exchange ?

https://ftx.com/futures

FTX seems to have quite a lot of unique contract names, to start with I am thinking of supporting their quarterly and semiannual futures as a starting point.

Unlike other exchanges you can only get the poll by the expiry such as https://ftx.com/api/futures/BTC-0327 for the semiannual contract or https://ftx.com/api/futures/BTC-1227 for the quarterly. As such I am wondering if we could use the existing convention of BTC.USD.THIS_QUARTER and BTC.USD.NEXT_QUARTER and have a helper that generates the last Friday of the current quarter and last Friday of next quarter based on the current date i.e from 14/10/2019 the helper would create 27-12-2019 as the last Friday of current quarter and 37-03-2020 for the last Friday of next quarter, which can then be used in the rest request to get the futures trade data via GET https://ftx.com/api/markets/BTC-1227/trades?limit=100 as something like GET https://ftx.com/api/markets/BTC-USD-QUARTER/trades?limit=100 is not supported on ftx's API.

**Comment by makarid** [comment]
+1. Unfortunately i don't have time to implement this exchange.When i will find i will start, but don't bet on it. :)

**Comment by mathvdh** [comment]
This can be closed as an implementation exists now
