### ISSUE TITLE
Build failing on example project

### ISSUE THREAD

**Issue by douggie** [knowm/XChange#3266]
Hi,

Been a while since building exchange but seems that the exchange-example project is failing, any pointers welcomed!

`$ mvn -version
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T16:06:16+01:00)
Maven home: /usr/local/Cellar/maven/3.6.2/libexec`

`$ java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)`
`git checkout c1b34c0644627071c5caa4b181527c5f6b4e9352`
` mvn install -DskipTests `

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project xchange-examples: Compilation failure: Compilation failure: 
[ERROR] /Users/douggieclarke/git/XChange/xchange-examples/src/main/java/org/knowm/xchange/examples/wex/trade/WexTradeDemo.java:[69,13] cannot find symbol
[ERROR]   symbol:   class Type
[ERROR]   location: class org.knowm.xchange.wex.v3.dto.trade.WexOrder
[ERROR] /Users/douggieclarke/git/XChange/xchange-examples/src/main/java/org/knowm/xchange/examples/wex/trade/WexTradeDemo.java:[69,34] non-static variable Type cannot be referenced from a static context
[ERROR] /Users/douggieclarke/git/XChange/xchange-examples/src/main/java/org/knowm/xchange/examples/wex/trade/WexTradeDemo.java:[69,39] cannot access enum
[ERROR]   class file for enum not found
[ERROR] /Users/douggieclarke/git/XChange/xchange-examples/src/main/java/org/knowm/xchange/examples/wex/trade/WexUserTradeHistoryDemo.java:[42,28] cannot find symbol
[ERROR]   symbol:   method getBTCETradeHistory(<nulltype>,<nulltype>,<nulltype>,<nulltype>,<nulltype>,<nulltype>,<nulltype>,<nulltype>)
[ERROR]   location: variable tradeService of type org.knowm.xchange.wex.v3.service.WexTradeServiceRaw
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :xchange-examples

**Comment by timmolter** [comment]
Strange. No idea. Make sure you've updated the `develop` branch locally.

**Comment by douggie** [comment]
No worries I will figure it out thought it might be maven version.

**Comment by douggie** [comment]
odd I run ` mvn package -DskipTests` builds fine
