### ISSUE TITLE
[core]UserTrade missing field "original volume"

### ISSUE THREAD

**Issue by Yampersand** [knowm/XChange#3269]
The UserTrade-Object is missing a field "OriginalVolume" similar to OriginalAmount. It should represent the actual volume of the trade.

At the moment this value has to be calculated using amount and price. That leads to rounding decisions which may differ from how it is handled by the exchange.
Some exchange offer this value via API: Bitcoin.de, Bitstamp, CEX.io (in some cases), Kraken, Poloniex.

An example:
Follow a trade on Bitstamp:
`{
	"usd": "-748.21",
	"btc_usd": 8317.45,
	"order_id": 4178040339,
	"datetime": "2019-10-01 23:15:12",
	"fee": "0.60",
	"btc": "0.08995704",
	"type": "2",
	"id": 98055730,
	"eur": 0.0
}`

resulting in this UserTrade:
`UserTrade[
    type=BID,
    originalAmount=0.08995704,
    currencyPair=BTC/USD,
    price=8317.45,
    timestamp=Wed Oct 02 01:15:12 CEST 2019,
    id=98055730,
    orderId='4178040339',
    feeAmount=0.60,
   feeCurrency='USD'
]`

Calculation the volume of the Trade results in 8317.45 (price) * 0.08995704 (amount) = 748.213182348‬ while the API report 748.21.

Is there a reason not to include this field? If not, I would like to add this.

**Comment by amjad1210** [comment]
@Yampersand This is available in the Order DTO with the method getCumulativeCounterAmount() you could add something similar into UserTrade. The reason this value isn't stored in Order or UserTrade is because it can easily be calculated. As for the rounding issue you can solve this by getting the currency precision from CurrencyPairMetaData e.g.

```
var pairs = exchange.getExchangeMetaData().getCurrencyPairs();
var tradePair = pairs.get(new CurrencyPair("BTC/USD"));
var scale = orderType == OrderType.BID ? tradePair.getCounterScale()  : tradePair.getBaseScale();
```

#3216

**Comment by Yampersand** [comment]
@amjad1210 That is a good hint, thank you for that.  I will see how far that gets me, even if it still feels weird ignoring a provided value just to recalulate it later

**Comment by walec51** [comment]
@Yampersand many exchanges don't provide this value and calculating it is trivial
having code that sometimes calculates it and sometimes does not would be a unnecessary complexity

feel free to reopen this issue if you have a problem with the current approach

**Comment by Yampersand** [comment]
I would like to reopen this issue as I still have a problem with the current approach:
As I discribed in #3447 rounding via information provided by CurrencyPairMetaData is not sufficient as following example of a Binance trade should show:
{"symbol":"ETHBTC","id":15919****,"orderId":59246****,"orderListId":-1,"price":"0.01938500","qty":"0.00700000","quoteQty":"0.00013569","commission":"0.00005069","commissionAsset":"BNB","time":15801309*****,"isBuyer":true,"isMaker":false,"isBestMatch":true}

The "CurrencyPairMetaData" defines the scale to 6 digitis which would result in a volume of 0.007 * 0.019385 = 0.000136 insteadt of "quoteQty = 0.00013569".

That's why I created to pullrequest #3447 as a compromise.

**Comment by walec51** [comment]
you should have let use talk about it first before creating the PR that modifies many exchanges

if you do not want rounding then do not round - I don't understand whats the problem?

this is still easy calculable in the DTOs you receive from this library

**Comment by Yampersand** [comment]
@walec51 Let me try to explain with a little more detail about my use case:
I want to use those values for our accounting, that why I need the exact value that balances changed with each transaction.  Calculating that value and guessing when and how to round isn't exact enough, especially when the exchange provides me with said value.

Using the current DTOs without my addition required me to specify a specific handling for each exchange and currency pair, where as with my solution I only have to know with exchanges provide the additional value.

That said, I didn't introduce something new to this library: The KrakenUserTrade does exactly what I try to do for Binance, Bitstamp und Poloniex.

**Comment by walec51** [comment]
`KrakenUserTrade` is an inconstancy in the library that in my opinion should not be propagated to other parts of the code. If you want to use exchange specific fields then use exchange specific APIs  - *ServiceRaw classes.

That said, we could add `Trade#getAmountInCounter()` which is calculated if it was not set by the adapter.

**Comment by Yampersand** [comment]
> That said, we could add Trade#getAmountInCounter() which is calculated if it was not set by the adapter.

If I understand your correctly that would be the solution I originally proposed? I was under the impression that that isn't desired.

Adding amountInCounter to UserTrade is definitly the better solution from my point of view. I'm willing to make a PR with the necessary changes.

**Comment by walec51** [comment]
well I thought that calculating this was trivial and you didn't say otherwise 

but as our talk went on you pointed out that calculating this can be not trivial

however whats different form your original proposal is to calculate it if adapter does not provide it to the Trade object

ps. the question remains which name is better `getAmountInCounter` or `getOriginalVolume` or just `getVolume`

**Comment by Yampersand** [comment]
The `Trade` already has a field called  `originalAmount`, that why I came up with `originalVolume` as we use the terms amount and volume to describe both sides of a trade in our domain.
But I'm open to other names, if there is one better suited to this domain.

Just to clarify things, how would be the discussed addition look like?

1. `Trade` with following addition:
  ```
protected final BigDecimal originalVolume;

  public BigDecimal getOriginalVolume() {
    if(originalVolume != null) {
      return originalVolume;
    }
    
    return this.originalAmount.multiply(this.price);
  }
```

2.  `Trade` with a regular getter that returns `null` if the value isn't provided as with fields like `makerOrderId ` or `takerOrderId`
3. The adapter calculates the value, so that `Trade` stays a POJO

**Comment by walec51** [comment]
as for (1) and (3) yes

as for (2) I don't know about which getter are you talking about - `getOriginalVolume` is already shown in detail in (1) so I assume (2) is about something else?

**Comment by Yampersand** [comment]
I'm sorry, I tried to outline three different approaches:

1. Handle the originalAmount in `Trade`, so that it always return a value
2. `Trade` only return a value, if the exchange supplies one
3. Trade always returns a value, but that value is calculated by the adapter and Trade doesn't know  whether was supplied by the exchange or the `Adapter`.

**Comment by walec51** [comment]
add this to `Trade`

```
protected final BigDecimal originalVolume;

public BigDecimal getOriginalVolume() {
  if(originalVolume != null) {
    return originalVolume;
  }
  
  return this.originalAmount.multiply(this.price);
}
```

use and `Adapter` to create a `Trade` instance and map values from an exchange native DTO to `Trade`
