### ISSUE TITLE
Passing through ResCU Interceptor's

### ISSUE THREAD

**Issue by Agrajag0** [knowm/XChange#3272]
Sometimes it would be nice to have the opportunity to test the api with real exchange data without the need to connect to the internet or to save the complete request/response data. 

For these use cases the ResCU client offers the so called Interceptor's. At the moment they are ignored when creating the REST Proxy, because they are optional. The question is, how to pass through interceptors if needed?

One solution that come to my mind is to add a method `Interceptor[] getInterceptors()` into the **BaseExchangeService.class**. Here you can read out some exchange specific parameter with the interceptors to pass through. It can then be used in the concrete service classes when creating the Proxy.

`RestProxyFactory.createProxy(restInterface, "some url", getClientConfig(), getInterceptors());
`

One drawback of this approach is, that you have to change a lot of sources and every new service has to use this pattern. Nethertheless i'am willing to make this effort if this approach is acceptable. Any opinions?

**Comment by walec51** [comment]
You can accomplish this by just using wiremock and setting exchangeSpecification.setSslUri to localhost. Its a better test the using interceptors which are meant to decorate requests, not mock them entirely.

**Comment by Agrajag0** [comment]
Well yes, that is an argument. Although it's a more heavier process with an extra server process involved. But okay.

What is with saving of request/response data. How would you accomplish that? Any suggestions appreciated.

**Comment by milczarekIT** [comment]
@Agrajag0, if you are still interested in ResCU Interceptors, I added interceptors support for XChange in https://github.com/knowm/XChange/pull/3745
