### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by pavlo-pastushok** [knowm/XChange#3280]
Hi, guys.

Can you, release the current version of lib, please?

Thanks in Advance!

**Comment by amjad1210** [comment]
Yeh the last release was quite some time ago.

@timmolter any chance we can get a release soon.

**Comment by timmolter** [comment]
Yeah, I'll get on it this weekend. I've been swamped lately, but will have time this weekend. Thanks, @walec51 for handling all the PRs!!!!

**Comment by timmolter** [comment]
done!
