### ISSUE TITLE
MarketDataService OrderBook no unique ID for orders

### ISSUE THREAD

**Issue by mtazov** [knowm/XChange#3302]
Hi! There is no ability to identify OrderBook open orders with ID. They have NULL, empty string or "0" values. I need this id to analyze unique orders. 
Is there any other way to get open orders with ID using XChange?

**Comment by walec51** [comment]
use `TradeService` to get your open orders with ids
as for market data most exchanges deliberately do not give order ids in orders book, most of them don't even give single orders there but aggregate orders with the same price

**Comment by mtazov** [comment]
Hi walec51! I tried TradeService getOpenOrders() for all currency pairs of Binance, but for all pairs of Binance I got:
"Open orders: None
Hidden orders: None"
In TradeService class description: "Retrieve the user's open orders on the exchange". But I need not my user open orders but all exchange open orders with their IDs. 
Does XChange allow to get them?
Thanks in advance!
