### ISSUE TITLE
Bitstamp missing currency_pair property

### ISSUE THREAD

**Issue by matejsp** [knowm/XChange#3303]
When calling:
https://www.bitstamp.net/api/v2/open_orders/all/

BitstampOrder class is missing:
currency_pair (if all currency pairs) | Currency Pair.

https://www.bitstamp.net/api/

**Comment by walec51** [comment]
thanks for reporting
feel free to submit a pull request

**Comment by matejsp** [comment]
PR created: https://github.com/knowm/XChange/pull/3305
