### ISSUE TITLE
Kucoin : username is null

### ISSUE THREAD

**Issue by straumat** [knowm/XChange#3330]
I created a sandbox account on Kucoin. Printing AccountInfo works well but `username` is null as you can see if I print it : 

`AccountInfo [username=null, tradingFee=null, wallets={main=Wallet{balances={BTC=Balance [currency=BTC, total=1, available=1, frozen=0, borrowed=0, loaned=0, withdrawing=0, depositing=0], ETH=Balance [currency=ETH, total=10, available=10, frozen=0, borrowed=0, loaned=0, withdrawing=0, depositing=0], KCS=Balance [currency=KCS, total=1000, available=1000, frozen=0, borrowed=0, loaned=0, withdrawing=0, depositing=0]}, id='main', name='main', walletFeatures=[TRADING, FUNDING], maxLeverage=0, currentLeverage=0}}]`

Tried with `4.4.2-SNAPSHOT`

**Comment by walec51** [comment]
does their API return the users name somewhere?

if yes, then feel free to submit a pull request with a fix
