### ISSUE TITLE
Kraken getKrakenWebsocketToken Permission denied

### ISSUE THREAD

**Issue by maxcww** [knowm/XChange#3363]
Hello, while setting up the KrakenExchange with apikey and secret and trying to get a kraken websocket token via the KrakenAccountService, I get permission denied. I have already tried manually with a rest request with the same api key and secret to get a websocket token and that succeeds, so I do not know what the problem is with this function.

**Comment by mdvx** [comment]
For Kraken, you to also add your username to the exchangeSpecification.
  exSpec.setUserName("abc");

Some exchanges also require a  passphrase (but not kraken)
  exSpec.setExchangeSpecificParametersItem("passphrase", "****");
