### ISSUE TITLE
[Bitmex] Proposal in order to change the feeAmount from USD to BTC

### ISSUE THREAD

**Issue by makarid** [knowm/XChange#3369]
Hello, when someone calls the getTradeHistory().getUserTrades method from Bitmex, the fee amount is displayed with USD values(using the price of the order). Because Bitmex pays only in bitcoin, i would like to propose to change that behavior and send the fee amount in BTC instead of USD.
Are you OK with that proposal in order to start implement it? Thanks

**Comment by timmolter** [comment]
sounds reasonable.

**Comment by makarid** [comment]
I will make the PR then.

**Comment by makarid** [comment]
#3372
