### ISSUE TITLE
[Core] Adding orderReference on UserTrade class

### ISSUE THREAD

**Issue by makarid** [knowm/XChange#3376]
Hello, it would be very helpful to add a field userReference on UserTrade.class in order to identify userTrades that have a specific userReference id. Are you OK to add this field?

**Comment by walec51** [comment]
The way you described this I don't think that it makes sense. An user does not create any trades directly and therefore cannot assign a trades userReference.

However a user can place Orders in which he can assign an orders userReference on some exchanges. If you want to propagate this orders field to user trades that correspond to the given order then you should call that field `orderUserReference` <- if this is what you want then ok

**Comment by makarid** [comment]
I am sorry i didn't describe it correctly, this is exactly what i am talking about. The thing is that i cannot find this orderUserReference field on the UserTrade.class.

**Comment by walec51** [comment]
if you can extract in on exchanges that use `Order#userReference` then yes

**Comment by mdvx** [comment]
userRef is on order, userTrade should have orderId.  That said userRef could be duplicated to userTrade, but you will also have to handle unsolicitated orders (orders created by the exchange, instead of the client - think phone order).

**Comment by walec51** [comment]
`UserTrade#orderId` <=> `Order#orderId` always generated by the exchange
`UserTrade#orderUserReference` <=> `Order#userReference`  they will be both null it the user did not set any userReferencje in the order

**Comment by makarid** [comment]
> `UserTrade#orderId` <=> `Order#orderId` always generated by the exchange
> `UserTrade#orderUserReference` <=> `Order#userReference` they will be both null it the user did not set any userReferencje in the order

Indeed both will be null most of the time. Is it OK to add this optional field to userTrade class?
