### ISSUE TITLE
[binance] get data by  websocket

### ISSUE THREAD

**Issue by TonnTamerlan** [knowm/XChange#3438]
Is there a possibility to get data from Binance by websocket? Or maybe there are other exchanges for which fetching data by websocket is implemented,  that I can, in the same way, to add such functionality  to Binance

**Comment by makarid** [comment]
There is this library: bitrich-info/xchange-stream. Which is about to merge with this branch

**Comment by TonnTamerlan** [comment]
@makarid what do you mean? I did not find bitrich-info library and branch here. Could you please provide a link. Thank you very much in advance

**Comment by makarid** [comment]
Here you are: https://github.com/bitrich-info/xchange-stream
