### ISSUE TITLE
org.knowm.xchange.kucoin  GET /api/v1/fills

### ISSUE THREAD

**Issue by abialy** [knowm/XChange#3497]
Could you please add orderId support for public Pagination<TradeResponse> getKucoinFills in package org.knowm.xchange.kucoin

Something like:

public Pagination<TradeResponse> getKucoinFill(String orderId) throws IOException {
    checkAuthenticated();
    return classifyingExceptions(
        () ->
            fillApi.queryTrades(
                apiKey,
                digest,
                nonceFactory,
                passphrase,
                null,
                orderId,
                null,
                null,
                null,
                null,
                10,
                1));
  }

**Comment by nibarulabs** [comment]
Hello, checking the [FillApi.java](https://github.com/knowm/XChange/blob/develop/xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/service/FillAPI.java) interface and it looks like pagination is supported. @earce or whomever else might want to close this. :+1:
