### ISSUE TITLE
CI stopped working

### ISSUE THREAD

**Issue by walec51** [knowm/XChange#3502]
I've noticed that out CI pipelines stopped working and no tests seam to run for pull request.

@timmolter please check it out when you'll have some time

**Comment by timmolter** [comment]
ok, i'll check it out.

**Comment by timmolter** [comment]
Everything looks fine: <https://travis-ci.org/github/knowm/XChange/builds>

**Comment by walec51** [comment]
ok, I see that it blocks a PR after the CI job finished and failed

however right after you publish a PR until the job finishes broken code look good to merge

screenshot right after creation:

![obraz](https://user-images.githubusercontent.com/738484/80629250-df81d280-8a52-11ea-99bc-a23fd58de877.png)

after w few minutes:

![obraz](https://user-images.githubusercontent.com/738484/80629268-e9a3d100-8a52-11ea-8232-3a1cd9ce9c90.png)

**Comment by timmolter** [comment]
Weird. Too bad it doesn't say "pending CI" or something...
