### ISSUE TITLE
Release 4.4.3?

### ISSUE THREAD

**Issue by catena2w** [knowm/XChange#3512]
Some useful fixes where already merged since last release 2 month ago (e.g. https://github.com/knowm/XChange/issues/3495), while SNAPSHOT version is very instable and now shows error:
```
[error] (run-main-0) java.lang.NoClassDefFoundError: org/knowm/xchange/client/ExchangeRestProxyBuilder
[error] java.lang.NoClassDefFoundError: org/knowm/xchange/client/ExchangeRestProxyBuilder
[error]         at org.knowm.xchange.binance.BinanceExchange.initServices(BinanceExchange.java:36)
[error]         at info.bitrich.xchangestream.binance.BinanceStreamingExchange.initServices(BinanceStreamingExchange.java:43)
[error]         at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:102)
[error]         at info.bitrich.xchangestream.core.StreamingExchangeFactory.createExchange(StreamingExchangeFactory.java:84)
``` 

So I think it might be a good time to make the next small release)

**Comment by walec51** [comment]
as for the error it looks like you didn't do 

`mvn install xchange-core`

after pullin as you are missing a new class from it

**Comment by catena2w** [comment]
It's called from websocket library `https://github.com/bitrich-info/xchange-stream`, I use release 4.4.3-SNAPSHOT from it.

**Comment by walec51** [comment]
well it look like its used the newest build of `xchange-binance` with older code of `xchange-core` on your machine which might be caused by snapshot jar in your local maven repository

run `mvn install xchange-core` on the exchange project on your local machine

**Comment by earce** [comment]
@badgerwithagun @timmolter hey wanted to follow up see when can we expect to cut 5.0.0 given we have started a new month?

**Comment by timmolter** [comment]
@earce Sometime today :)

**Comment by earce** [comment]
Awesome! This is great news!

**Comment by earce** [comment]
I see this isn't available in maven central yet, will it at some point?

**Comment by earce** [comment]
Nevermind I see it now
