### ISSUE TITLE
[kraken] Failing to subscribe to websocket API - Unsupported field error

### ISSUE THREAD

**Issue by wvos** [knowm/XChange#3542]
The Kraken streaming API doesn't work for a number of subscriptions.  Using the below code works perfectly fine for other exchanges but gives a consistent error for Kraken

**Code** 
```
exchange = StreamingExchangeFactory.INSTANCE.createExchange(KrakenStreamingExchange.class.getName());

exchange.connect().blockingAwait();

Disposable sub = exchange.getStreamingMarketDataService()
                .getOrderBook(CurrencyPair.BTC_USD)
                .subscribe(orderBook -> LOG.info("Order book: {}", orderBook));
```
**Error/logs**
01:38:23.437 [main] INFO  info.bitrich.xchangestream.kraken.KrakenStreamingService - Subscribing to channel book-BTC/USD
01:38:23.475 [nioEventLoopGroup-2-1] INFO  info.bitrich.xchangestream.kraken.KrakenStreamingService - System status: KrakenSystemStatus{connectionID='18409444206880552937', event='systemStatus', status='online', version='1.0.1'}
01:38:23.668 [nioEventLoopGroup-2-1] ERROR info.bitrich.xchangestream.kraken.KrakenStreamingService - Channel book-BTC/USD has been failed: _Unsupported field: 'error' for the given msg type: subscribe_

**Comment by badgerwithagun** [comment]
Hmm, looks like the socket's sending an error back from the subscribe request and `KrakenStreamingExchange` doesn't know how to interpret it.  That's hiding the real cause of the error.

**Comment by wvos** [comment]
Indeed, the serialized subscription message has an 'error' field which is not part of the spec, and also a couple of null fields which causes it to fail

**Comment by mdvx** [comment]
The Kraken Spec is unreliable, and you need to look at the Futures API as well as the spot API

**Comment by nielsdraaisma** [comment]
Is this issue still relevant?, the code above seems to match to what's happening in `KrakenManualExample` and that example seems to work fine. 

If this is still happening it would be great if the actual message could be reported back here to it can be added to the testsuite.

**Comment by earce** [comment]
Fix was merged in
