### ISSUE TITLE
[poloniex] heap usage grows over time due to websockets

### ISSUE THREAD

**Issue by RomanHiden** [knowm/XChange#3545]
I have noticed that my service regularly gets killed by OOM. It takes approximately 4 days for my heap usage to double. I made a heap dump just before that.
All 3 leak suspects that I have point to
`io.netty.*` which comes as a dependency from  `xchange-stream` . 

Question: 
Does anybody have similar experience? Possible solutions ?

**Comment by earce** [comment]
Are you running this standalone or inside of something like docker?

**Comment by RomanHiden** [comment]
@earce I am running google f1-micro. yea I know they are really small, but should be more than enough to subscribe for 1 currency/pair

**Comment by RomanHiden** [comment]
so what I have tried is `streamingExchange.disconnect().blockingAwait();` once in an hour. I was wondering maybe this will free up memory allocation. but looks like this call is stuck forever.

**Comment by walec51** [comment]
what are you java max heap settings?

GC usually will not collect anything until it reaches the set max

**Comment by RomanHiden** [comment]
@walec51 
I am using the following to start
```
java -XX:+HeapDumpOnOutOfMemoryError -XX:MaxRAM=400m -Xmx256m -XX:+UseSerialGC -Xss512k -XX:HeapDumpPath=./memory.crash.dump -jar target/trading-0.0.1-SNAPSHOT.jar --spring.profiles.active="$@"
```

**Comment by RomanHiden** [comment]
@walec51 -XX:MaxRAM=400m helped. however I am still seeing some web-sockets disconnecting from time to time. Thanks for help closing ticket
