### ISSUE TITLE
Binance: Add Currency (Question)

### ISSUE THREAD

**Issue by julian-su** [knowm/XChange#3547]
Hi all,

I want trade with altcoins but there are not all are implemented, so how can I add a Currency? I tried using createCurrency method in Currency class but is private

Thanks

**Comment by mdvx** [comment]
Currency.getInstance & Currency.getInstanceNoCreate

**Comment by julian-su** [comment]
getInstance & Currency.getInstanceNoCreate
/** Returns the Currency instance for the given currency code only if one already exists. */

I want to create a new Currency that not exists, for example MATIC

**Comment by mdvx** [comment]
Currency matic = Currency.getInstance("MATIC");  // no obvious, but that will do it

**Comment by julian-su** [comment]
You are right, thank u

**Comment by timmolter** [comment]
You can also add the currencies to XChange via a pull request if you'd like to.
