### ISSUE TITLE
Build error: mt-maven-plugin java 11 (except 8) 

### ISSUE THREAD

**Issue by mdvx** [knowm/XChange#3550]
c:\> git clone git@github.com:knowm/XChange.git xchange2
c:\> cd xchange2
c:\> mvn clean install

[ERROR] Failed to execute goal com.coveo:fmt-maven-plugin:2.10:format (default) on project xchange-parent: Execution default of goal com.coveo:fmt-maven-plugin:2.10:format failed: An API incompatibility was encountered while executing com.coveo:fmt-maven-plugin:2.10:format: java.lang.UnsupportedClassVersionError: com/google/googlejavaformat/java/FormatterException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by mdvx** [comment]
Is it related to this
https://github.com/knowm/XChange/issues/2945

**Comment by timmolter** [comment]
Yeah, you need to use JDK11.

**Comment by mdvx** [comment]
Thank you
