### ISSUE TITLE
[Bitmex] Order type property is misspelled in BitmexPrivateOrder class json annotation

### ISSUE THREAD

**Issue by treerz** [knowm/XChange#3564]
This property is called "_ordType_" in the actual json response, not "_orderType_", therefore it is always null.

https://github.com/knowm/XChange/blob/599a3a9e1e1b934f2398fa9e7d58aa8e8f7568ab/xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/dto/marketdata/BitmexPrivateOrder.java#L70

So the order type is lost when getting the orders via _BitmexTradeServiceRaw.getBitmexOrders()_.

Also the _getOpenOrders_ methods in _BitmexTradeService_ have several issues, as they try to convert the order via _BitmexAdapters::adaptOrder_, which does not even check the type (so it will not notice that is always null), but assumes that it is always a limit order, and does not transfer other important properties used by other order types (e.g. _stopPx_ for stops).

Just using the raw service and the original "raw" _BitmexPrivateOrder_ object without adapting would work fine, were it not for the missing _ordType_, due to the misspell.

**Comment by earce** [comment]
This was corrected
