### ISSUE TITLE
[CoinbasePro]CoinbaseProStreamingTradeService

### ISSUE THREAD

**Issue by mdvx** [knowm/XChange#3589]
Is this working correctly, I thought Coinbase Pro used channel ALL?  and although I have them in my ProductSubscription these exceptions are being triggered.
`
    if (!containsPair(service.getProduct().getOrders(), currencyPair))
      throw new UnsupportedOperationException(
          String.format("The currency pair %s is not subscribed for orders", currencyPair));
`
`
    if (!containsPair(service.getProduct().getUserTrades(), currencyPair))
      throw new UnsupportedOperationException(
          String.format("The currency pair %s is not subscribed for user trades", currencyPair));
`

**Comment by mdvx** [comment]
@badgerwithagun

**Comment by badgerwithagun** [comment]
I'm not an active user of CBP anymore I'm afraid. I know from seeing various PRs going through that Coinbase have changed their API a fair bit recently though.

**Comment by mdvx** [comment]
Thanks for the insight @badgerwithagun

**Comment by earce** [comment]
@mdvx not sure if you're still having issues with this but when you create and set your `ProductSubscription` are you adding the currency pairs for both `trades` and `userTrades` and setting them on the `CoinbaseProStreamingService`?

Coinbase channel says 'ALL' but that's not actually the channel it subscribes to. To see the channels that's in `CoinbaseProProductSubsctiption.generateSubscriptionMessage`.

**Comment by mdvx** [comment]
This got fixed
