### ISSUE TITLE
getCurrencyPairs() differs from exchange response

### ISSUE THREAD

**Issue by straumat** [knowm/XChange#3609]
hello, I'm the developer of [Cassandre trading bot framework](https://trading-bot.cassandre.tech/) and I'm using XChange 5.0.1.

On Kucoin, when calling this method
```
exchange.getExchangeMetaData()
				.getCurrencyPairs()
				.forEach((currencyPair, currencyPairMetaData) -> {System.out.println(">" + currencyPair)});
```

I only get 4 currency pairs : 
```
>KCS/USDT
>ETH/USDT
>BTC/USDT
>ETH/BTC
```

But when I curl Kucoin exchange API with `curl https://api.kucoin.com/api/v1/symbols`, i have more than 15 currency pairs, is it normal ?

**Comment by timmolter** [comment]
You'll have to look at the source code to understand what I'm about to say, but the exchange meta data is either loaded from a config file in `resources` where the pairs (and other meta data) is used to populate that DTO. Some other exchange implementations pull the data from the exchange over various API end points, which probably isn't the case in Kucoin. It would need to be be properly implemented.

**Comment by straumat** [comment]
Thanks @timmolter From what I have seen, it tooks it from the API
[https://github.com/knowm/XChange/blob/develop/xchange-kucoin/src/main/resources/kucoin.json](https://github.com/knowm/XChange/blob/develop/xchange-kucoin/src/main/resources/kucoin.json)

**Comment by straumat** [comment]
Ok, this is not a bug. When you are using sandbox, you don't have all access all currency pairs. When in production, they all appears !
