### ISSUE TITLE
Frequency of websocket disconnects

### ISSUE THREAD

**Issue by earce** [knowm/XChange#3641]
For anyone who connects to CoinbasePro and Kraken via websockets for authenticated trade data as well as public trades data, how often do you see the xchange client disconnect and reconnect to the exchanges?

@badgerwithagun @mdvx

**Comment by mdvx** [comment]
rarely, on both, however I normally use FIX for CoinbasePro user trades

**Comment by earce** [comment]
how often is rarely? I usually see either exchange get disconnected once every few hours, some times 2hrs+ sometimes 1-2 days etc. But I don't see it go say 3-5 days without a disconnect. 

I'm trying to see if there is anything I can do to improve the reliability of websocket connections or if there is something else that may be causing this.

Has FIX been more reliable in your experience?

**Comment by badgerwithagun** [comment]
I'm not an active user at the moment. Avoiding active crypto trading for a while, so I've got no feel for how often this happens.

**Comment by earce** [comment]
Closing as has been answered
