### ISSUE TITLE
[Kraken-Streaming] websocket connection dead if Kraken returns invalid session message

### ISSUE THREAD

**Issue by earce** [knowm/XChange#3683]
When Kraken returns `ESession:Invalid session` the `KrakenStreamingService.java` class is unable to recover the websocket connectivity. Kraken describes what creates this error message on their website [Why am I getting Session Invalid](https://support.kraken.com/hc/en-us/articles/202966366-Why-am-I-getting-a-Session-Invalid-message-) and have answered this on reddit as well [Session Invalid](https://www.reddit.com/r/Kraken/comments/1z2kh3/session_invalid_immediately_after_first_login/).

This is the second time in about 2 months I've seen this present itself. Log line goes as follows `ERROR info.bitrich.xchangestream.kraken.KrakenStreamingService - Channel null has been failed: ESession:Invalid session`. I was thinking about throwing inside of the `case error:` to have it bubble back up and trigger a reconnect inside the `NettyStreamingService.java`. Not sure if this is the best approach or if this will help with a valid session.

Would love some input @badgerwithagun @mdvx.

**Comment by mdvx** [comment]
Is the problem that the error is occuring when a new IP might have been assigned to the client, or is the problem that the error is not being handled correctly?

For my part, i do all my reconnects outside of knowm, because I maintain state on some structures, and silent reconnects can mess those up (unknown missing data), and also add undetected latency.

**Comment by earce** [comment]
This is happening on AWS based deployment, I am not under the impression EC2 ips are ever reassigned if there is not host restart etc, in a normal running environment I don't think ips will ever change there.

Given that my initial suspicion was that this was a transient issue? Restarting the process seemed to fix it.

How do you do these reconnects outside of knowm? Like are you not using knowm's re-connection logic?

**Comment by earce** [comment]
Does anyone have any other thoughts about this?
