### ISSUE TITLE
Kucoin

### ISSUE THREAD

**Issue by ufotje** [knowm/XChange#3712]
I really love this project and I would like to be kept in the loop.
I was started to build my own arbitrage bot and would like to addept my projct to use your project.
Did you write all the package yourself or are you using sdks where possible?
Cause for Kucoin I know their sdk is bugged, they're working on an update and new release, when you traded the crypto is creditted to your trading account. When you then want to withdraw you first need to send it to your spotaccount, but for internal transfers you can't specify the coin to sent...

**Comment by walec51** [comment]
just look at the code, we write our own clients to REST APIs
