### ISSUE TITLE
Add BRZ on Currency and CurrencyPair class

### ISSUE THREAD

**Issue by mileschet** [knowm/XChange#3729]
Hi, 

I wanted to add the brazilian digital token that's a stable coin listed on some exchanges the project support, i've working on some integrations with Bittrex and it would be nice to have on the core project.

Thank you,

**Comment by walec51** [comment]
just do `new Currency("ANY_OTHER_COIN", "BRZ")` in your project

**Comment by mileschet** [comment]
Well the thing is that some exchanges are listing and i have some projects using the lib, including some implementation of connectors using it. do you still think doesn't worth to have on your parent project so i dont have to maintain my own fork ?
