### ISSUE TITLE
getCurrencyPair deprecated

### ISSUE THREAD

**Issue by cymp** [knowm/XChange#3766]
![image](https://user-images.githubusercontent.com/3685318/95873938-acb56780-0d70-11eb-816e-bc43b1e2e0cc.png)

I know that we now have this Instrument thing, but what is the best practice here if I don't want to have this deprecated use warning?

Maybe @Yampersand ?

**Comment by Yampersand** [comment]
This works for me without any compiler warnings:

```java
final List<CurrencyPair> currencyPairs = exchange.getMarketDataService().getTickers(null)
            .stream()
            .map(Ticker::getInstrument)
            .filter(instrument -> instrument instanceof CurrencyPair)
            .map(instrument -> (CurrencyPair) instrument)
            .collect(Collectors.toList());
```
For most of my use cases I know what kind of instrument I'm dealing with, so I can directly cast into the desired sub type.
Hope this helps.

**Comment by cymp** [comment]
I don't get why CurrencyPair is deprecated.

**Comment by Yampersand** [comment]
The instrument is the "product" you trade:

"XBT/USD" means you trade bitcoins against US dollar. In that case the instrument/ product is represented through a CurrencyPair
"BTC-25JUN21" means you trade a future based on bitcoins, so this product can't be represented through two currencies.

Long speech short: Instrument abstracts the "product" your trading and CurrencyPair is only one possible implementation

**Comment by walec51** [comment]
@cymp if you don't want to deal with other instruments then just filter like in @Yampersand example 

using `getCurrencyPair` will break your code in the future the minute an exchange which you assumed to only support currency pairs starts to support futures contracts - this is why we should migrate to using `getInstrument`

**Comment by cymp** [comment]
All clear, thanks.
