### ISSUE TITLE
[Poloniex-Streaming] Poloniex ws api v1 usage

### ISSUE THREAD

**Issue by earce** [knowm/XChange#3790]
Is anyone involved in this project using Poloniex V1 Websocket api (xchange-stream-poloniex). Documentation online is very sparse and I gather that the WAMP server Poloniex used was why `WampStreamingService` was needed in the library. 

It appears that the WAMP server has been deprecated for some time and I don't see official Poloniex documentation on the subject. I don't know that the WAMP server endpoint is even serviced anymore.

This wamp server brings a significant dependency set that we would go away if we didn't have this as a dependency. Curious to hear anyone else's thoughts.

@badgerwithagun @walec51

**Comment by earce** [comment]
Are we ok with removing Poloniex V1?

**Comment by timmolter** [comment]
One way to find out if it's used anymore is to remove it and see if someone complains. It looks like the V1 streaming API is not supported anymore. Go ahead and remove it.

**Comment by earce** [comment]
https://github.com/knowm/XChange/pull/3797
