### ISSUE TITLE
5.0.4

### ISSUE THREAD

**Issue by earce** [knowm/XChange#3805]
@timmolter would it be possible to cut a release? I know it's a little later then usual but may help folks who discover that kraken connectivity issue later to just bump up to a new version.

**Comment by jurepetrovic** [comment]
That would be really very nice. Thanks, 
Jure

**Comment by mdvx** [comment]
yes, that Kraken problem was a side swipe

**Comment by timmolter** [comment]
yeah, working on it today...

**Comment by timmolter** [comment]
There are a lot of open streaming PRs. Who wants to merge/cancel them?

**Comment by earce** [comment]
Who has the ability to?

**Comment by timmolter** [comment]
@badgerwithagun can merge and is intimately familiar with the streaming code.

**Comment by timmolter** [comment]
I think I'll push a release tomorrow regardless of what happens with the open streaming PRs. Thanks to everyone for all your efforts!

**Comment by timmolter** [comment]
I'm still struggling to get 5.0.4 pushed to Maven Central. I'm having network connection issues in the middle of the builds and other GPG signing issues probably stemming from the fact that I'm using a loaner computer ATM. I'll need some more time to get this figured out.

**Comment by badgerwithagun** [comment]
Apologies for the lack of responsiveness on streaming PRs recently. Actual work has got in the way somewhat. Will try and take a look through the latest PRs in the next few days.

**Comment by timmolter** [comment]
no worries @badgerwithagun :)

**Comment by timmolter** [comment]
I'm still dealing with connection errors to the nexus artifact upload server. I had this before in the past and it eventually fixed itself after a few days so I'll just keep on trying. Here's an example: `[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project xchange-paribu: Failed to deploy artifacts: Could not transfer artifact org.knowm.xchange:xchange-paribu:jar:5.0.4 from/to sonatype-nexus-staging (https://oss.sonatype.org/service/local/staging/deploy/maven2/): Transfer failed for https://oss.sonatype.org/service/local/staging/deploy/maven2/org/knowm/xchange/xchange-paribu/5.0.4/xchange-paribu-5.0.4.jar 504 Gateway Time-out -> [Help 1]`

**Comment by timmolter** [comment]
ok, finally after about a dozen tries over 3 days....
