### ISSUE TITLE
Creating Discord for communication

### ISSUE THREAD

**Issue by earce** [knowm/XChange#3812]
Hi everyone,

Wanted to get some input from the community using this library. Many other important github projects have a Discord setup where users can communicate when issues are going on related to the library or general questions. I am thinking here of the issue last week where Kraken upgraded the websockets and caused some serious problems with users of this library. I think having a real-time channel for users of this lib to talk to each other would be massively beneficial.

Want to get some feedback of who would make use of having something like this setup. And @timmolter wanted to get your thoughts on if you are ok with either me or someone setting this up?

**Comment by nielsdraaisma** [comment]
I would be part of that for sure, great idea.

**Comment by timmolter** [comment]
Well, we do already have this: https://gitter.im/Java-XChange/

**Comment by nielsdraaisma** [comment]
I was about to mention that, but there’s very little activity on that channel. I’d be happy to hang out in a discord if there’s a more active community there.

**Comment by earce** [comment]
I'll set one up and see how it goes. I did notice the glitter but did not see much activity.

**Comment by earce** [comment]
Created this for the time being, https://discord.gg/n27zjVTbDz if we get enough users to adopt it we can add it as a badge on the project.

**Comment by earce** [comment]
I have also added webhook integration from the exchanges into one of the discord channels so that the channel will get notifications direct from the exchanges for those who want a consolidated place for exchange alerts.

**Comment by timmolter** [comment]
Nice, let's put a badge on the readme. I think I'll remove the gitter badge as it's pretty much dead right now.

**Comment by earce** [comment]
Removed glitter and added discord
