### ISSUE TITLE
Error in BSV currencycode translation

### ISSUE THREAD

**Issue by geck64** [knowm/XChange#3829]
Hello, 

While looping on krakenAccountService.getKrakenBalance() map response with KrakenUtils.translateKrakenCurrencyCode,
there is an exception especially on BSV :

> org.knowm.xchange.exceptions.ExchangeException: Kraken does not support the currency code BSV
> at org.knowm.xchange.kraken.KrakenUtils.translateKrakenCurrencyCode(KrakenUtils.java:103) ~[xchange-kraken-5.0.5-SNAPSHOT.jar:?]

Note that the KrakenBalance map was : 

> {ZEUR=xxx, XXBT=xxx, ..., , BSV=0E-10, ATOM=xxx}

**Comment by geck64** [comment]
Issue first mentioned here 
https://github.com/knowm/XChange/issues/2880#issuecomment-739844837

**Comment by earce** [comment]
Do you want to submit a PR in that KrakenUtils class and add BSV to the discontinuedCurrencies map?

**Comment by geck64** [comment]
Yes, i think it's the right fix todo : https://blog.kraken.com/post/2274/kraken-is-delisting-bsv/
Can you do it ?

**Comment by earce** [comment]
I have another review currently in the pipeline so waiting on that, but feel free to, we encourage PRs!

**Comment by geck64** [comment]
> I have another review currently in the pipeline so waiting on that, but feel free to, we encourage PRs!

Here is a try : https://github.com/knowm/XChange/pull/3830

**Comment by earce** [comment]
Thanks for that, merged you in
