### ISSUE TITLE
In Cexio streaming orderbook no alert if orderbook goes out of sync.

### ISSUE THREAD

**Issue by katamarano** [knowm/XChange#3846]
Hello again, another issue in cex.io streaming is in the function 
```java
 @Override
    public OrderBook apply(CexioWebSocketOrderBookSubscribeResponse t) throws Exception {
      OrderBook retVal;
      if (prevID != null && prevID.add(BigInteger.ONE).compareTo(t.id) != 0) {
        orderBookSoFar =
            new OrderBook(new Date(), new ArrayList<LimitOrder>(), new ArrayList<LimitOrder>());
      }

      prevID = t.id;
      orderBookSoFar = CexioAdapters.adaptOrderBookIncremental(orderBookSoFar, t);
      retVal = orderBookSoFar;

      return retVal;
    }
```
in class CexioStreamingMarketDataService.OrderBookUpdateConsumer

First, a new instance of orderBookSoFar is created and then anyway is overwritten by  
```java
orderBookSoFar = CexioAdapters.adaptOrderBookIncremental(orderBookSoFar, t);
```
What is the meaning to create a new instance and then reassign it?
I think that instead of creating a new instance (useless cause then anyway is reassigned) should be thrown an exception cause the orderbook is compromised if the ID of the message is not in sequence with the local ID that was saved from the previous message. Instead, in this case, the user is ignoring that its orderbook messages are out of order and not in sync. Very dangerous imho if the goal is to recreate a local orderbook and keep in  sync.

**Comment by earce** [comment]
This seems right, I think triggering a reconnect and recreation of state would be the right thing

**Comment by earce** [comment]
Closed with PR
