### ISSUE TITLE
Ticker class missing exchange reference

### ISSUE THREAD

**Issue by wolftobias** [knowm/XChange#3855]
Is it possible to add a field which represents the origin Exchange class?

```
org.knowm.xchange.dto.marketdata.Ticker

public class Ticker {

	private Exchange exchange;

	public Exchange getExchange() {
		return exchange;
}
```

**Comment by earce** [comment]
I don't think the exchange is appropriate on ticker @timmolter given it's not typically a field that belongs to ticker

**Comment by timmolter** [comment]
Agreed. Seems like functionality belonging in client code anyway.
