### ISSUE TITLE
Usage of joda-money

### ISSUE THREAD

**Issue by wolftobias** [knowm/XChange#3856]
Why you guys are writing the basic financial stuff yourself?
Why not saving time and use a existing library?

https://www.joda.org/joda-money/

**Comment by timmolter** [comment]
https://github.com/JodaOrg/joda-money/issues?q=xchange

We used it originally, but it became too limiting for cryptocurrencies.

**Comment by wolftobias** [comment]
But that's 8 years ago!
They made also progress and have a good Money implementation when it comes to calculation stuff!
I requested a change for crypto currencies and they implemented it.
Why not give it another try?!

**Comment by timmolter** [comment]
We use BigDecimal for all our calculations just like Jodatime, and it's not that hard to do. If we give them another try we'd probably need to update a hundred thousand lines of code. No one is going to volunteer to do that especially if there is no concrete benefit.

**Comment by wolftobias** [comment]
BigDecimal is not the same as a full functional Money class!

```
// create a monetary value
Money money = Money.parse("USD 23.87");

// add another amount with safe double conversion
CurrencyUnit usd = CurrencyUnit.of("USD");
money = money.plus(Money.of(usd, 12.43d));

// subtracts an amount in dollars
money = money.minusMajor(2);

// multiplies by 3.5 with rounding
money = money.multipliedBy(3.5d, RoundingMode.DOWN);

// compare two amounts
boolean bigAmount = money.isGreaterThan(dailyWage);

// convert to GBP using a supplied rate
BigDecimal conversionRate = ...;  // obtained from code outside Joda-Money
Money moneyGBP = money.convertedTo(CurrencyUnit.GBP, conversionRate, RoundingMode.HALF_EVEN);

// use a BigMoney for more complex calculations where scale matters
BigMoney moneyCalc = money.toBigMoney();
```
The first issue I ean into when building my trading application was i.e. rounding.
The BigDecimal class is just for random numbers, in financial application they need just more functionality.
Is it really 100.000 lines of code? 
Not really, or?!
Some can just extend the ticker interface or implement a provider interface then everybody can decide what to use.
What do you think?
I'm an experienced java developer, I mean I can help and contribute!
