### ISSUE TITLE
gdax.com no more available?

### ISSUE THREAD

**Issue by wolftobias** [knowm/XChange#3860]
Does somebody knows what happend with gdax.com exchange?
Is it down forever?
The website gdax.com is no more reachable!

**Comment by timmolter** [comment]
it's coinbase-pro now.

**Comment by wolftobias** [comment]
Then the exchange specification needs to be updated, right?!

**Comment by timmolter** [comment]
The gdax module is long gone. The coinbase-pro module is missing an  exchange specification. Feel free to add one!
