### ISSUE TITLE
bid volume and ask volume

### ISSUE THREAD

**Issue by caussada** [knowm/XChange#3867]
hy, I know nothing about code , I try to install XchangeKnowm and ask to someone to do that, is it available the data bid volume and ask volume separetly, or there is only the data volume ?

Thanks for your help :)

**Comment by walec51** [comment]
this is a Java library for developers

if you know nothing about code then you should not be using it

**Comment by caussada** [comment]
thanks for your answer, i gonna ask someone to install  it for me in fact , someone on know java, but to avoid to wast his time I just would like to know if there is the tape (time and sale , list of trade) because it's what interested me, and when I watch the exemple of bitstamp in the sire web known.org I dont see it. Do you have this information ?

**Comment by timmolter** [comment]
with xchange you can get a list of recent trades in one API call and the orderbook in another API call which give all the bids and asks together. Most exchanges offer a 24-hour ticker endpoint as well which contains the 24-hour volume. If you want to calculate your own volume, you can just sum all the trades over whatever time period you want.

**Comment by caussada** [comment]
thanks a lot Timmolter :) you really helped me  !
