### ISSUE TITLE
[CoinbasePro] Exception 'request timestamp expired'

### ISSUE THREAD

**Issue by milczarekIT** [knowm/XChange#3871]
I noticed 'request timestamp expired' problem after https://github.com/knowm/XChange/pull/3818 (and using synchronized incremental nonce).
But problem is not https://github.com/knowm/XChange/pull/3818, but using nonce. CoinbasePro similar to Binance is not using nonce in request. 

They are using timestamp. Accoring to spec (https://docs.pro.coinbase.com/#selecting-a-timestamp):

> The CB-ACCESS-TIMESTAMP header MUST be number of seconds since Unix Epoch in UTC. Decimal values are allowed.
> 
> Your timestamp must be within 30 seconds of the api service time or your request will be considered expired and rejected. We recommend using the time endpoint to query for the API server time if you believe there many be time skew between your server and the API servers.

Current implementation in xchange is working for few request... Each request has incremented timestamp by 1s, so after 30+ requsts in 1 second there is an error 'request timestamp expired'

**Comment by earce** [comment]
Which version of xchange are you currently using? 

I think this _does_ introduce a bug but not in the way you describe. The code does not simply increment the timestamp after taking it once. It it takes the timestamp and tries to use that, if the timestamp happens to be the same as what was last taken then it increments it (like a nonce) but in this case we don't want the nonce we just want the timestamp. A simpler code review would be 

```
private final SynchronizedValueFactory<Long> nonceFactory = 
          () -> System.currentTimeMillis() / 1000;
```

**Comment by timmolter** [comment]
I don't understand how this would fix the issue. And NOT using `CurrentTimeIncrementalNonceFactory` will cause other issues later.

**Comment by earce** [comment]
The way I understand it from this excerpt:

> The CB-ACCESS-TIMESTAMP header MUST be number of seconds since Unix Epoch in UTC
> Your timestamp must be within 30 seconds of the api service time or your request will be considered expired and rejected.

This makes it clear to me that a nonce is not necessary, a timestamp is what is required. As an example:

If we have timestamp 1000000000, if we make 1, 15 or 60 requests at that second the timestamp should _always_ be the same. If however we have an incrementing nonce, if we make 60 requests we would submit timestamps in the message ranging from 1000000000...1000000060, which at timestamp 1000000000 the largest drift allowed is 30 seconds so the largest possible value valid would 1000000030. This is incorrect behavior. 

We should only submit 1000000000 regardless of number of requests.

**Comment by timmolter** [comment]
Ah ok. That makes sense.

**Comment by milczarekIT** [comment]
@earce thank you for your clarification, that was the problem.
