### ISSUE TITLE
[coinbasepro] Cannot specify a size of base currency in a buy order

### ISSUE THREAD

**Issue by katamarano** [knowm/XChange#3884]
Hello,
don't know if I'm missing something here, but according the implementation, I cannot specify a size of the amount of coins I want to buy, in a buy order (market)

```java
public static CoinbaseProPlaceMarketOrder adaptCoinbaseProPlaceMarketOrder(
      MarketOrder marketOrder) {
    return new CoinbaseProPlaceMarketOrder.Builder()
        .productId(adaptProductID(marketOrder.getCurrencyPair()))
        .clientOid(marketOrder.getUserReference())
        .type(CoinbaseProPlaceOrder.Type.market)
        .side(adaptSide(marketOrder.getType()))
        .funds(marketOrder.getType() == OrderType.BID ? marketOrder.getOriginalAmount() : null)
        .size(marketOrder.getType() == OrderType.ASK ? marketOrder.getOriginalAmount() : null)
        .build();
  }
```

If the order is a BUY, the order Type is BID...so this will result in size 0 and fund equals to the size I specified.
If my transaction is BTC-EUR, and i specify 0.1 in size (of course this means 0.1 BTC to buy), it will translate to 0.1 EUR to use to buy BTC.
Seems that i can specify an amount of coins only if I sell, but not if I buy.
Am I missing something here?

**Comment by katamarano** [comment]
Hi, try to ping again on this, cause I cannot udnerstand the reason why it was implemented in this way.
Accordin to coinbase pro documentation:

MARKET ORDER PARAMETERS
-size | [optional]* Desired amount in base currency
-funds | [optional]* Desired amount of quote currency to use
One of size or funds is required.


But in the code:
```java
 .funds(marketOrder.getType() == OrderType.BID ? marketOrder.getOriginalAmount() : null)
 .size(marketOrder.getType() == OrderType.ASK ? marketOrder.getOriginalAmount() : null)
```
There is no way to specify a size in a BID order, and there is no way to specify a price (fund) in a ASK order.
Any reason for this?

**Comment by walec51** [comment]
coinbases documentation states that you pass either size or funds

you don't pass both

in a BID we set funds, in ASK we set size - thing wrong here

in the original amount just set the amount of currency you want to buy or sell

**Comment by katamarano** [comment]
Hello, thanks for replying.
I don't set both funds and size. I set only size. If you specifiy the size in the originalAmount, in a BUY, the code in xchange will use it as a FUNDS.
I can repeat the example, if my transaction is BTC-EUR, and I specify 0.1 in original amount (of course this means I want to buy 0.1 BTC), it will assign this value to the funds field. So when the BUY is performed, you will buy not 0.1 BTC, but only the BTC that you can buy with 0.1 EUR, and clearly this will return error cause 0.1 is not  enough to reach the limit for transactions in EUR.
I report again the code:

 .funds(marketOrder.getType() == OrderType.BID ? marketOrder.getOriginalAmount() : null)
 .size(marketOrder.getType() == OrderType.ASK ? marketOrder.getOriginalAmount() : null)
 
 The size is 0 when you perform a BID type order.
