### ISSUE TITLE
difference binance and binance stream , huobi and huobi stream 

### ISSUE THREAD

**Issue by caussada** [knowm/XChange#3893]
Hello,   I m looking for the API for binance future and huobi future, I installed the simple binance and huobi xchange API wich are for the spot data . do Binance stream and huboi stream are the futures by any chance ? Thanks for your help

**Comment by walec51** [comment]
future are not fully supported by this yet 

@douggie started working on it but never finished

you can pick up where he left https://github.com/knowm/XChange/pull/3473
