### ISSUE TITLE
Bittrex user trades are always classified as SELLs

### ISSUE THREAD

**Issue by det-mark** [knowm/XChange#3898]
`BittrexAdapters.adaptUserTrades(...)` classifies user trades as SELLs regardless of order type.

Probably a typo: `adaptUserTrades(...)` looks at `bittrexOrder.getType()` instead of `bittrexOrder.getDirection()`.

Per https://bittrex.github.io/api/v3#/definitions/Order, type is the order type (`LIMIT`, `MARKET`, etc.) while direction is `BUY` or `SELL`.

**Comment by earce** [comment]
This definitely seems like a bug, feel free to submit a PR
