### ISSUE TITLE
Implement itBit

### ISSUE THREAD

**Issue by jheusser** [knowm/XChange#391]
ItBit (http://www.itbit.com) recently released their API. Example implementation can be found here:
http://api-portal.anypoint.mulesoft.com/itbit/api/itbit-exchange/docs/code
http://api-portal.anypoint.mulesoft.com/itbit/api/itbit-exchange/docs/raml

I'm currently developing this, but please let me know if you wanted to help.

**Comment by timmolter** [comment]
@jheusser Do you know the status of this exchange? I cannot see their API docs or get a simple Ticker fetch working.

**Comment by jheusser** [comment]
@timmolter ItBit is implemented and works fine for me, authenticated and unauthenticated. API docs are here http://api-portal.anypoint.mulesoft.com/itbit/api/itbit-exchange#raml-console

**Comment by timmolter** [comment]
@jheusser OK, thanks. Do you know where the public API docs are for the orderbook and trades?

Also, why is the Ticker only available over the private API? Do you know?
