### ISSUE TITLE
[Binance] Live subscribing/unsubscribing

### ISSUE THREAD

**Issue by dpageau2021** [knowm/XChange#3914]
Hello,
Do you have any plans to add the live subscribing/unsubscribing coins feature in stream-binance library? (Available in Binance since last year)

Thanks

**Comment by earce** [comment]
If the feature is not currently available with XChange feel free to open a PR

**Comment by dpageau2021** [comment]
> If the feature is not currently available with XChange feel free to open a PR

I'm working on it

**Comment by dpageau2021** [comment]
@earce @timmolter  I have a PR ready but I don't have access to push my branch:
`remote: Permission to knowm/XChange.git denied to dpageau2021.
fatal: unable to access 'https://github.com/knowm/XChange.git/': The requested URL returned error: 403`

Thanks

**Comment by dpageau2021** [comment]
https://github.com/knowm/XChange/pull/3943

**Comment by dpageau2021** [comment]
Fix merged
