### ISSUE TITLE
[bitfinex] bid size and ask size websockets tickers #

### ISSUE THREAD

**Issue by youssef-cooptalis** [knowm/XChange#3938]
Would you please adjust the websocket streaming of bitfinex to take bid and ask size into consideration?

**Comment by youssef-cooptalis** [comment]
That’s the file location https://github.com/knowm/XChange/blob/develop/xchange-stream-bitfinex/src/main/java/info/bitrich/xchangestream/bitfinex/dto/BitfinexWebSocketTickerTransaction.java

**Comment by earce** [comment]
Feel free to submit a PR
