### ISSUE TITLE
What happen to an Order to make if the HTTP POST fail during the response?

### ISSUE THREAD

**Issue by yaniferhaoui** [knowm/XChange#3950]
Hello,

When I make a buy/sell order I would like to handle IO exceptions during the HTTP response and be sure to don't duplicate the order.

Some exchanges allow to use Client Order ID, so if an exceptions occurs, I can just check if the order exists with my own generated ID => So try again if the order don't exists.

But for exchanges which don't have this feature, I can't check if the order exists because I don't receive any results (Just a connection error).

So there is any rule in the HTTP world which says if a POST response is not correctly send back to the user => Don't make the transaction ? (So in this case I can just try again and be sure to don't duplicate order)

Thanks in advance :)

**Comment by earce** [comment]
In theory it should be this way, but this is really going to come down to the specific exchange's implementation so better to confirm and validate against each particular exchange.

**Comment by walec51** [comment]
if an exchange allows you to  pass a user reference to the order then you can check if the order got added, if not then there is no 100% sure way to know if the request succeeded or not
