### ISSUE TITLE
Stream FTX : Checksum is not correct!

### ISSUE THREAD

**Issue by dgosset** [knowm/XChange#4014]
Hi,

I try the stream with FTX (code is like the example) and this part cause an issue : Checksum is not correct!

class FtxStreamingAdapters

                if (!calculatedChecksum.equals(message.getChecksum())) {
                  throw new RuntimeException("Checksum is not correct!");
                }
If i comment this lines (88/89/90), it's worked. I receive the orderbook.

**Comment by bitcoinmat-dev** [comment]
what is the issue? Can you please send the stacktrace. Thanks

**Comment by makarid** [comment]
What is the issue? Can you please send the stacktrace? Thanks

**Comment by makarid** [comment]
This happens after an unsubscribe message send and then trying to reconnect. I am investigating right now. If anyone knows about  the internal mechanism of NettyStreamingService please add any comment on this issue . Thanks

**Comment by dgosset** [comment]
Hi @makarid,

I comment the checksum part to work, and i don't understand if the current code (xchange) match with the FTX Documentation.

Did you worked with this stream orderbook and FTX?
Because, the stream always add values on my orderbook. And the init doesn't work for me.

https://docs.ftx.com/#orderbooks
Initial snapshot
Upon subscribing, you will receive one snapshot of the orderbook (partial) with a data field containing:
>> looks like empty for me. But after i receive updates.

Updates
After receiving your snapshot, you will be streamed updates (message type is update) that have data fields with:
>> with the update i try to update my local orderbook, but the size is growing

Part of my code for example. 
`
		
		
		Exchange exchangeFTX = ExchangeFactory.INSTANCE.createExchange(FtxExchange.class);
		FtxMarketDataService marketDataService = (FtxMarketDataService) exchangeFTX.getMarketDataService();
		try {
			orderBook = marketDataService.getOrderBook(CurrencyPair.BTC_USD);
			
		} catch (IOException e) {
			e.printStackTrace();
		}
		
		FtxStreamingExchange exchange = (FtxStreamingExchange) StreamingExchangeFactory.INSTANCE.createExchange(FtxStreamingExchange.class); // FtxStreamingExchange.class
		 exchange
	        .connect(
	            ProductSubscription.create()
	                .addOrderbook(CurrencyPair.BTC_USD)
	                .build())
	        .blockingAwait();

		Disposable subscription2 = exchange.getStreamingMarketDataService()
		    .getOrderBook(CurrencyPair.BTC_USD)
		    .subscribe(
		    		orderBookUpdate -> {
		    			if (orderBookUpdate.getBids().size() > 0 && orderBookUpdate.getAsks().size() > 0) {
		    				
		    				for (LimitOrder limitOrder : orderBookUpdate.getAsks()) {
			    				 OrderBookUpdate update = new OrderBookUpdate(OrderType.ASK, limitOrder.getOriginalAmount(), limitOrder.getInstrument(), limitOrder.getLimitPrice(), orderBookUpdate.getTimeStamp(), limitOrder.getOriginalAmount());
			    				 orderBook.update(update);
		    				}
		    				 
		    				for (LimitOrder limitOrder : orderBookUpdate.getBids()) {
			    				 OrderBookUpdate update = new OrderBookUpdate(OrderType.BID, limitOrder.getOriginalAmount(), limitOrder.getInstrument(), limitOrder.getLimitPrice(), orderBookUpdate.getTimeStamp(), limitOrder.getOriginalAmount());
			    				 orderBook.update(update);
		    				}

		    			}
		    		},
    				throwable -> LOGGER.error("Error in trade subscription", throwable)
		);
`

**Comment by makarid** [comment]
I think you are doing it wrong. No need to update your local orderbook like this. You just need to tell that:

youLocalOrderbook = streamingOrderbook;

**Comment by phraktle** [comment]
Indeed, the most basic example fails with a checksum error:

```
      var x = StreamingExchangeFactory.INSTANCE.createExchange(FtxStreamingExchange.class);
      x.connect().blockingAwait();
      x.getStreamingMarketDataService().getOrderBook(CurrencyPair.BTC_USD)
              .subscribe(book -> System.out.println(book.getTimeStamp()));
```

**Comment by makarid** [comment]
Thank you for your message! I am looking forward to make it much better,
please feel free to give any advice how to implement it. Thanks

**Comment by mdvx** [comment]
https://github.com/knowm/XChange/pull/4151/commits/20154ce6504cd077d219888deb1f8e5e7737f254

**Comment by earce** [comment]
Fixed by @mdvx
