### ISSUE TITLE
[Bitstamp] Some Currency Metadata and CurrencyPair Metadata are null

### ISSUE THREAD

**Issue by mathvdh** [knowm/XChange#4024]
When calling the functions `.getCurrencies` and `.getCurrencyPairs` which are defined in `org.knowm.xchange.dto.meta.ExchangeMetaData`.

Some of the metadata were null. Basically everything that was not defined in `/resources/bitstamp.json` was returning null for the metadata.

After inspection, this is because the `remoteInit()` function of `org.knowm.xchange.bitstamp.BitstampExchange` is not doing much, more specifically the `BitstampAdapters.adaptMetaData(Arrays.asList(bitstampPairInfos), exchangeMetaData)` function is just adding currencies and pairs from API Call that it cannot find in bitstamp.json but not parsing the metadata from the Api call and just adding the currencies and currencypairs with "null" as meta data.

I have updated the bitstamp.json with new currencies infos (taken from : [https://www.bitstamp.net/fee-schedule/](https://www.bitstamp.net/fee-schedule/))
And I have updated the "adaptMetaData" so that it will fill the infos it can find from the Api Call.

I will submit a PR that fixes this.

**Comment by mathvdh** [comment]
I forgot that my current develop branch is already out of sync, so the PR #4023 contains both the fixes for #4021 and #4021

**Comment by earce** [comment]
Closing as merged
