### ISSUE TITLE
How to get all historical data from a specific asset?

### ISSUE THREAD

**Issue by PanagiotisDrakatos** [knowm/XChange#4025]
i am wondering how to get all historical data from a specific asset from the start until the end. i am trying something like this with no success

   ```
Exchange bitstamp = ExchangeFactory.INSTANCE.createExchange(BinanceExchange.class);
        MarketDataService marketDataService = bitstamp.getMarketDataService();
        List<CurrencyPair> list=bitstamp.getExchangeSymbols();
        list.stream().forEach(val-> System.out.println(val.toString()));
        List<Ticker> ticker = marketDataService.getTickers((Params) list.get(2));
        System.out.println(ticker.toString());
```

**Comment by earce** [comment]
This is very dependent on the data you want to get and if the exchanges support queries of this nature, many do not. I would defer to individual exchange APIs and if there is one where the xchange api does not have it you can submit a PR to add it!
