### ISSUE TITLE
Coinbasepro: MarketOrder incorrect (currency pair and type)

### ISSUE THREAD

**Issue by straumat** [knowm/XChange#4028]
_The first listed currency of a currency pair is called the base currency, and the second currency is called the quote currency. When you buy a currency pair, you buy the base currency and sell the quote currency so when you are making a buy on BTC/EUR, you should be getting BTC for euros._

It works this way with other exchanges (like kucoin for example) but, with Coinbasepro things don't work this way.

This is the test I'm running on Coinbase sandbox:
- Buying 10 BTC with Euro.
- Selling 20 BTC for euro

The result is:
- 10 euro bought.
- 1 BTC sold.

This is my code:
```
        final CurrencyPair cp = new CurrencyPair(Currency.BTC, Currency.EUR);

        // Creates a buy market order.
        MarketOrder buyingOrder = new MarketOrder(Order.OrderType.BID,    // Buying order.
                new BigDecimal("10"), // "10".
                cp);    // BTC / EUR.
        final String buyingOrderId = tradeService.getXChangeService().placeMarketOrder(buyingOrder);
        System.out.println("Buying 10 BTC with Euro, order number " + buyingOrderId);

        // Creates a buy market order.
        MarketOrder sellingOrder = new MarketOrder(Order.OrderType.ASK,    // Selling order.
                new BigDecimal("1"), // "1".
                cp);    // BTC / EUR.
        final String sellingOrderId = tradeService.getXChangeService().placeMarketOrder(sellingOrder);
        System.out.println("Selling 1 BTC for Euro, order number " + sellingOrderId);
```

The result:
```
Buying 10 BTC with Euro, order number b1d0b278-659e-4f96-83bc-583222e35f94
Selling 1 BTC for Euro, order number 7a41c749-0fb9-4063-8d72-ee3eb5017f6a
```

And this is the result in Coinbasepro Sandbox:
![coinbase](https://user-images.githubusercontent.com/536498/115972277-adb02880-a54d-11eb-881c-1b7a411ecdd3.png)

How come 10 euros was bought? instead of buying BTC ?

**Comment by straumat** [comment]
In the coinbase [place a new order documentation](https://docs.pro.coinbase.com/#place-a-new-order) I read this:
_FUNDS
The funds field is optionally used for market orders. When specified it indicates how much of the product quote currency to buy or sell. For example, a market buy for BTC-USD with funds specified as 150.00 will spend 150 USD to buy BTC (including any fees). If the funds field is not specified for a market buy order, size must be specified and Coinbase Pro will use available funds in your account to buy bitcoin._

And in the code, [CoinbaseProAdapters](https://github.com/knowm/XChange/blob/fa4e891f5035fceb94fac50d8d0864acb86a5272/xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbaseProAdapters.java#L444), I see this code:

```
public static CoinbaseProPlaceMarketOrder adaptCoinbaseProPlaceMarketOrder(
      MarketOrder marketOrder) {
    return new CoinbaseProPlaceMarketOrder.Builder()
        .productId(adaptProductID(marketOrder.getCurrencyPair()))
        .clientOid(marketOrder.getUserReference())
        .type(CoinbaseProPlaceOrder.Type.market)
        .side(adaptSide(marketOrder.getType()))
        .funds(marketOrder.getType() == OrderType.BID ? marketOrder.getOriginalAmount() : null)
        .size(marketOrder.getType() == OrderType.ASK ? marketOrder.getOriginalAmount() : null)
        .build();
  }
```

I changed it to:
```
    public static CoinbaseProPlaceMarketOrder adaptCoinbaseProPlaceMarketOrder(
            MarketOrder marketOrder) {
        return new CoinbaseProPlaceMarketOrder.Builder()
                .productId(adaptProductID(marketOrder.getCurrencyPair()))
                .clientOid(marketOrder.getUserReference())
                .type(CoinbaseProPlaceOrder.Type.market)
                .side(adaptSide(marketOrder.getType()))
                .size(marketOrder.getOriginalAmount())
                //.funds(marketOrder.getType() == OrderType.BID ? marketOrder.getOriginalAmount() : null)
                //.size(marketOrder.getType() == OrderType.ASK ? marketOrder.getOriginalAmount() : null)
                .build();
    }
```

And it seems to work. Can I have your opinion? 
Should I make a merge request ?

**Comment by straumat** [comment]
In the coinbase [place a new order documentation](https://docs.pro.coinbase.com/#place-a-new-order) I read this:
_FUNDS
The funds field is optionally used for market orders. When specified it indicates how much of the product quote currency to buy or sell. For example, a market buy for BTC-USD with funds specified as 150.00 will spend 150 USD to buy BTC (including any fees). If the funds field is not specified for a market buy order, size must be specified and Coinbase Pro will use available funds in your account to buy bitcoin._

And in the code, [CoinbaseProAdapters](https://github.com/knowm/XChange/blob/fa4e891f5035fceb94fac50d8d0864acb86a5272/xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbaseProAdapters.java#L444), I see this code:

```
public static CoinbaseProPlaceMarketOrder adaptCoinbaseProPlaceMarketOrder(
      MarketOrder marketOrder) {
    return new CoinbaseProPlaceMarketOrder.Builder()
        .productId(adaptProductID(marketOrder.getCurrencyPair()))
        .clientOid(marketOrder.getUserReference())
        .type(CoinbaseProPlaceOrder.Type.market)
        .side(adaptSide(marketOrder.getType()))
        .funds(marketOrder.getType() == OrderType.BID ? marketOrder.getOriginalAmount() : null)
        .size(marketOrder.getType() == OrderType.ASK ? marketOrder.getOriginalAmount() : null)
        .build();
  }
```

I changed it to:
```
    public static CoinbaseProPlaceMarketOrder adaptCoinbaseProPlaceMarketOrder(
            MarketOrder marketOrder) {
        return new CoinbaseProPlaceMarketOrder.Builder()
                .productId(adaptProductID(marketOrder.getCurrencyPair()))
                .clientOid(marketOrder.getUserReference())
                .type(CoinbaseProPlaceOrder.Type.market)
                .side(adaptSide(marketOrder.getType()))
                .size(marketOrder.getOriginalAmount())
                //.funds(marketOrder.getType() == OrderType.BID ? marketOrder.getOriginalAmount() : null)
                //.size(marketOrder.getType() == OrderType.ASK ? marketOrder.getOriginalAmount() : null)
                .build();
    }
```

And it seems to work. Can I have your opinion? 
Should I make a merge request ?

**Comment by straumat** [comment]
With this change, it seems to work:
```
        final CurrencyPair cp = new CurrencyPair(Currency.BTC, Currency.EUR);

        // Creates a buy market order.
        MarketOrder buyingOrder = new MarketOrder(Order.OrderType.BID,    // Buying order.
                new BigDecimal("3"), // "3".
                cp);    // BTC / EUR.
        final String buyingOrderId = tradeService.getXChangeService().placeMarketOrder(buyingOrder);
        System.out.println("Buying 3 BTC with Euro, order number " + buyingOrderId);

        // Creates a buy market order.
        MarketOrder sellingOrder = new MarketOrder(Order.OrderType.ASK,    // Selling order.
                new BigDecimal("2"), // "2".
                cp);    // BTC / EUR.
        final String sellingOrderId = tradeService.getXChangeService().placeMarketOrder(sellingOrder);
        System.out.println("Selling 2 BTC for Euro, order number " + sellingOrderId);
```

I get the following results:
![coinbase](https://user-images.githubusercontent.com/536498/115974342-29b16d00-a55c-11eb-8647-935ab139b33d.png)
![coinbase](https://user-images.githubusercontent.com/536498/115974352-48afff00-a55c-11eb-945f-401240785deb.png)

Only strange things, the size of the buy....

**Comment by earce** [comment]
Is this something that has always been an issue for you or as of a certain version?

**Comment by straumat** [comment]
@earce In fact, I just started using the cionbasepro.
For my project [Cassandre](https://github.com/cassandre-tech/cassandre-trading-bot), I was only using kucoin until last weed.

**Comment by garciapd** [comment]
Hi, the CoinbasePro implementation is like that on purpose, in their API you can define if you are placing the order in base or quote, in the case of Market Order when buying, i see better to specify the quote, as you specify the amount in EUR you want to spend at the market price. Although it is true that the other exchanges works as you were expected and can get confusing.

**Comment by straumat** [comment]
@garciapd from my tests, you are using the XChange API to ask for something in a normalized way and you don't get the expected result. Coinbase can specify things on its own but XChange is supposed to provide the same behavior no matter the exchange

**Comment by earce** [comment]
@straumat I would mostly agree with you except in the case where there are things which are very exchange specific. Some websocket apis have the ability to send subscriptions while the socket is open, others need the pairs upfront. 

If this is significant enough you can submit a PR and we can review it.

**Comment by straumat** [comment]
@earce yes but coinbase says the parameter xchange is not mandatory... so why are we fulfilling it as it creates a strange behavior ?

**Comment by earce** [comment]
I am not sure I was not involved in the original implementation but if it does not make sense here we can modify it.

**Comment by garciapd** [comment]
@straumat I agree there have to be consistency, as much as possible. There are also implementations where the amount to trade need to include the fees and others not.

If you decide to change it, I would suggest to add it in the release notes, as even if it brings consistency which is good, there is a breaking change and will affect many people.

**Comment by straumat** [comment]
@garciapd indeed, you are right!

**Comment by straumat** [comment]
@earce  Hi, it seems that my code was removed :( is it normal ?
