### ISSUE TITLE
[Bittrex] Trade history query support for TradeHistoryParamsTimeSpan

### ISSUE THREAD

**Issue by det-mark** [knowm/XChange#4050]
The Bittrex `GET /orders/closed` API (https://bittrex.github.io/api/v3#operation--orders-closed-get) used for querying trade history supports `startDate` and `endDate` parameters to specify a time range for the query.

At present the implementation of `BittrexAuthenticated.getClosedOrders` does not support these parameters, and so `BittrexTradeService.getTradeHistory` ignores any time range that may be provided in a `TradeHistoryParams` that implements `TradeHistoryParamsTimeSpan`.

Looks like it should be straightforward to add this functionality to the query (unless there is a reason I'm unaware of).

**Comment by earce** [comment]
Feel free to submit a PR we can review
