### ISSUE TITLE
Binance WAPI removal  

### ISSUE THREAD

**Issue by otbalance** [knowm/XChange#4059]
According to Binance info:

"To optimize API performance and provide better trading services for our API users, Binance will delist all WAPI endpoints from the Binance API at 2021-08-01 2:00 AM (UTC). Information on WAPI endpoints will be removed from Binance API Documentation at approximately 2021-06-01 2:00 AM (UTC). "

Do you plan to have a binance client compatible with their changes ?

If so in which release?

**Comment by earce** [comment]
Hi if there is a feature you want please submit a PR

**Comment by otbalance** [comment]
Binance will decommission all WAPI endpoints. Currently XChange binance connector is using them. Are you aware of that change? They are going to stop supporting all WAPI endpoints by August 2021. 

Do you plan to remove them and change them to supported ones?

**Comment by earce** [comment]
I am not aware of anyone working on this, this project is community driven and a product of folks generously giving their time to keep this project up to date!

**Comment by otbalance** [comment]
Ok, we will try to research what should be changed and maybe we can help out with this.

**Comment by mrmx** [comment]
I'm aware and maybe can help with that due to a project I'm building and focused in Binance as first target.

**Comment by mrmx** [comment]
Feel free to start it on your fork and announce it as a WIP PR
