### ISSUE TITLE
Binance testnet/sandbox initialization/authentication  problem

### ISSUE THREAD

**Issue by vaseok10** [knowm/XChange#4079]
Unable to initialize Binance sandbox.

implementation pull request: https://github.com/knowm/XChange/pull/4042

**Comment by walec51** [comment]
this this pull request solve the problem?

can we close this issue now?

**Comment by mrmx** [comment]
I left a comment with a workaround in the #4042 pull request. I'd close this issue.

**Comment by vaseok10** [comment]
you can close, but that is just an workaround.
