### ISSUE TITLE
[Kraken] Orderbooks are getting crossed under load

### ISSUE THREAD

**Issue by mdvx** [knowm/XChange#4080]
KrakenOrderbookExample

`        List<CurrencyPair> currencyPairs = Lists.list(CurrencyPair.BTC_USD, CurrencyPair.LTC_USD, CurrencyPair.ETH_USD, CurrencyPair.BTC_EUR);

        currencyPairs.forEach(cp -> {
            krakenExchange
                    .getStreamingMarketDataService()
                    .getOrderBook(cp)
                    .subscribe(
                            s -> {
//                                LOG.info("Received {}", s);

                                if (s.getBids().get(0).getLimitPrice().compareTo(s.getAsks().get(0).getLimitPrice()) >= 0)
                                    LOG.error("CROSSED book");
                            },
                            throwable -> {
                                LOG.error("Fail to get ticker {}", throwable.getMessage(), throwable);
                            });

        });
`

CROSSED book is hit after a few seconds

With one book it is fine, discovered in my system, a few days/weeks ago.  Now replicated here.

@nielsdraaisma

**Comment by mdvx** [comment]
I was also able to reproduce in unit test after running for a little longer
so far only CROSSED book, and not the milder case of a LOCKED book.

**Comment by mdvx** [comment]
Ah, the Cross occurs at quantity == 0, that is the delete signal.  

` if (bid.getOriginalAmount().compareTo(BigDecimal.ZERO) > 0 && ask.getOriginalAmount().compareTo(BigDecimal.ZERO) > 0) {
                                    if (bid.getLimitPrice().compareTo(ask.getLimitPrice()) > 0)
                                        LOG.error("CROSSED book");
                                    else if (bid.getLimitPrice().compareTo(ask.getLimitPrice()) == 0)
                                        LOG.error("LOCKED book");
                                }`


however this is still producing CROSSED errors

**Comment by mdvx** [comment]
timestamp=Sat May 22 23:13:30 EDT 2021 
timestamp=Sat May 22 23:15:23 EDT 2021  

1m53s diff on top of book?

That leads me to speculate that the delete signal (qty==0) is being incorrectly processed.

**Comment by mdvx** [comment]
`
//KrakenStreamingAdapters
public static OrderBook adaptOrderbookMessage(OrderBook orderBook, Instrument instrument, ArrayNode arrayNode) 
{
...

        return new OrderBook(
                orderBook.getTimeStamp(),
                Lists.newArrayList(orderBook.getAsks().stream().filter(lo -> lo.getOriginalAmount().compareTo(BigDecimal.ZERO) != 0).collect(Collectors.toList())),
                Lists.newArrayList(orderBook.getBids().stream().filter(lo -> lo.getOriginalAmount().compareTo(BigDecimal.ZERO) != 0).collect(Collectors.toList())),
                true);
    }`
    
  // DOES NOT FIX, so much for the quick solution

**Comment by nielsdraaisma** [comment]
I will update this PR, I found some other crossed book cases but am pretty confident I’ve got a new fix for that.

**Comment by gewure** [comment]
any updates on this?

**Comment by mdvx** [comment]
What ever the bug, I think it effects more than just Kraken, I saw similar on another exchange

**Comment by gewure** [comment]
This is very nasty, since reliance on the integrity of streaming-data is paramount for most systems using xchange, i guess.
It is, for our application.

What other exchange did you encounter this @mdvx ?

**Comment by mdvx** [comment]
We need to reopen this, created a PR that alleviates but does not cure.
https://github.com/knowm/XChange/pull/4239
