### ISSUE TITLE
Add support for querying solana RPC

### ISSUE THREAD

**Issue by douggie** [knowm/XChange#4096]
Having programmatic access to various block chains proves useful (i.e. bitcoincore), especially to retrieve data which is then uses to then place orders on a dex or central exchange.

It would be very helpful, for me, and I am sure others, to be able to access various information from Solana via xchange.

The first implementation i would imagine the following methods exposed via an AccountService
* https://docs.solana.com/developing/clients/jsonrpc-api#gettokenaccountsbyowner
* https://docs.solana.com/developing/clients/jsonrpc-api#getbalance

Any objections for me to raise pull request for a new xchange/solana module that just implements the AccountService similarly to bitcoincore?

**Comment by earce** [comment]
This is really meant to query exchanges not blockchains.

**Comment by douggie** [comment]
but we have examples of this in the project, such as bitcoincore.

**Comment by douggie** [comment]
Will just be a pain to fork the project, maintain the solana rest interface and keep it up to date.

**Comment by earce** [comment]
I haven't been a maintainer when those modules were added @timmolter can opine more on this topic, but I don't see why conflate this project with blockchain explorer libraries, they are fundamentally different things.

**Comment by douggie** [comment]
okey, and adding an account service to the serum project that queries solana adresses is a no go too?

**Comment by earce** [comment]
I think that would make sense because all Solana addresses can become addresses for exchange interaction. But I would be more curious about what that would turn into as more features are added.

I would leave it to @timmolter about where to draw the line, not sure if he cares about adding this functionality at all, this is just my opinion.

**Comment by douggie** [comment]
all I am interested is is balances for a given public key, so seems ok to raise a PR for that within the serum module.

**Comment by douggie** [comment]
i'll open another issue releated to just the serum changes.

**Comment by douggie** [comment]
https://github.com/knowm/XChange/issues/4097 for the serum changes

**Comment by timmolter** [comment]
Feel free to add this, as it's an addition to the serum DEX.
