### ISSUE TITLE
Very very incomplete implementation of Bittrex/and many other generic services

### ISSUE THREAD

**Issue by aligokalppeker** [knowm/XChange#4103]
As i look into the implementation of Bittrex generic services implementation, i see "BittrextAdapters" class has such an incomplete and erroneous code :

` public static void adaptMetaData(List<BittrexSymbol> rawSymbols, ExchangeMetaData metaData) {`
    `    BittrexAdapters.adaptCurrencyPairs(rawSymbols).forEach(`
    `        currencyPair -> {`
    `          metaData.getCurrencyPairs().putIfAbsent(currencyPair, null);`
    `          metaData.getCurrencies().putIfAbsent(currencyPair.base, null);`
    `          metaData.getCurrencies().putIfAbsent(currencyPair.counter, null);`
    `        });`
`  }`

(This code belongs to @walec51 as git blame shows)

This code fills the pairs and currency only with their name and leaves other fields as null(or with default value with the lucky ones read from the static resource file). Any developer which aims to use generic interfaces gets incomplete/inconsistent currencies and/or currency pairs with null fields(wallet health, fees etc..).

Me and my colleague, as we traverse the code within the scope of generic exchange implementations, see many of these incomplete implementations. They are just seem to be implemented for "just putting some code on the method that returns something" 

I am fixing this issue in a separate branch. But i want to open this issue, because such situations cause frustrations about the stability/functionality of the xchange and it is required moderate and avoid contribution of such "bad examples" to get more community interest/investment on the project.

NOTE: By the way, its interface and other design concepts of xchange is good. I appreciate the other qualities of the library( domain model-dto, adapters and API decorators)

**Comment by cymp** [comment]
I don't understand your concern. It looks like the author added some information, which is better than having no information at all. Maybe (and likely) he didn't have the complete information at the implementation time and put what he knew.  Better than nothing, and you can complete the missing information if you like, but I can't understand what you see as "erroneous".

**Comment by aligokalppeker** [comment]
If you want to understand my concern get to the "Exchange Support" site in wiki and see what writes for the "Bittrex". It is stated as supported but the implementation is far away from the statement. This is misdirection or bad quality work. You should define a explicit "definition of done" process for an exchange and mark it supported as you have all of them complete.

I understand your mindset in this situation but defensive behavior is not healthy for improvement of an open source project. We should be able to embrace the problematic parts of a project to improve them. You should not make shallow comments just to defend against a critic.

**Comment by walec51** [comment]
@aligokalppeker you right - that that wiki page is out of date

but that said - this is an open source project

I only add things I need to the library

I only work on the modules I use

if you want to improve it and make it more complete - create a pull request

**Comment by aligokalppeker** [comment]
Dear @walec51,

As i said in the first comment, I am already preparing a PR. This is software life cycle problem, can not be fixed with just one PR. The philosophy i tried to tell you is far more than "just fixing an issue within an exchange". What about other generic exchange interfaces ? What about implementing an exchanges functionality just based on "your needs" ? This is the major problem of main stream "open source" projects in the industry.

But as i see the comments, i can not make you understand, or create an awareness of the issue. I closing it. Talking about this issue seems useless.

**Comment by walec51** [comment]
We are aware of the issue. And no - its not a life cycle issue.

What is your proposed solution?

Not to accept PRs if they do not implement every feature required by generic interface?

If so then you can remove 9 out of 10 modules from this repo and kill this project. No one ever provided a 100% complete implementation of a exchange in one PR and no one ever will. This is an on going effort - eventually we might get there for most big exchanges.

Every one which uses this library works only on the features they need. Every time I find some missing feature in those generic interfaces I add it and submit a PR. If you stop accepting PRs with partial implementations then I and every one else will just stop submitting them to this project.

**Comment by aligokalppeker** [comment]
Then please update the "exchange support" page to reflect the true state of the project. Also we should remove or write a warning about the "generic examples" from the introductory "readme" page though generic interface are not implemented properly.

This project should not misguide people, neither intentional or otherwise....
