### ISSUE TITLE
Build  schedule? (USE_SANDBOX) - 5.0.10-SNAPSHOT?

### ISSUE THREAD

**Issue by CaelumF** [knowm/XChange#4135]
Hello!

USE_SANDBOX for Binance's testnet has been broken recently by Binance's changes. Deprecated WAPI is removed and 404s now I think. The latest code on this repo, with the latest pom.xml version of 5.0.10-SNAPSHOT works great and with it I can use USE_SANDBOX.

Though, the snapshots only goes up to 5.0.9-SNAPSHOT. Are these snapshots built under any criteria? Is there a schedule to build them?

I have been trying to use the source code on my own, which works for the Spot module but I am having difficulty with the streaming module, which I am trying with copy+pasted source because I also not been smart enough to build the jars locally, since they seem to depend on each other through the snapshot repo.

I think my troubles will be resolved just with some patience to wait for 5.0.10-SNAPSHOT to be available, but I am curious when that build will be made (assuming the code on develop branch is already suitable for a build)

Thanks!

**Comment by wlk** [comment]
Hi, I confirm that `5.0.10-SNAPSHOT` isn't published even though it says that in the README, what's the status here?

**Comment by wlk** [comment]
I suspect that lack of snapshots is due to Travis CI:

>  Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

This requires attention of the project owner(s) to update the build configuration

**Comment by CaelumF** [comment]
@timmolter

**Comment by andre77** [comment]
any progress here?
the issue is still present
the SNAPSHOT dependency seems not usable now

**Comment by timmolter** [comment]
I'm working on getting this up and running on github actions pipelines as travis-ci is no longer working.

**Comment by timmolter** [comment]
it's now working again.
