### ISSUE TITLE
Invalid Api-Key ID in v5.0.9 but not in v5.0.8

### ISSUE THREAD

**Issue by ts-00** [knowm/XChange#4137]
I updated the xchange-binance version from 5.0.8 to 5.0.9 (and changed nothing in my code). After updating the lib, the following error happens:

`Caused by: org.knowm.xchange.binance.dto.BinanceException: Invalid Api-Key ID. (HTTP status code: 400)`

Switching back to 5.0.8, no error and it works. Is there a **changelog** I can look what or why this breaks?

**Comment by makarid** [comment]
I have the same problem.

**Comment by makarid** [comment]
Any news on this one?

**Comment by makarid** [comment]
I have found the issue. The problem is on the getAssetDetails call on the remoteInit. If you complete delete it, it will work

**Comment by cymp** [comment]
Fixed here : https://github.com/knowm/XChange/pull/4198
