### ISSUE TITLE
Binance: Resilience - how to disable inital wait time

### ISSUE THREAD

**Issue by ts-00** [knowm/XChange#4140]
Currently, when using xchange api (for example, binance xchange api) there is an initial wait time before the request is fired (because of **resilience4j**). Is there a way to disable this first inital wait time (first inital "waitDuration") or set it to a lower value?

**Comment by walec51** [comment]
I'm not awary of any initial wait time

could you provide some logs that showcase this?

**Comment by ts-00** [comment]
It seems that the initial wait time only happens when calling any method within a Junit-Test-case:

```
@Test
final void callBars() {
// setup connection
var conn = ExchangeFactory.INSTANCE.createExchange(BinanceExchange.class, apiKey, secretKey);
// call method
var orderbook = conn.getMarketDataService().getOrderBook(...)
assertNotNull(orderbook);
}
```

I think this happens because of resilience4j which has an initial waitDuration by default.

**Comment by ts-00** [comment]
> Am curious if 
> conn.remoteInit(); 
> shortcuts the delay you encounter.

Good point. The "conn.remoteInit();" is called each time the `BinanceExchange` is created because by default `shouldLoadRemoteMetaData` is set to true.

```
// according to ExchangeSpecification.java
 private boolean shouldLoadRemoteMetaData = true; // default value
```
