### ISSUE TITLE
Support for Options markets

### ISSUE THREAD

**Issue by vasylp3** [knowm/XChange#4154]
In continuation to [Futures markets](https://github.com/knowm/XChange/issues/3171) I'd like to suggest Options markets support.
First of all it requires adding a new type of Instrument - OptionsContract.

Secondly, I'd like OrderBook class to be extended with a map of generic parameters, where option specific data like iv, greeks etc can be stored.

Further steps include:
-using AccountInfo#openPositions for both Futures and Options, which will require some modifications as well;
-adding TradeService#getInstruments() to fetch Futures/Options instruments currently available.

If the community supports the idea, I will create a PR.

**Comment by earce** [comment]
This sounds interesting to me, maybe even a small draft may be worth putting up and getting feedback?

**Comment by walec51** [comment]
We already have a method

Exchange#getExchangeInstruments

In https://github.com/knowm/XChange/issues/3171 we decided that we should go for a more generic API and to avoid adding methods specific for derivatives. To do this we started replacing the usage of CurrencyPair with a more generic term: Instrument

The above method should return everything: spot currency pairs, futures and options <- so just add mappings for that in there

As for the OrderBook  please post some pseudocode here to review before doing an implementation and make sure that the fields you want to add are not exchange specific

**Comment by vasylp3** [comment]
Please check xchange-core changes first. Short description:
-introduced OptionsContract next to FuturesContract;
-changed derivative serializar separator from '/' to '-';
-added meta for futures and options;
-added instrument methods to MarketDataService for ticker, trades and order book.
