### ISSUE TITLE
[Kraken] KrakenStreamingAdapters.adaptOrderbookMessage always sets lastTime to 1/1/1970

### ISSUE THREAD

**Issue by wlk** [knowm/XChange#4172]
There is a bug in `KrakenStreamingAdapters.adaptOrderbookMessage` the `lastTime` value is never updated and this results in always returning same value which is epoch time = 0.

line 60:
```
        final AtomicReference<Date> lastTime = new AtomicReference<>(Date.from(Instant.EPOCH));
```

line 91:
```
        return new OrderBook(lastTime.get(), Lists.newArrayList(asks), Lists.newArrayList(bids), true);
```

There are 2 options I see as a potential fix:
- Set time equal to latest timestamp observed in the individual orders
- Or, Set time to "current time"

ping @nielsdraaisma 

This affects current `develop` branch

**Comment by Gepro83** [comment]
@wlk are you able to place orders with the current version of the kraken libarry? I get "EGeneral:Invalid arguments" exception when using like this:

    ```
kraken.tradeService.placeMarketOrder(MarketOrder.Builder(org.knowm.xchange.dto.Order.OrderType.BID, CurrencyPair.ETH_EUR)
        .originalAmount(BigDecimal("0.001"))
        .build())
```
API key etc works, i can querry the wallet balance...

**Comment by earce** [comment]
@Gepro83 you probably are missing something in your request.

@wlk I think the last timestamp across all orders is more accurate otherwise you are just timestamping when XChange received the order

**Comment by wlk** [comment]
The "per order" timestamp is set correctly, but "per orderbook" timestamp is set to null, it's not provided directly by Kraken, possible options:
- set to  `null` 
- set timestamp = current time
- set timestamp = MAX of all individual orders in the book

the current behavior of setting timestamp to `0` is a bug to me, wdyt?

**Comment by earce** [comment]
Yea @wlk I understand, and what I was saying is that I think #3 makes the most sense otherwise as mentioned you are just timestamping the message when your systems receives it.

**Comment by timmolter** [comment]
Traditionally, for this project, we would set the timestamp (Date) to null indicating that the server doesn't provide any timestamp. In this case however I think option #3 makes the most sense since the timestamp can be inferred by the other data.

**Comment by mdvx** [comment]
Up vote! i see the Timestamp passed, and then get lost

**Comment by ldrygala** [comment]
I would like to fix this issue. PR should be ready this week.
