### ISSUE TITLE
Bittrex OrderStatus is wrong

### ISSUE THREAD

**Issue by BernatCarbo** [knowm/XChange#4180]
Hello there,

I noticed that order status from a canceled order is `OrderStatus.NEW` while it should be `OrderStatus.CANCELED`, looks like the function `adaptOrderStatus` is ignoring the order status returned by Bittrex..

**Comment by jecker7** [comment]
Which function from the Bittrex API are you using to cancel the order? From their v3 API it looks like only type OrderStatus.CLOSED is supported after canceling Order types (OrderStatus.CANCELED is provided for ConditionalOrder types, but this doesn't look to be supported by XChange Bittrex API currently). I think my MR here should fix this: https://github.com/knowm/XChange/pull/4183

**Comment by BernatCarbo** [comment]
I use the `exchange.cancelOrder(orderId)` function which seems to call the `DELETE v3/orders/{order_id}` endpoint from Bittrex.

**Comment by earce** [comment]
addressed with pr
