### ISSUE TITLE
[FTX] No implementation of MarketDataService.getTicker

### ISSUE THREAD

**Issue by mathvdh** [knowm/XChange#4195]
Hi All,

There is no implementation of `getTicker` for the Market Data Service.

According to the FTX docs, they don't really give tickers as defined in Xchange.
But by combining the information of `getMarket` and `getCandles` (which I added) we can fill a full ticker.
I will submit this implementation shortly.

Let me know if it's OK for you or if you have any comments or maybe a simple way of getting this info.

Thanks

**Comment by cymp** [comment]
Good practices in this project is to use only one API call per operations. If not possible, please take care of rate limits by using [resilience](https://github.com/knowm/XChange/wiki/Implementing-resiliency-features).

**Comment by mathvdh** [comment]
@cymp Ok thanks, I'll have a look ... and come back to discuss it

**Comment by earce** [comment]
I saw this was merged I put a comment on there closing this as complete
