### ISSUE TITLE
[FTX] Dependencies issue

### ISSUE THREAD

**Issue by elkceo** [knowm/XChange#4247]
When I am adding dependencies for ftx
`<dependency>
			<groupId>org.knowm.xchange</groupId>
			<artifactId>xchange-ftx</artifactId>
			<version>5.0.9</version>
		</dependency>
		<dependency>
			<groupId>org.knowm.xchange</groupId>
			<artifactId>xchange-stream-ftx</artifactId>
			<version>5.0.9</version>
		</dependency>`
I cant use FtxStreamingTradeService, It says .NotYetImplementedForExchangeException: getStreamingTradeService
But I see on github there's methods getStreamingTradeService().getOrderChanges() or getUserTrades();
But in source file it doesnt exist. Any idea how to fix it? 
![image](https://user-images.githubusercontent.com/48324597/130834910-c35e35e5-754f-42f0-92bd-eafd8e763f98.png)

**Comment by earce** [comment]
does 5.0.10 have it?
