### ISSUE TITLE
FTX get historical prices

### ISSUE THREAD

**Issue by yoobi** [knowm/XChange#4295]
Hello, according to the documentation we can specify a `start_time` and an `end_time` query parameters, these two parameters aren't in the lib https://github.com/knowm/XChange/blob/2791382c76f722c979b9925f80a78992600d5a67/xchange-ftx/src/main/java/org/knowm/xchange/ftx/Ftx.java#L41

I can make the change and create a MR if you need, or you can do it as well, it's rather quick
```java
@Path("/markets/{market_name}/candles")
  @Consumes(MediaType.APPLICATION_JSON)
  FtxResponse<List<FtxCandleDto>> getCandles(
          @PathParam("market_name") String market, @QueryParam("resolution") String resolution,
          @QueryParam("start_time") String startTime, @QueryParam("end_time") String endTime, @QueryParam("limit") Integer limit
) throws IOException, FtxException;
```

PS: Note that the current `getCandles` use `@PathParam("resolution")` instead of `@QueryParam`

EDIT: I've also noticed that there is a limit queryParam we can add (where the max limit is 5000) see following
https://ftx.com/api/markets/BTC/USDT/candles?resolution=3600&start_time=1539881511&end_time=1634979516&limit=5000

**Comment by timmolter** [comment]
please submit a PR and we'll happily merge it.
