### ISSUE TITLE
[CoinbasePro] Websocket Reconnection failed

### ISSUE THREAD

**Issue by garciapd** [knowm/XChange#4320]
Hi, is anybody getting this error?

` i.b.xchangestream.coinbasepro.CoinbaseProStreamingService - Reconnection failed: invalid WebSocket Extension handshake for "permessage-deflate; server_no_context_takeover; client_no_context_takeover"`

and

`i.bitrich.xchangestream.service.netty.WebSocketClientHandler - WebSocket client [id: 0x0ee94488, L:/10.0.2.171:54379 - R:ws-feed.pro.coinbase.com/104.18.14.237:443] encountered exception (CodecException - invalid WebSocket Extension handshake for "permessage-deflate; server_no_context_takeover; client_no_context_takeover"). Closing`

**Comment by z-kovacs** [comment]
yes. any update on this?

**Comment by garciapd** [comment]
I have solved it but didn't have time to do a PR, I created:


`package info.bitrich.xchangestream.coinbasepro;

import static io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateServerExtensionHandshaker.MAX_WINDOW_SIZE;

import io.netty.channel.ChannelHandler;
import io.netty.handler.codec.compression.ZlibCodecFactory;
import io.netty.handler.codec.http.websocketx.extensions.WebSocketClientExtensionHandler;
import io.netty.handler.codec.http.websocketx.extensions.compression.DeflateFrameClientExtensionHandshaker;
import io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateClientExtensionHandshaker;

@ChannelHandler.Sharable
public final class WebSocketClientCompressionAllowClientNoContextHandler
        extends WebSocketClientExtensionHandler {

    public static final WebSocketClientCompressionAllowClientNoContextHandler INSTANCE =
            new WebSocketClientCompressionAllowClientNoContextHandler();

    private WebSocketClientCompressionAllowClientNoContextHandler() {
        super(
                new PerMessageDeflateClientExtensionHandshaker(
                        6, ZlibCodecFactory.isSupportingWindowSizeAndMemLevel(), MAX_WINDOW_SIZE, true, true),
                new DeflateFrameClientExtensionHandshaker(false),
                new DeflateFrameClientExtensionHandshaker(true));
    }
}`



and modify the CoinbaseProStreamingService to use the class above instead of

`import info.bitrich.xchangestream.service.netty.WebSocketClientCompressionAllowClientNoContextHandler;`

**Comment by z-kovacs** [comment]
Thank you! It seems upgrading to the latest xchange sorted it out as well, but will monitor the situation.

Thanks again!
