### ISSUE TITLE
Shorting on Binance

### ISSUE THREAD

**Issue by jurepetrovic** [knowm/XChange#4425]
Hello, 

I'm trying to short on binance through the use of xchange lib. 
Since margin shorting on binance is a multi step process
requiring borrowing and so on...

Does anyone of you short on binance using Xchange lib? 

Any idea appreciated. 
Thanks,
Jure

**Comment by jurepetrovic** [comment]
So, in other words - I'm asking if it's possible to margin trade on binance with xchange
and how should one go about it? 

Thanks,
Jure

**Comment by earce** [comment]
I do not know this to be supported you would have to add the functionality to the libs

**Comment by jurepetrovic** [comment]
Thank you for the answer!
I need to see if we want to do margin or not and then maybe I decide for implementation.
