### ISSUE TITLE
Feature Request - Any support for Bybit planned?

### ISSUE THREAD

**Issue by Christophe06410** [knowm/XChange#4430]
Hello,

Did you plan to support bybit?

For information, here is a good starting point: https://github.com/bybit-exchange/QuickStartWithPostman

Thank you
Christophe

**Comment by earce** [comment]
This project is mostly a labor of love for folks, we don't have a group actively creating new supported exchanges, feel free to open a PR!

**Comment by Christophe06410** [comment]
I will certainly.
