### ISSUE TITLE
How does StreamingExchange set up a proxy？

### ISSUE THREAD

**Issue by 597800451** [knowm/XChange#4450]
I try to do this

> ExchangeSpecification exSpec = new BinanceStreamingExchange().getDefaultExchangeSpecification();
 **exSpec.setProxyHost("127.0.0.1");
exSpec.setProxyPort(7890);
exSpec.setExchangeSpecificParametersItem(StreamingExchange.SOCKS_PROXY_HOST, "127.0.0.1");
exSpec.setExchangeSpecificParametersItem(StreamingExchange.SOCKS_PROXY_PORT, 7890);**
StreamingExchange exchange = StreamingExchangeFactory.INSTANCE.createExchange(exSpec);

Neither, hint:

> 02:44:34.822 [nioEventLoopGroup-2-1] ERROR info.bitrich.xchangestream.binance.BinanceStreamingService - Reconnection failed: **connection timed out**: stream.binance.com/66.220.146.94:9443
02:44:34.822 [nioEventLoopGroup-2-1] INFO info.bitrich.xchangestream.binance.BinanceStreamingService - Scheduling reconnection
02:44:49.824 [nioEventLoopGroup-2-1] INFO info.bitrich.xchangestream.binance.BinanceStreamingService - Connecting to wss://stream.binance.com:9443/stream?streams=btcusd@trade

This works fine on Exchange, but webSocket is always unavailable on StreamingExchange  
I'm at my wit's end

**Comment by kennethjor** [comment]
@597800451 Have you confirmed your local proxy supports WebSockets and that it allows connections to non-standard ports? It looks like Binance is trying to connect to port 9443. Are you able to connect without the proxy?

**Comment by 597800451** [comment]
I found another option. Use Clash and enable TUN mode. It can be used directly without a proxy

**Comment by gewure** [comment]
> I found another option. Use Clash and enable TUN mode. It can be used directly without a proxy

can you explain a little more detailed, for the sake of completeness in case anybody wants to use a Proxy too? <3
