### ISSUE TITLE
Update FTX getOpenPositions to return averge price of position rather than last trade price

### ISSUE THREAD

**Issue by m1dnightc0der** [knowm/XChange#4483]
When managing positions it is useful to have the average price of the position to calculate the pnl (i.e. average price-last price), currently the FTX adapter returns the last traded price which can be retrieved from the existing market data services, however the average price of the position can only be retrieved via the open positions api.

**Comment by m1dnightc0der** [comment]
okey, seem to be a issue with FTx giving the last trade price in the entry price.

**Comment by makarid** [comment]
I have fix it, you can close the issue

**Comment by douggie** [comment]
sorry thought I raised a PR, https://docs.ftx.com/#get-positions use
showAvgPrice in the call.
