### ISSUE TITLE
[Proposal] Create a new way to save metadata for all instruments

### ISSUE THREAD

**Issue by makarid** [knowm/XChange#4598]
Hello, i would like to propose a new implementation on the way that we save the currencyPair metadata of instruments. 
Right now every instrument has its own Map in which we add the metadata. I think this implementation has the following issues:

It is not possible to search for a specific Metadata on any instrument with just 1 search of a Map, you need to always check the type of the instrument and search on the specific Map. Also, because the DerivateMetadata and CurrencypairMetadata classes do not implement the same class, it is also difficult to make a generic function which searches for the type of instrument, searches to the correct Map and return the correct Metadata.

I propose to create a new interface named InstrumentMetadata which both CurrencyPairMetadata and DerivateMetadata classes will implement and create 1 Map for all instruments, instead of having 3 maps (currencyPair, futures, options).The Map will be of type Map<Instrument, InstrumentMetaData>. If you are ok with this i can implement it asap. I am waiting for your response/feedback. Thank you

**Comment by timmolter** [comment]
Sounds good. Please just make sure to refactor all legacy pas to the new API rather than having a new and a legacy impl.

**Comment by makarid** [comment]
Great i will start asap. Thanks

**Comment by makarid** [comment]
Merged
