### ISSUE TITLE
Release Schedule

### ISSUE THREAD

**Issue by gewure** [knowm/XChange#4599]
Hello there,

i've noticed there has not been a release in quite some time and i wanted to ask when a new release is expected and what one could do to speed the process up. 

We rely on xchange for one of our projects and we noticed its quite more comfortable to fork a own version and fix certain issues him/herself than to wait for a release - most do even build straight from the dev branch..

Would love to see a more regular release schedule!

**Comment by timmolter** [comment]
Coming soon! :)

**Comment by timmolter** [comment]
it's been released
