### ISSUE TITLE
getExchangeSymbols(), getExchangeInstruments don't work on MEXCExchange.

### ISSUE THREAD

**Issue by DongwonTTuna** [knowm/XChange#4616]
I'm sorry for my bad english.

Hello. I'm using  your Xchange Library for my trading bot program.

I'm now adding serveral exchanges to my program.

When I add the MEXC to it, The program doesn't work likes the other Exchanges.

So I checked the code and I found the Bug.

If I made a new Instance with MEXC and Run getExchangeSymbols() and getExchangeInstruments(),
It didn't return anything.

Thank you for developing this great library.

I really appreciate to your great work.

**Comment by makarid** [comment]
I have implement an update on these metadata structure, maybe it will work after the merge.
