### ISSUE TITLE
Automated releases

### ISSUE THREAD

**Issue by kennethjor** [knowm/XChange#4633]
A lot of time passes between releases on this project. I wonder if there have there been any discussions about setting up automated releases when merging PRs? I've set this up for several of my own projects and it works really well.

Some tools available:

* [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) using commit messages to decide which version number a PR should bump.
* [Github action](https://github.com/amannn/action-semantic-pull-request) to enforce conventional commit titles on PRs. Squash commits must be used when merging for this to work properly.
* [semantic-release](https://github.com/semantic-release/semantic-release) - manages the build process and can even manage [Github release pages](https://github.com/autonomouslogic/semantic-release-gradle-sonatype-example/releases/tag/0.4.27) and put [release notifications on PRs](https://github.com/autonomouslogic/semantic-release-gradle-sonatype-example/pull/47#issuecomment-1336646306).
* [Example repo](https://github.com/autonomouslogic/semantic-release-gradle-sonatype-example) I made a while ago to experiment with this in Gradle. I'm sure something similar could be done for Maven. Note that this doesn't actually run Semantic Release, I have that in a different private repo for security reasons.

I'd be happy to help with this if there's interest from the powers that be.

**Comment by timmolter** [comment]
Our process is set up and it works well and reliably. See the README about how often we push releases. I really appreciate the offer, but right now I barely have any time to commit to XChange and setting up a whole new process will probably take more time than I have right now unfortunately. I plan on pushing a new release ASAP, but there are a lot of big changes coming through right now.

**Comment by kennethjor** [comment]
Sure. Let me know if you want any assistance with it in the future :+1: Happy to help.
