### ISSUE TITLE
Binance FuturesContract orderBook depth20 instead of depth

### ISSUE THREAD

**Issue by rizer1980** [knowm/XChange#4667]
@makarid 
BinanceStreamingMarketDataService.java

```
if(instrument instanceof FuturesContract){
      return service.subscribeChannel(channelFromCurrency(instrument, BinanceSubscriptionType.DEPTH20.getType()))
```

Why in futures used depth20 instead of depth ?

**Comment by makarid** [comment]
Hello, I just put this as default, I think 20 depth is ok, maybe I am wrong.

**Comment by rizer1980** [comment]
Sorry, I was in a hurry with this report.
I looked at the code more carefully and realized that the getOrderBook for Futures is not ready yet.
Not implemented Diff. Depth Stream and separately getOrderBookUpdates
I'll try to finish these moments one of these days.
