### ISSUE TITLE
Please approve PR

### ISSUE THREAD

**Issue by rizer1980** [knowm/XChange#4685]
Hello.

@makarid 
Please confirm 3 PR .
https://github.com/knowm/XChange/pull/4669
https://github.com/knowm/XChange/pull/4670
https://github.com/knowm/XChange/pull/4671

If you have questions about them, then explain what

**Comment by trixprod** [comment]
The #4671 still has merge conflicts ?

**Comment by timmolter** [comment]
Yes, it does.

**Comment by rizer1980** [comment]
failed to resolve the conflict.
Removed the PR and made a new one
https://github.com/knowm/XChange/pull/4697
