### ISSUE TITLE
Bitget Implementation

### ISSUE THREAD

**Issue by m1dnightc0der** [knowm/XChange#4695]
Hi,

Anyone fancies collaborating on a bitget implementation (https://bitgetlimited.github.io/apidoc/en/mix/#update-log)

**Comment by chenenyu** [comment]
Bitget's market share is rapidly increasing, is there a plan to support it?

**Comment by bigscoop** [comment]
Fixed in https://github.com/knowm/XChange/pull/4944

@timmolter  Feel free to close the issue
