### ISSUE TITLE
need advice to OKX future placeOrder

### ISSUE THREAD

**Issue by rizer1980** [knowm/XChange#4728]
@makarid 
Hello
I want to ask for advice.
For now placing an order on OKX Futures does not work, since "posSide" should not contain "null", but "long" or "short".
Your comment from there OkexAdapters.java
```
        .posSide(null) // PosSide should come as a input from an extended LimitOrder class to
        // support Futures/Swap capabilities of Okex, till then it should be null to
        // perform "net" orders
```
Can you explain/suggest about the extended LimitOrder class?
It only occurs to me to implement this through somethinbg like order.hasFlag(OkexOrderFlags.LONG ))

Thanks!

**Comment by douggie** [comment]
Depends how you have your account set up on net or gross at okx. You can
set an order flag on you okx to set it, if you need to keep.long and short
positions separated.
