### ISSUE TITLE
Bybit problem with Instrument conversion for options. java.text.ParseException: Unparseable date: "31MAY24"

### ISSUE THREAD

**Issue by wesssup** [knowm/XChange#4828]
Exception thrown : java.text.ParseException: Unparseable date: "31MAY24" in BybitAdapters.java line 180

In  BybitAdapters.java line 172:
.expireDate(OPTION_DATE_FORMAT.parse(expireDateString)) it is trying to parse date "31MAY24" as option date.
==>Will work for all environments in a US setting
==> Will not work for non-us environments. In Dutch it's MEI for example but will work for JAN,FEB,....DEC...)

It can be solved by changing line 47
From
private static final SimpleDateFormat OPTION_DATE_FORMAT = new SimpleDateFormat("ddMMMyy");
TO
 SimpleDateFormat OPTION_DATE_FORMAT = new SimpleDateFormat("ddMMMyy",Locale.US);

**Comment by rizer1980** [comment]
please close

**Comment by ycyangcai** [comment]
this issue have also in version 5.2.1，why?

**Comment by rizer1980** [comment]
Hi, @ycyangcai 

Please provide more info or/and stacktrace of error.

**Comment by rizer1980** [comment]
Hello, @wesssup 

Gurrent develop branch have working code, with Locale.US
https://github.com/knowm/XChange/blob/2a77edb9ded8b8c76dd7f5b06914b3ff4f605d90/xchange-bybit/src/main/java/org/knowm/xchange/bybit/BybitAdapters.java#L54-L55
