### ISSUE TITLE
Bitget needs a maven artifact

### ISSUE THREAD

**Issue by arass** [knowm/XChange#4953]
Hi. 
Need a maven artifact for the new exchange ( Bitget ) you guys added. (thanks for that, btw). 

        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-bitget</artifactId>
            <version>${xchange.version}</version>
        </dependency>

Right now this gets me nothing. 
Also read.me is missing any reference to this (naturally). 

Thanks, guys.

**Comment by bigscoop** [comment]
Hi. 

Since bitget is new and wasn't included in any release yet, take the snapshot version

`<version>5.2.1-SNAPSHOT</version>`

**Comment by arass** [comment]
Can you explain in detail? 
What I see is that:
https://mvnrepository.com/search?q=xchange-bitget
doesn't exist yet for any version, as far as I can tell.

**Comment by timmolter** [comment]
See the README please.
<img width="873" alt="Screenshot 2024-10-14 at 6 12 34 PM" src="https://github.com/user-attachments/assets/ce161daf-49dd-41b1-8a5c-fc330d49478f">

**Comment by arass** [comment]
I have that repo in my maven and it doesn't see xchange-bitget for any version.

**Comment by arass** [comment]
https://oss.sonatype.org/content/repositories/snapshots/org/knowm/xchange/xchange-bitget/5.2.1-SNAPSHOT/

is a 404!
