### ISSUE TITLE
Bitget needs a maven artifact

### ISSUE THREAD

**Issue by arass** [knowm/XChange#4954]
Continuation of https://github.com/knowm/XChange/issues/4953 cause someone who is NOT the person who opened the issue decided to closed the issue. Bad process, guys!!!

Updated to reduce reading:
------
Hi.
Need a maven artifact for the new exchange ( Bitget ) you guys added. (thanks for that, btw).

    <dependency>
        <groupId>org.knowm.xchange</groupId>
        <artifactId>xchange-bitget</artifactId>
    </dependency>

Right now this gets me nothing.
I do have the sonartype.org repo in my maven as well.
Also read.me is missing any reference to this (naturally).

Thanks, guys.

--- 

was replied with a "go read manual" and add secondary maven repo. which I did like a year ago. 
So this was clearly not the answer. 

https://oss.sonatype.org/content/repositories/snapshots/org/knowm/xchange/xchange-bitget/5.2.1-SNAPSHOT/

**is a 404!**

https://oss.sonatype.org/content/groups/public/org/knowm/xchange/
doesn't have any bitget jars either. 

There's clearly a missing artifact, like I stated. **Can someone who's serious please take a look?**

**Comment by timmolter** [comment]
It seems as though the deployment to sonatype has failed recently, explaining why the SNAPSHOTs are not there. I'm looking into it. Thanks for bringing this issue to light!

**Comment by timmolter** [comment]
OK, It's working again: https://oss.sonatype.org/content/groups/public/org/knowm/xchange/xchange-bitget/

**Comment by arass** [comment]
You rock. Thank you muchly!
