### ISSUE TITLE
[Binance] KLine/Ticker interval

### ISSUE THREAD

**Issue by malakeel** [knowm/XChange#4963]
I am trying to get CandleStick data using streaming api and migrate existing code from binance-connector-java. It seems the interval is not respected: 

`
ExchangeSpecification spec = StreamingExchangeFactory.INSTANCE
				.createExchange(BinanceStreamingExchange.class)
				.getDefaultExchangeSpecification();

		BinanceStreamingExchange exchange = (BinanceStreamingExchange) StreamingExchangeFactory.INSTANCE
				.createExchange(spec);

		ProductSubscription subscription = ProductSubscription.create()
				.addTicker(CurrencyPair.BTC_USDT).build();

		exchange.connect(subscription).blockingAwait();
		exchange.enableLiveSubscription();

		BinanceStreamingMarketDataService marketDataService = exchange.getStreamingMarketDataService();

		Observable<?> service = marketDataService
				.getTicker(CurrencyPair.BTC_USDT, KlineInterval.m15);

		Disposable klines = service.subscribe(data -> {
			LOG.info("Candlestick: {}", data);
		});
`

The problem with the above code is causes the websocket to emit events multiple times a second. Changing to use 'addKline()' gives the same results. So my questions:
- In Binance terminology kLine is used to obtain a candleStick data (timestamp, open, close .. etc). What is the equivalent in XChange?
- Does XChange-binance respece subscription to specific timeframe (1 minute, 5 minutes , 15 min) ? This does not look like the case, or I am using it in wrong way.

**Comment by rizer1980** [comment]
Hi, @malakeel 
According to binance Api docs(https://binance-docs.github.io/apidocs/spot/en/#kline-candlestick-streams-for-utc)
Update Speed: 1000ms for 1s, 2000ms for the other intervals Kline/Candlestick chart intervals

There is an example of usage in the tests folder  [BinanceKlineExample](https://github.com/knowm/XChange/blob/develop/xchange-stream-binance/src/test/java/info/bitrich/xchangestream/binance/BinanceKlineExample.java)
I think the code should be something like this:
```
Map<Instrument, Set<KlineInterval>> klineSubscriptionMap = new HashMap<>();
    HashSet<KlineInterval> intervals = new HashSet<>();
    intervals.add(KlineInterval.m1);
    klineSubscriptionMap.put(new CurrencyPair("BTC/USDT"), intervals);
    exchange
        .connect(new KlineSubscription(klineSubscriptionMap))
        .blockingAwait();
```

**Comment by malakeel** [comment]
@rizer1980 
Thank you. My bad. I forgot that I need to filter the events by isClosed() to get the actual candle-stick data for that specific time frame. I appreciate the quick reply.
