### ISSUE TITLE
Huobi Streaming Data

### ISSUE THREAD

**Issue by ghost** [knowm/XChange#721]
It is possible to implement huobi streaming data via websockets?

**Comment by bryan4887** [comment]
Just curious—why hasn't this been merged into XChange?

**Comment by jheusser** [comment]
@bryan4887  It's not a PR to XChange, it requires quite a bit of work.

**Comment by sutra** [comment]
xchange is growing bigger and bigger, do not like it anymore, it should be spilted into multiple projects, to be one exchange one git repo. And its project structure is not I preferred, should split the WebSocket from the rest as they has different dependencies.

**Comment by lazyp** [comment]
@sutra sometimes use rest and ws in the project

**Comment by glabmoris** [comment]
I'd be interested to build it, if nobody has started on it

**Comment by bryan4887** [comment]
@sutra I agree it has become big, but if it were to be split into different repos, both by exchange _and_ by websocket v. REST, then how would you enforce a common interface?  That, to me, is the greatest advantage of keeping the project together, albeit a bit harder to organize.
